package entity

import (
	"bytes"
	"crypto/md5"
	"fmt"
	"go/format"
	"os"
	"strings"
	"text/template"
)

const generatorVersion = "v2"

// generate produces the wiring file for an entity.
// Returns true if the file was written (changed).
func generate(ent EntityDef, pkg string, outFile string, force bool) (bool, error) {
	remoteV2 := ent.RemotePolicy == "entity.RemotePolicyManaged"
	if remoteV2 && !ent.RemoteBase {
		return false, fmt.Errorf("entity %s: remote=managed requires embedding *entity.RemoteEntityBase", ent.Name)
	}
	var buf bytes.Buffer

	data := templateData{
		Package:  pkg,
		Entity:   ent,
		HasDaos:  len(ent.Daos) > 0,
		HasComps: len(ent.Components) > 0,
		HasDirty: hasDirtyDao(ent),
		RemoteV2: remoteV2,
	}
	data.NeedsRemove = data.HasDirty && !ent.NoPersist && !data.RemoteV2 && !hasMethod(ent, "PrepareDelete")
	data.ImportBlock = buildImportBlock(ent, data.RemoteV2 || data.NeedsRemove, data.RemoteV2, data.NeedsRemove)

	tmpl, err := template.New("entity_wire").Funcs(template.FuncMap{
		"deref":              derefType,
		"ctor":               constructorName,
		"quote":              quoteString,
		"syncTopic":          syncTopicExpr,
		"daoCollectionConst": daoCollectionConstExpr,
		"hasMethod":          hasMethod,
	}).Parse(wireTemplate)
	if err != nil {
		return false, fmt.Errorf("template parse: %w", err)
	}

	if err := tmpl.Execute(&buf, data); err != nil {
		return false, fmt.Errorf("template exec: %w", err)
	}

	content, err := format.Source(buf.Bytes())
	if err != nil {
		return false, fmt.Errorf("format generated source: %w", err)
	}

	// Check if file exists and content is unchanged
	if !force {
		existing, err := os.ReadFile(outFile)
		if err == nil {
			existingHash := fmt.Sprintf("%x", md5.Sum(existing))
			newHash := fmt.Sprintf("%x", md5.Sum(content))
			if existingHash == newHash {
				return false, nil
			}
		}
	}

	if err := os.WriteFile(outFile, content, 0644); err != nil {
		return false, err
	}

	return true, nil
}

func derefType(s string) string {
	if len(s) > 0 && s[0] == '*' {
		return s[1:]
	}
	return s
}

func constructorName(typeName string) string {
	name := derefType(typeName)
	if idx := strings.LastIndex(name, "."); idx >= 0 {
		return name[:idx+1] + "New" + name[idx+1:]
	}
	return "New" + name
}

func quoteString(s string) string {
	return fmt.Sprintf("%q", s)
}

func syncTopicExpr(s string) string {
	if s == "" {
		return `""`
	}
	if isConstExpr(s) {
		return s
	}
	return quoteString(s)
}

func daoCollectionConstExpr(typeName string) string {
	name := derefType(typeName)
	qualifier := ""
	if idx := strings.LastIndex(name, "."); idx >= 0 {
		qualifier = name[:idx+1]
		name = name[idx+1:]
	}
	return qualifier + name + "Collection"
}

func isConstExpr(s string) bool {
	if strings.ContainsAny(s, "\"'`") {
		return false
	}
	idx := strings.Index(s, ".")
	if idx <= 0 || idx == len(s)-1 {
		return false
	}
	first := s[0]
	if (first < 'A' || first > 'Z') && (first < 'a' || first > 'z') && first != '_' {
		return false
	}
	for _, r := range s[:idx] {
		if (r < 'A' || r > 'Z') && (r < 'a' || r > 'z') && (r < '0' || r > '9') && r != '_' {
			return false
		}
	}
	afterDot := s[idx+1]
	return afterDot >= 'A' && afterDot <= 'Z'
}

func hasDirtyDao(ent EntityDef) bool {
	return len(ent.Daos) > 0
}

func hasMethod(ent EntityDef, name string) bool {
	return ent.ExistingMethods != nil && ent.ExistingMethods[name]
}

func buildImportBlock(ent EntityDef, needsFmt, needsCheckpoint, needsNest bool) string {
	var groups [][]string
	std := []string{`"sync"`}
	if needsFmt {
		std = append([]string{`"fmt"`}, std...)
	}
	groups = append(groups, std)

	local := make([]string, 0, len(ent.Imports)+2)
	for _, imp := range ent.Imports {
		if imp.Explicit {
			local = append(local, fmt.Sprintf(`%s "%s"`, imp.Alias, imp.Path))
		} else {
			local = append(local, fmt.Sprintf(`"%s"`, imp.Path))
		}
	}
	if needsCheckpoint {
		local = append(local, `"github.com/tjbdwanghaibo/cube-core/checkpoint"`)
	}
	if needsNest {
		local = append(local, `"github.com/tjbdwanghaibo/cube-core/nest"`)
	}
	local = append(local, `"github.com/tjbdwanghaibo/cube-core/entity"`)
	groups = append(groups, local)

	var b strings.Builder
	for i, group := range groups {
		if i > 0 {
			b.WriteByte('\n')
		}
		for _, line := range group {
			b.WriteByte('\t')
			b.WriteString(line)
			b.WriteByte('\n')
		}
	}
	return b.String()
}

type templateData struct {
	Package     string
	Entity      EntityDef
	ImportBlock string
	HasDaos     bool
	HasComps    bool
	HasDirty    bool
	RemoteV2    bool
	NeedsRemove bool
}

var wireTemplate = `// Code generated by tool/entity. DO NOT EDIT.
package {{.Package}}

import (
{{.ImportBlock -}}
)

var registerEntityOnce sync.Once

// RegisterEntity registers the {{.Entity.Name}} entity builder.
func RegisterEntity() {
	registerEntityOnce.Do(func() {
		entity.RegisterEntityBuilder(&entity.EntityBuilderParam{
			Category: entity.MustEntityCategoryOfKind({{.Entity.EntityKind}}),
			Kind: {{.Entity.EntityKind}},
			Builder: func(param *entity.EntityCreateParam) (entity.IThreadSafeEntity, error) {
				return New{{.Entity.Name}}(param)
			},
{{- if .HasDaos}}
			DaoBuilders: []entity.DaoBuilderFunc{
{{- range .Entity.Daos}}
				func() entity.DaoInterface { return {{ctor .TypeName}}() },
{{- end}}
			},
{{- end}}
			NoPersist: {{.Entity.NoPersist}},
{{- if .Entity.RemotePolicy}}
			RemotePolicy: {{.Entity.RemotePolicy}},
{{- end}}
{{- if .Entity.Lifetime}}
			Lifetime: {{.Entity.Lifetime}},
{{- end}}
{{- if .Entity.Sync}}
			Sync: entity.EntitySyncBuilderParam{
				Enabled:     true,
				Topic:       {{syncTopic .Entity.SyncTopic}},
				FlushPolicy: entity.SyncFlushOnEntityRelease,
{{- if .Entity.SyncPacker}}
				PackerFactory: {{.Entity.SyncPacker}},
{{- end}}
{{- if .Entity.SubjectPacker}}
				SubjectPackerFactory: {{.Entity.SubjectPacker}},
{{- end}}
			},
{{- end}}
		})
{{- if .RemoteV2}}
{{- range .Entity.Daos}}
		entity.MustRegisterRemoteSnapshotDecoder(
			entity.RemoteSnapshotSchema({{$.Entity.EntityKind}}, entity.RemoteSnapshotScope({{daoCollectionConst .TypeName}})),
			func(data []byte) (any, error) {
				dao := {{ctor .TypeName}}()
				decoder, ok := any(dao).(interface{ ApplySync([]byte) error })
				if !ok {
					return nil, fmt.Errorf("{{$.Entity.Name}}: remote snapshot DAO {{.CollName}} does not implement ApplySync")
				}
				if err := decoder.ApplySync(data); err != nil {
					return nil, err
				}
				return dao, nil
			},
		)
{{- end}}
{{- end}}
	})
}

func New{{.Entity.Name}}(param *entity.EntityCreateParam) (*{{.Entity.Name}}, error) {
	e := &{{.Entity.Name}}{}
	if err := param.NormalizeID({{.Entity.EntityKind}}); err != nil {
		return nil, err
	}

	// EntityBase
{{- if .RemoteV2}}
	e.RemoteEntityBase = entity.NewRemoteEntityBaseWithMutex(param.Id, param.Category, {{.Entity.NoPersist}}, param.Mutex, param.Kind)
{{- else}}
	e.EntityBase = entity.NewEntityBaseWithMutex(param.Id, param.Category, {{.Entity.NoPersist}}, param.Mutex, param.Kind)
{{- end}}
	e.EntityBase.SetHooks(e.generatedOnClear, e.generatedOnDestroy)

{{- if .HasComps}}

	// ComponentManager
	e.ComponentManager = entity.NewComponentManager()
{{- end}}
{{- if .HasDaos}}

	// DaoManager
	e.DaoManager = entity.NewDaoManager()
{{- end}}

{{- range .Entity.Daos}}

	// DAO: {{.FieldName}}
	if raw, ok := param.Dao[{{daoCollectionConst .TypeName}}]; ok {
		e.{{.FieldName}} = raw.({{.TypeName}})
	} else {
{{- if .Cold}}
		// cold DAO: initialized on demand
{{- else}}
		e.{{.FieldName}} = {{ctor .TypeName}}()
		e.{{.FieldName}}.SetId(param.StorageID())
{{- end}}
	}
	if e.{{.FieldName}} != nil {
		e.DaoManager.Set({{daoCollectionConst .TypeName}}, e.{{.FieldName}})
	}
{{- end}}

{{- range .Entity.Components}}

	// Component: {{.FieldName}}
{{- if .Cold}}
	// cold component: initialized on demand
{{- else}}
	if comp, err := entity.CreateComponent({{.CompType}}, e, param); err != nil {
		return nil, err
	} else {
		e.{{.FieldName}} = comp.({{.TypeName}})
	}
	e.ComponentManager.Set({{.CompType}}, e.{{.FieldName}})
{{- end}}
{{- end}}

{{- if .HasComps}}

	// Initialize all components in dependency order
	if err := e.ComponentManager.InitAll(param, param.IsCreate); err != nil {
		return nil, err
	}
{{- end}}

	return e, nil
}
{{- if not (hasMethod .Entity "Base")}}

{{- if .RemoteV2}}
func (e *{{.Entity.Name}}) Base() *entity.EntityBase { return &e.RemoteEntityBase.EntityBase }
{{- else}}
func (e *{{.Entity.Name}}) Base() *entity.EntityBase { return e.EntityBase }
{{- end}}
{{- end}}
{{- range .Entity.Components}}
{{- if and .GetterName (not (hasMethod $.Entity .GetterName))}}

func (e *{{$.Entity.Name}}) {{.GetterName}}() {{.GetterType}} { return e.{{.FieldName}} }
{{- end}}
{{- end}}
{{- range .Entity.Daos}}
{{- if and .GetterName (not (hasMethod $.Entity .GetterName))}}

func (e *{{$.Entity.Name}}) {{.GetterName}}() {{.TypeName}} { return e.{{.FieldName}} }
{{- end}}
{{- end}}

func (e *{{.Entity.Name}}) generatedOnClear() {
{{- if .HasComps}}
	e.ComponentManager.Clear()
{{- end}}
{{- if .HasDaos}}
	e.DaoManager.Clear()
{{- end}}
{{- range .Entity.Components}}
	e.{{.FieldName}} = nil
{{- end}}
{{- range .Entity.Daos}}
	e.{{.FieldName}} = nil
{{- end}}
}

func (e *{{.Entity.Name}}) generatedOnDestroy(reason entity.EntityDestroyReason) {
{{- if .HasComps}}
	e.ComponentManager.DestroyAll(reason)
{{- end}}
}
{{- if .RemoteV2}}

var _ entity.IRemoteCommitParticipant = (*{{.Entity.Name}})(nil)

// BuildRemoteCommitLocked freezes DAO state while Nest holds the entity mutex.
// The returned commit owns all byte slices and is safe for asynchronous WAL use.
func (e *{{.Entity.Name}}) BuildRemoteCommitLocked(lease entity.RemoteWriteLease, outcome entity.RemoteTransactionOutcome) (entity.RemoteCommit, error) {
	commit := entity.RemoteCommit{
		TransactionID: outcome.TransactionID,
		EntityID:      e.GUId(),
		Kind:          e.GetEntityKind(),
		Delete:        e.IsRemoved(),
		BaseVersion:   lease.BaseVersion,
		NextVersion:   lease.BaseVersion + 1,
		MarkerEpoch:   lease.MarkerEpoch,
		LockFence:     lease.LockFence,
		RouteEpoch:    lease.RouteEpoch,
		Schema:        1,
		Codec:         1,
	}
	if commit.Delete {
{{- range .Entity.Daos}}
		if e.{{.FieldName}} != nil {
			commit.Deletes = append(commit.Deletes, entity.RemoteDataDelete{
				Database: e.{{.FieldName}}.DbName(), DatabaseScope: uint8(checkpoint.ResolveDatabaseScope(e.{{.FieldName}})),
				Collection: e.{{.FieldName}}.CollName(), ID: e.{{.FieldName}}.Id(),
			})
		}
		commit.Invalidations = append(commit.Invalidations, entity.RemoteSnapshotKey{
			EntityID: e.GUId(), Kind: e.GetEntityKind(), Scope: entity.RemoteSnapshotScope({{daoCollectionConst .TypeName}}),
		})
{{- end}}
		return commit, nil
	}
{{- range .Entity.Daos}}
	if e.{{.FieldName}} != nil {
		if mask := e.{{.FieldName}}.DirtyTracker().TakePersistDirty(); mask != 0 {
			data := append([]byte(nil), e.{{.FieldName}}.MarshalPersist(mask)...)
			if len(data) == 0 {
				e.{{.FieldName}}.DirtyTracker().RollbackPersist(mask)
				e.RollbackRemoteCommit(commit)
				return entity.RemoteCommit{}, fmt.Errorf("{{$.Entity.Name}}: empty remote mutation for {{.CollName}}")
			}
			e.{{.FieldName}}.DirtyTracker().IncVersion()
			mutation := entity.RemoteDataMutation{
				Database:      e.{{.FieldName}}.DbName(),
				DatabaseScope: uint8(checkpoint.ResolveDatabaseScope(e.{{.FieldName}})),
				Collection:    e.{{.FieldName}}.CollName(),
				ID:            e.{{.FieldName}}.Id(),
				Version:       commit.NextVersion,
				Mask:          mask,
				Data:          data,
			}
			commit.Mutations = append(commit.Mutations, mutation)
			scope := entity.RemoteSnapshotScope(e.{{.FieldName}}.CollName())
			commit.Snapshots = append(commit.Snapshots, entity.RemoteSnapshotRecord{
				Key: entity.RemoteSnapshotKey{EntityID: e.GUId(), Kind: e.GetEntityKind(), Scope: scope},
				Schema:   entity.RemoteSnapshotSchema(e.GetEntityKind(), scope),
				Codec:    1,
				Full:     true,
				Data:     append([]byte(nil), data...),
				Checksum: entity.RemoteSnapshotChecksum(data),
			})
		}
	}
{{- end}}
	return commit, nil
}

// AcknowledgeRemoteCommit intentionally does not clear dirty bits: Build used
// atomic exchange, so any later business mutation is already in a new mask.
func (e *{{.Entity.Name}}) AcknowledgeRemoteCommit(commit entity.RemoteCommit) error {
	if commit.EntityID != e.GUId() {
		return fmt.Errorf("{{.Entity.Name}}: remote acknowledgement identity mismatch")
	}
	return nil
}

func (e *{{.Entity.Name}}) RollbackRemoteCommit(commit entity.RemoteCommit) {
	for _, mutation := range commit.Mutations {
		switch mutation.Collection {
{{- range .Entity.Daos}}
		case {{daoCollectionConst .TypeName}}:
			if e.{{.FieldName}} != nil {
				e.{{.FieldName}}.DirtyTracker().RollbackPersist(mutation.Mask)
			}
{{- end}}
		}
	}
}
{{- end}}
{{- if .NeedsRemove}}

// PrepareDelete registers versioned tombstones in the active Nest transaction.
func (e *{{.Entity.Name}}) PrepareDelete(tx *nest.RollbackTx) error {
	if tx == nil { return nest.ErrTransactionClosed }
{{- range .Entity.Daos}}
	if e.{{.FieldName}} != nil {
		participant, ok := any(e.{{.FieldName}}).(nest.MutationParticipant)
		if !ok { return fmt.Errorf("{{$.Entity.Name}}: DAO {{.CollName}} does not implement nest.MutationParticipant") }
		if err := tx.MarkPersistDelete(participant); err != nil { return err }
	}
{{- end}}
	return nil
}
{{- end}}
`
