package roost

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const generatedHeader = "// Code generated by roost-codegen. DO NOT EDIT."

type NewOptions struct {
	Name     string
	Module   string
	Out      string
	Services []string
	Mods     []string
	Features []string
	Versions VersionSpec
}

type SyncResult struct {
	Created   []string
	Updated   []string
	Unchanged []string
}

type plannedFile struct {
	Body  []byte
	Owned bool
}

type syncChange struct {
	rel     string
	path    string
	body    []byte
	before  []byte
	existed bool
}

func NewProject(options NewOptions) (SyncResult, string, error) {
	if !validName(options.Name) {
		return SyncResult{}, "", fmt.Errorf("invalid project name %q", options.Name)
	}
	manifest := DefaultManifest(options.Name, options.Module, options.Services, options.Mods, options.Features)
	mergeVersions(&manifest.Versions, options.Versions)
	if err := manifest.Validate(); err != nil {
		return SyncResult{}, "", err
	}
	target := options.Out
	if target == "" {
		target = options.Name
	}
	absTarget, err := filepath.Abs(target)
	if err != nil {
		return SyncResult{}, "", err
	}
	if _, err := os.Stat(absTarget); err == nil {
		return SyncResult{}, "", fmt.Errorf("target %s already exists", absTarget)
	} else if !os.IsNotExist(err) {
		return SyncResult{}, "", err
	}
	parent := filepath.Dir(absTarget)
	if err := os.MkdirAll(parent, 0o755); err != nil {
		return SyncResult{}, "", err
	}
	stage, err := os.MkdirTemp(parent, ".roost-project-*")
	if err != nil {
		return SyncResult{}, "", err
	}
	defer os.RemoveAll(stage)
	manifestRaw, err := manifest.Marshal()
	if err != nil {
		return SyncResult{}, "", err
	}
	if err := writeAtomic(filepath.Join(stage, ManifestName), manifestRaw, 0o644); err != nil {
		return SyncResult{}, "", err
	}
	result, err := syncManifest(stage, manifest)
	if err != nil {
		return SyncResult{}, "", err
	}
	if err := Generate(stage, GenerateOptions{Stdout: io.Discard}); err != nil {
		return SyncResult{}, "", fmt.Errorf("generate initial artifacts: %w", err)
	}
	if err := os.Rename(stage, absTarget); err != nil {
		return SyncResult{}, "", fmt.Errorf("commit project: %w", err)
	}
	return result, absTarget, nil
}

func SyncProject(root string) (SyncResult, error) {
	absRoot, err := filepath.Abs(root)
	if err != nil {
		return SyncResult{}, err
	}
	manifest, err := LoadManifest(absRoot)
	if err != nil {
		return SyncResult{}, err
	}
	result, err := syncManifest(absRoot, manifest)
	if err != nil {
		return SyncResult{}, err
	}
	if err := Generate(absRoot, GenerateOptions{Stdout: io.Discard}); err != nil {
		return SyncResult{}, fmt.Errorf("refresh generated artifacts: %w", err)
	}
	return result, nil
}

func syncManifest(root string, manifest Manifest) (SyncResult, error) {
	result, changes, err := planManifestSync(root, manifest)
	if err != nil {
		return SyncResult{}, err
	}
	for index, change := range changes {
		if err := writeAtomic(change.path, change.body, 0o644); err != nil {
			rollbackErr := rollbackSync(changes[:index])
			return SyncResult{}, errors.Join(fmt.Errorf("write %s: %w", change.rel, err), rollbackErr)
		}
	}
	return result, nil
}

func planManifestSync(root string, manifest Manifest) (SyncResult, []syncChange, error) {
	plan, err := renderProject(manifest)
	if err != nil {
		return SyncResult{}, nil, err
	}
	paths := make([]string, 0, len(plan))
	for path := range plan {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	var result SyncResult
	var changes []syncChange
	// Preflight the entire plan before writing anything. This prevents a late
	// ownership conflict from leaving an earlier generated file updated.
	for _, rel := range paths {
		file := plan[rel]
		path := filepath.Join(root, filepath.FromSlash(rel))
		current, readErr := os.ReadFile(path)
		switch {
		case readErr == nil && bytes.Equal(current, file.Body):
			result.Unchanged = append(result.Unchanged, rel)
		case readErr == nil && !file.Owned:
			result.Unchanged = append(result.Unchanged, rel)
		case readErr == nil:
			if !canOverwriteGenerated(rel, current) {
				return SyncResult{}, nil, fmt.Errorf("refusing to overwrite non-generated file %s", rel)
			}
			changes = append(changes, syncChange{rel: rel, path: path, body: file.Body, before: current, existed: true})
			result.Updated = append(result.Updated, rel)
		case os.IsNotExist(readErr):
			changes = append(changes, syncChange{rel: rel, path: path, body: file.Body})
			result.Created = append(result.Created, rel)
		default:
			return SyncResult{}, nil, readErr
		}
	}
	return result, changes, nil
}

func canOverwriteGenerated(rel string, current []byte) bool {
	return bytes.Contains(current, []byte("Code generated by roost-codegen")) ||
		strings.HasPrefix(rel, ".github/") ||
		strings.HasPrefix(rel, "deploy/dev/") ||
		strings.HasPrefix(rel, "deploy/shell/") ||
		strings.HasPrefix(rel, "deploy/docker/") ||
		strings.HasPrefix(rel, "deploy/k8s/")
}

func rollbackSync(applied []syncChange) error {
	var joined error
	for index := len(applied) - 1; index >= 0; index-- {
		change := applied[index]
		if change.existed {
			if err := writeAtomic(change.path, change.before, 0o644); err != nil {
				joined = errors.Join(joined, fmt.Errorf("rollback %s: %w", change.rel, err))
			}
			continue
		}
		if err := os.Remove(change.path); err != nil && !os.IsNotExist(err) {
			joined = errors.Join(joined, fmt.Errorf("rollback new %s: %w", change.rel, err))
		}
	}
	return joined
}

func writeAtomic(path string, data []byte, mode os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".roost-write-*")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)
	if _, err = tmp.Write(data); err != nil {
		_ = tmp.Close()
		return err
	}
	if err = tmp.Sync(); err != nil {
		_ = tmp.Close()
		return err
	}
	if err = tmp.Close(); err != nil {
		return err
	}
	if err = os.Chmod(tmpName, mode); err != nil {
		return err
	}
	if err = os.Rename(tmpName, path); err != nil {
		// Windows cannot atomically replace an existing destination. Preserve a
		// recoverable backup during the short replacement window.
		backup := path + ".roost-backup"
		_ = os.Remove(backup)
		if moveErr := os.Rename(path, backup); moveErr != nil {
			return err
		}
		if moveErr := os.Rename(tmpName, path); moveErr != nil {
			_ = os.Rename(backup, path)
			return moveErr
		}
		_ = os.Remove(backup)
	}
	return nil
}

func mergeVersions(target *VersionSpec, override VersionSpec) {
	if override.Core != "" {
		target.Core = override.Core
	}
	if override.Kit != "" {
		target.Kit = override.Kit
	}
	if override.Skill != "" {
		target.Skill = override.Skill
	}
	if override.Codegen != "" {
		target.Codegen = override.Codegen
	}
}

func printSyncResult(w io.Writer, result SyncResult) {
	for _, path := range result.Created {
		fmt.Fprintf(w, "created: %s\n", path)
	}
	for _, path := range result.Updated {
		fmt.Fprintf(w, "updated: %s\n", path)
	}
	fmt.Fprintf(w, "summary: created=%d updated=%d unchanged=%d\n", len(result.Created), len(result.Updated), len(result.Unchanged))
}

func projectRoot(start string) (string, error) {
	root, err := filepath.Abs(start)
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(root, ManifestName)); err == nil {
			return root, nil
		}
		parent := filepath.Dir(root)
		if parent == root {
			return "", errors.New("roost.yaml not found")
		}
		root = parent
	}
}
