package roost

import (
	"fmt"
	"strings"
)

func renderBeginnerQuickstart(m Manifest) string {
	service := sortedServiceNames(m)[0]
	const guide = `<!-- Code generated by roost-codegen. DO NOT EDIT. -->
# {{NAME}} 零基础快速开始

这份教程假设你只会运行基本命令。先照着完成一次，再阅读完整功能说明。

## 1. 准备环境

必须安装：

- Go 1.25 或项目 go.mod 指定的更高兼容版本；
- Git；
- GNU Make；
- 能访问 Go module proxy 或 GitHub。

只有使用 Redis、MongoDB、NATS、etcd 等 Mod 时才需要 Docker。执行以下命令确认环境：

    roost version
    roost env doctor
    roost help beginner

## 2. 先理解五个词

| 名称 | 它是什么 | 初学时在哪里修改 |
| --- | --- | --- |
| Service | 一个可独立启动的游戏服务进程，例如 game、gate | internal/service/<name> |
| Mod | Service 启动时装配的基础设施能力，例如 etcd、mongo、nest | roost.yaml 的 services.<name>.mods |
| Feature | 决定生成哪些代码和目录的开关，例如 protocol、entity、dao | roost.yaml 的 features |
| Access | 已认证请求进入业务的边界，例如 player | roost.yaml 的 access |
| Generated file | codegen 管理、带 DO NOT EDIT 标识的文件 | 不手改；修改声明后运行 make sync/generate |

Mod 是运行时能力，Feature 是生成期能力，它们不是同一组选项。

## 3. 第一次生成和检查

项目已经创建时，在项目根目录执行：

    make deps-update
    make next

只执行 next 输出的当前一行，完成后再次 make next。阶段结束时它会明确要求 generate、doctor 和 test。
generate 会在临时项目完成全部生成器和不升级版本的 go mod tidy，补齐新生成 import 所需的
go.mod/go.sum；全部成功后才提交，后置步骤失败不会留下半生成工程。
失败时先读错误信息中的文件名，不要删除生成标识或手工修改 generated.go 绕过错误。

## 4. 启动服务

当前示例 Service 是 {{SERVICE}}：

    make run SERVICE={{SERVICE}}

如果配置启用了外部基础设施，先执行：

    make dev-up
    make run SERVICE={{SERVICE}}

默认 ops 端点通常在 http://127.0.0.1:9100；readyz 成功才表示服务可以接流量。
端口和依赖以 configs/service/config.{{SERVICE}}.yaml 为准。

## 5. 做第一个业务改动

如果不想记命令，只运行 make next，执行它显示的 next 行，完成后再次 make next。完整路线如下：

    roost add access player --service {{SERVICE}}
    roost add entity Player
    roost add component Profile --entity Player
    roost add dao Player --entity Player
    roost add handler RenamePlayer --entity Player --component Profile
    roost add protocol RenamePlayer --group game --handler player

先按 FIRST_BUSINESS.zh-CN.md 给 DAO、Component、handler 和 Request 添加业务字段，再执行：

    roost add endpoint RenamePlayer --handler player
    roost add lifecycle Player --service {{SERVICE}}
    make generate
    roost project doctor --workflow first-business

然后只编辑不带 Code generated 标识的定义或业务文件：

- protocol/def：消息结构；
- game/entities：Entity 定义与 Component 组合；
- db/def：DAO 定义；
- game/handler：Nest handler 业务逻辑；
- internal/service/{{SERVICE}}：服务接入和业务生命周期。

生成器负责注册、访问器、Sender、装配和重复样板；它不会替你决定业务字段、权限和玩法规则。
完整可复制例子见 FIRST_BUSINESS.zh-CN.md 和 ENTITY_COMPONENT.zh-CN.md。
add access 会启用 Nest 及其持久化依赖；第一次实际启动前运行 make dev-up。

要接真实 TCP 客户端，再执行 roost add transport tcp。该命令生成有界帧、连接限制、超时、背压和
优雅关停；鉴权文件默认拒绝所有连接。配置会自动以 disabled 状态加入 Service，不用复制 YAML；按
PLAYER_ACCESS_TCP.zh-CN.md 实现票据校验后运行 roost config enable player-tcp 才能启用 listener。

## 6. 修改 roost.yaml 后

    make sync
    make generate
    make doctor
    make ci

字段含义和完整例子见 ROOST_YAML.zh-CN.md。先运行 project diff 可以预览模板变化；
升级 codegen 管理的模板使用 make project-upgrade。

## 7. 常见问题

- roost 找不到：确认 go env GOBIN；为空时使用 go env GOPATH 下的 bin，并把它加入 PATH。
- make 找不到：安装 GNU Make，或从 Makefile 中复制对应的 roost/go 命令执行。
- go get 超时：检查 GOPROXY、公司代理和 GitHub 访问，不要把 replace 指向个人绝对路径提交。
- 配置包含 CHANGE_ME：这是生产 fail-closed 模板，必须换成真实 secret；本地开发使用非 prod 配置。
- sync 拒绝覆盖文件：该路径存在非生成文件；先备份并确认所有权，不要直接加生成标识骗过检查。
- generate 后 git 有变化：正常；生成物应与定义一起提交，并由 make check-generated 在 CI 校验。

## 8. 下一步阅读

1. BEGINNER_WORKBOOK.zh-CN.md：只看当前一步的完整小白操作手册；
2. ROOST_YAML.zh-CN.md：每个项目字段；
3. FIRST_BUSINESS.zh-CN.md：从玩家协议到 Entity 的第一条完整链路；
4. ENTITY_COMPONENT.zh-CN.md：业务代码、持久化状态和 Nest 锁边界；
5. PROTOCOL_TO_NEST.zh-CN.md：网络适配、协议、Sender 和错误边界；
6. PLAYER_ACCESS_TCP.zh-CN.md：可运行 TCP listener、帧、鉴权和上线检查；
7. SKILL.zh-CN.md：稳定 roost-skill 接入；
8. USAGE.zh-CN.md：当前项目启用的 Service、Mod 和命令；
9. IMPLEMENTATION.zh-CN.md：Entity、Nest、WAL、Remote Entity、Saga 和同步实现；
10. DEPLOYMENT.zh-CN.md：Shell、Docker、Kubernetes 生产部署。
`
	return strings.NewReplacer("{{NAME}}", m.Project.Name, "{{SERVICE}}", service).Replace(guide)
}

func renderEntityComponentGuide(manifest Manifest) string {
	const guide = `<!-- Code generated by roost-codegen. DO NOT EDIT. -->
# Entity、Component 与 DAO 零基础实战

这条路径不要求手写工厂、组件注册、Manager、字段 tag 或 getter。生成器负责接线，业务只写
Component 方法和 Nest handler。

## 1. 创建一个完整聚合

在项目根目录执行：

    roost add entity Player
    roost add component Profile --entity Player
    roost add dao Player --entity Player
    roost add mod nest -service {{SERVICE}}
    roost add handler RenamePlayer --entity Player --component Profile
    make generate
    make doctor

如果项目只有一个 Entity，Component 的 --entity 可以省略；有多个 Entity 时必须明确指定，
生成器会拒绝猜测。DAO 只有写了 --entity 才会自动挂载；不写表示创建独立 DAO 定义。

生成结果：

| 文件 | 所有权 | 应该做什么 |
| --- | --- | --- |
| game/entities/player/entity.go | 业务 | Entity 聚合、Component/DAO 字段与接口；不要删除生成器添加的 tag |
| game/entities/player/profile_component.go | 业务 | 在文件末尾添加玩法方法 |
| db/def/player.go | 业务 | 声明持久化/同步字段，不写 ID、id、tracker |
| db/gen_player_dao.go | 生成器 | 使用 GetName()/SetName() 等方法访问；禁止直接访问存储字段 |
| game/entities/player/player_gen_wire.go | 生成器 | 工厂、装配、getter、Snapshot；禁止手改 |

## 2. 写 Component 逻辑

先在 db/def/player.go 定义字段并运行 make generate：

    type Player struct {
        Name  string ` + "`bson:\"name\" dao:\"persist,sync\"`" + `
        Level int32  ` + "`bson:\"level\" dao:\"persist,sync\"`" + `
    }

然后在 profile_component.go 末尾写业务方法：

    func (component *ProfileComponent) Rename(name string) error {
        if name == "" {
            return fmt.Errorf("invalid name %q", name)
        }
        component.Owner().Dao().SetName(name)
        return nil
    }

必须使用 DAO 生成的 SetXxx/UpdateXxx/RemoveXxx 方法，不能直接写字段。生成方法会同时维护
dirty mask、回滚、持久化 patch 和同步标记。

## 3. 从 Nest handler 调用

Nest 同时需要 roost.yaml 的 nest feature（生成 Sender/handler）和目标 Service 的 nest mod
（装配 WAL、checkpoint、NATS、MongoDB、Redis 等运行依赖）。缺少运行时 mod 时 add handler 会直接报错，
不会生成一个只能编译、不能正确运行的半成品。先执行：

    roost add mod nest -service {{SERVICE}}
    roost add handler RenamePlayer --entity Player --component Profile

然后编辑生成的 game/handler/rename_player.go：

    package handler

    import player "{{MODULE}}/game/entities/player"

    //roost:nest rollback=undo durability=strict
    func handlerRenamePlayer(target player.IProfileEntity, name string) error {
        return target.ProfileComp().Rename(name)
    }

运行 make generate 后，Nest 会生成 Sender、按全局顺序取得 Entity 锁、执行 handler，
并按声明完成回滚和 durability。业务层不要再次给
Entity 或 Component 加 mutex，也不要绕过 Sender 直接并发调用 handler。

选择 rollback/durability：

| 场景 | 推荐标记 |
| --- | --- |
| 只读查询 | 默认，或 durability=memory |
| 单 Entity 普通写入 | rollback=undo durability=async |
| 交易、付费、跨实体关键写入 | rollback=undo durability=strict |
| 依赖完整状态快照回滚 | rollback=state；先确认 Entity 支持 snapshot |

不确定时先使用 strict；压测和故障演练后再放宽，不要为了吞吐直接关闭 durability。

## 4. 哪些数据放在哪里

- Entity：身份、生命周期和聚合边界，不堆放可变业务字段。
- Component：玩法行为和对 Entity/DAO 的编排；普通字段默认只在内存中，重启后不会恢复。
- DAO：需要 save/load、rollback 或 sync 的状态，必须声明 persist/sync 意图。
- Config：策划静态数据，放 configs/schema 与 configs/table，不写进 Entity。
- Remote Entity：只有跨服所有权场景才启用；普通房间内 Entity 不要默认使用。

## 5. 每次修改后的固定检查

    make generate
    make doctor
    make test
    make test-race

提交前再执行 make ci。以下错误不要绕过：

- no component factory：Component 没有通过 roost add component --entity 创建或注册被删除；
- multiple Entities exist：补上 --entity；
- generated files are stale：重新 make generate 并提交生成物；
- reserved field id/tracker：删除 DAO 中的保留字段，身份和 tracker 由生成器管理；
- repeats shared mod / unknown feature：按 ROOST_YAML.zh-CN.md 修正清单，不手改生成代码。
`
	service := sortedServiceNames(manifest)[0]
	return strings.NewReplacer("{{MODULE}}", manifest.Project.Module, "{{SERVICE}}", service).Replace(guide)
}

func renderManifestGuide() string {
	return fmt.Sprintf(`<!-- Code generated by roost-codegen. DO NOT EDIT. -->
# roost.yaml 字段参考与示例

roost.yaml 是项目结构的唯一声明源。修改后运行 make sync；需要更新生成代码时再运行
make generate。未知字段会直接报错，避免拼写错误被静默忽略。

## 1. 完整示例

    schema: 1
    project:
      name: planet
      module: github.com/acme/planet
    versions:
      core: latest
      kit: latest
      skill: latest
      codegen: latest
    shared_mods:
      - lock
      - ops
      - statslog
    services:
      game:
        mods:
          - configdata
          - etcd
          - redis
          - mongo
          - nats
          - sync
          - remote_entity
          - checkpoint
          - nestwal
          - nest
      gate:
        mods:
          - etcd
    access:
      player:
        service: game
        transports:
          - tcp
    features:
      - protocol
      - config
      - entity
      - nest
      - event
      - dao
      - errcode
      - replication-quic
    sagas:
      - alliance_rally
    ids:
      protocol:
        groups:
          game:
            min: 10000
            max: 19999
      entity:
        min: 1
        max: 255
      component:
        min: 2000
        max: 2999
      errcode:
        min: 100000
        max: 199999

## 2. 顶层字段

| 字段 | 必填 | 含义 | 修改后的影响 |
| --- | --- | --- | --- |
| schema | 是 | 清单格式版本，当前只能为 1 | 其他值拒绝加载 |
| project | 是 | 项目身份和 Go module | 影响 import、应用名和生成路径 |
| versions | 是 | core、kit、skill、codegen 更新策略 | deps、sync、CI 和 Makefile 使用 |
| shared_mods | 否 | 每个进程只装配一次的共享 Mod | 进入 App 根容器，不得在 Service 重复 |
| services | 是 | 可启动 Service 及各自 Mod；至少一个 | 生成启动入口、配置和 bootstrap |
| access | 否 | 已认证请求边界、所属 Service 与显式 transport | 生成 player runtime、binding、listener 与装配 |
| features | 否 | 项目级代码生成能力开关 | 决定目录、生成器和 bootstrap 接线 |
| sagas | 否 | 已生成 Saga 定义名称 | bootstrap 聚合并注册 Definitions |
| ids | 否 | protocol/entity/component/errcode 编号空间 | add、id next 和 id check 使用 |

## 3. project

| 字段 | 规则 | 示例 |
| --- | --- | --- |
| project.name | 小写字母开头，只能包含小写字母、数字、下划线 | planet_server |
| project.module | 合法 Go module import path；拒绝控制字符、路径回退、反斜杠、冒号和空 segment | github.com/acme/planet |

name 是运行与部署身份；module 是 Go import 前缀。仓库目录名可以不同，但初学项目建议三者一致。
修改 module 属于全仓 import 迁移，不应只改 roost.yaml。

## 4. versions

| 字段 | 控制对象 | 当前兼容下限 | 值示例 |
| --- | --- | --- | --- |
| versions.core | cube-core 依赖解析 | %s | latest 或 %s |
| versions.kit | cube-kit 依赖解析 | %s | latest 或 %s |
| versions.skill | roost-skill 依赖解析 | %s | latest 或 %s |
| versions.codegen | Makefile 使用的 roost-codegen | %s | latest 或 %s |

latest 是持续更新策略，不会原样写进 go.mod。project deps 会在同级临时项目联合解析 core、kit、skill，
只把本次选中的具体版本写入 go.mod/go.sum；失败或并发变化不覆盖原文件，这样一次测试和发布仍然
可复现。明确版本是 Go MVS 下限，不是禁止更高传递版本的上限。

## 5. shared_mods 与 services

shared_mods 适合 lock、ops、statslog 等进程级能力。services 是名称到配置的 map：

    shared_mods: [lock, ops, statslog]
    services:
      game:
        mods: [configdata, etcd, mongo, nest]
      chat:
        mods: [etcd, redis, nats]

services.<name>.mods 表示该 Service 运行时装配的 Kit Mod。生成器会自动展开依赖并按
DependsOn 拓扑排序；例如 nest 会补 nestwal、checkpoint、mongo、redis、nats。
同一个 Mod 不能同时出现在 shared_mods 和某个 Service 中，未知 Mod 和依赖环会失败。

access.player.service 指定玩家协议接入层安装到哪个 Service。当前仅支持 player；它要求 protocol
feature，并要求目标 Service 有 nest Mod。access.player.transports 是显式启用的客户端传输列表；当前
支持 tcp。推荐依次使用 roost add access player --service game 与 roost add transport tcp，避免漏掉
受控文件、依赖和生产边界。Access 提供 transport-neutral Dispatch/Encode；TCP 生成层负责 listener、
有界帧、连接上限、超时、sequence、背压和关停，应用只实现生成后不会覆盖的 auth.go。

当前可用 Mod：

| Mod | 主要用途 | 自动依赖 |
| --- | --- | --- |
| lock | 进程内锁服务 | 无 |
| ops | 健康检查与运维端点 | 无 |
| statslog | 周期统计日志 | 无 |
| configdata | 本地配置数据加载 | 无 |
| etcd | 服务发现与分布式配置 | 无 |
| redis | Redis 访问 | 无 |
| mongo | MongoDB 访问 | 无 |
| nats | NATS 消息传输 | 无 |
| sync | Entity/状态同步 | nats |
| remote_entity | 跨服 Remote Entity | redis、mongo、sync |
| checkpoint | Entity 持久化检查点与 WAL | mongo、redis |
| nestwal | Nest 可靠执行与 effect outbox | checkpoint、nats |
| nest | Nest 调度接入 | nestwal |
| saga | 跨服务 Saga 编排 | nestwal |

## 6. features

features 只控制生成期形态，不会自动启动同名基础设施：

| Feature | 生成内容或作用 | 默认启用 |
| --- | --- | --- |
| protocol | 协议、消息 ID、绑定与 handler 骨架 | 是 |
| config | 配置 schema 与强类型配置 | 是 |
| entity | Entity/Component 声明与访问器 | 是 |
| nest | Nest Sender、handler 和注册代码 | 是 |
| event | 事件定义、分发和 handler 接线 | 是 |
| dao | DAO 定义与方法式字段访问代码 | 是 |
| errcode | 错误码检查与文档导出 | 是 |
| attribute | 属性定义与访问代码 | 否 |
| webroute | HTTP route 扫描和注册代码 | 否 |
| saga | Saga definition 的生成与注册 | 否；由 roost add saga 维护 |
| replication-udp | 房间帧同步 UDP 接线 | 否 |
| replication-kcp | 房间帧同步 KCP 接线 | 否 |
| replication-quic | 房间帧同步 QUIC 接线 | 否 |

例如启用 UDP 与 QUIC：

    features:
      - protocol
      - entity
      - replication-udp
      - replication-quic

Feature 和 Mod 必须分别理解：config feature 生成配置代码，configdata mod 在运行时加载配置；
nest feature 生成 handler/注册代码，nest mod 装配运行引擎。

## 7. sagas

sagas 是 roost add saga 生成过的定义名称列表：

    sagas:
      - alliance_rally
      - cross_server_trade

不要只手工添加名字；使用 roost add saga，让定义文件、Service 的 saga mod、依赖和 bootstrap
一起更新。删除前确认没有运行中的旧 definition version。

## 8. ids

普通编号空间使用 min/max 闭区间：

    ids:
      entity: {min: 1, max: 255}

Protocol 可以按业务 group 分段：

    ids:
      protocol:
        groups:
          game: {min: 10000, max: 19999}
          chat: {min: 20000, max: 20999}

min 必须大于 0，max 必须不小于 min。EntityKind 编码为 uint8，范围不能超过 255；
ComponentType 不能超过 65535；Protocol 消息 ID 不能超过 4294967295。范围应互不重叠并预留增长空间。分配和检查：

    roost id next protocol -group game
    roost id next entity
    roost id check

## 9. 常用修改流程

    roost project diff
    make sync
    make generate
    make doctor
    make ci

project diff 只预览受控模板；sync 不覆盖业务拥有的 Service 实现和配置。升级整个模板使用
make project-upgrade，更新框架依赖使用 make deps-update，更新完整项目依赖图使用 make roost-up。

## 10. 常见错误

- cannot unmarshal / field not found：字段拼写错误或当前 schema 不支持；不要忽略。
- repeats shared mod：把该 Mod 只保留在 shared_mods 或 Service 一处。
- unknown feature/mod：查看 roost help mods 和项目生成器文档的合法清单。
- version below minimum：改用 latest，或升级到不低于错误信息给出的版本。
- invalid range / duplicate ID：修正 ids 范围或冲突定义后再生成。
- saga requires saga mod：使用 roost add saga，不要只手改 sagas/features。
`, minimumVersions.Core, minimumVersions.Core,
		minimumVersions.Kit, minimumVersions.Kit,
		minimumVersions.Skill, minimumVersions.Skill,
		minimumVersions.Codegen, minimumVersions.Codegen)
}
