package roost

import (
	"fmt"
	"strings"
)

func renderBeginnerQuickstart(m Manifest) string {
	service := sortedServiceNames(m)[0]
	const guide = `<!-- Code generated by roost-codegen. DO NOT EDIT. -->
# {{NAME}} 零基础快速开始

这份教程假设你只会运行基本命令。先照着完成一次，再阅读完整功能说明。

## 1. 准备环境

必须安装：

- Go 1.25 或项目 go.mod 指定的更高兼容版本；
- Git；
- GNU Make；
- 能访问 Go module proxy 或 GitHub。

只有使用 Redis、MongoDB、NATS、etcd 等 Mod 时才需要 Docker。执行以下命令确认环境：

    go version
    git --version
    make --version
    roost help

## 2. 先理解四个词

| 名称 | 它是什么 | 初学时在哪里修改 |
| --- | --- | --- |
| Service | 一个可独立启动的游戏服务进程，例如 game、gate | internal/service/<name> |
| Mod | Service 启动时装配的基础设施能力，例如 etcd、mongo、nest | roost.yaml 的 services.<name>.mods |
| Feature | 决定生成哪些代码和目录的开关，例如 protocol、entity、dao | roost.yaml 的 features |
| Generated file | codegen 管理、带 DO NOT EDIT 标识的文件 | 不手改；修改声明后运行 make sync/generate |

Mod 是运行时能力，Feature 是生成期能力，它们不是同一组选项。

## 3. 第一次生成和检查

项目已经创建时，在项目根目录执行：

    make deps-update
    make generate
    make doctor
    make test

这些命令分别更新框架依赖、生成代码、检查工程和运行测试。失败时先读错误信息中的文件名，
不要删除生成标识或手工修改 generated.go 绕过错误。

## 4. 启动服务

当前示例 Service 是 {{SERVICE}}：

    make run SERVICE={{SERVICE}}

如果配置启用了外部基础设施，先执行：

    make dev-up
    make run SERVICE={{SERVICE}}

默认 ops 端点通常在 http://127.0.0.1:9100；readyz 成功才表示服务可以接流量。
端口和依赖以 configs/service/config.{{SERVICE}}.yaml 为准。

## 5. 做第一个业务改动

    roost add protocol PlayerLogin -group game
    roost add entity Player
    roost add dao Player
    make generate

然后只编辑不带 Code generated 标识的定义或业务文件：

- protocol/def：消息结构；
- game/entities：Entity 定义与 Component 组合；
- db/def：DAO 定义；
- game/handler：Nest handler 业务逻辑；
- internal/service/{{SERVICE}}：服务接入和业务生命周期。

生成器负责注册、访问器、Sender、装配和重复样板；它不会替你决定业务字段、权限和玩法规则。

## 6. 修改 roost.yaml 后

    make sync
    make generate
    make doctor
    make ci

字段含义和完整例子见 ROOST_YAML.zh-CN.md。先运行 project diff 可以预览模板变化；
升级 codegen 管理的模板使用 make project-upgrade。

## 7. 常见问题

- roost 找不到：确认 go env GOBIN；为空时使用 go env GOPATH 下的 bin，并把它加入 PATH。
- make 找不到：安装 GNU Make，或从 Makefile 中复制对应的 roost/go 命令执行。
- go get 超时：检查 GOPROXY、公司代理和 GitHub 访问，不要把 replace 指向个人绝对路径提交。
- 配置包含 CHANGE_ME：这是生产 fail-closed 模板，必须换成真实 secret；本地开发使用非 prod 配置。
- sync 拒绝覆盖文件：该路径存在非生成文件；先备份并确认所有权，不要直接加生成标识骗过检查。
- generate 后 git 有变化：正常；生成物应与定义一起提交，并由 make check-generated 在 CI 校验。

## 8. 下一步阅读

1. ROOST_YAML.zh-CN.md：每个项目字段；
2. USAGE.zh-CN.md：当前项目启用的 Service、Mod 和命令；
3. IMPLEMENTATION.zh-CN.md：Entity、Nest、WAL、Remote Entity、Saga 和同步实现；
4. DEPLOYMENT.zh-CN.md：Shell、Docker、Kubernetes 生产部署。
`
	return strings.NewReplacer("{{NAME}}", m.Project.Name, "{{SERVICE}}", service).Replace(guide)
}

func renderManifestGuide() string {
	return fmt.Sprintf(`<!-- Code generated by roost-codegen. DO NOT EDIT. -->
# roost.yaml 字段参考与示例

roost.yaml 是项目结构的唯一声明源。修改后运行 make sync；需要更新生成代码时再运行
make generate。未知字段会直接报错，避免拼写错误被静默忽略。

## 1. 完整示例

    schema: 1
    project:
      name: planet
      module: github.com/acme/planet
    versions:
      core: latest
      kit: latest
      skill: latest
      codegen: latest
    shared_mods:
      - lock
      - ops
      - statslog
    services:
      game:
        mods:
          - configdata
          - etcd
          - redis
          - mongo
          - nats
          - sync
          - remote_entity
          - checkpoint
          - nestwal
          - nest
      gate:
        mods:
          - etcd
    features:
      - protocol
      - config
      - entity
      - nest
      - event
      - dao
      - errcode
      - replication-quic
    sagas:
      - alliance_rally
    ids:
      protocol:
        groups:
          game:
            min: 10000
            max: 19999
      entity:
        min: 1000
        max: 1999
      component:
        min: 2000
        max: 2999
      errcode:
        min: 100000
        max: 199999

## 2. 顶层字段

| 字段 | 必填 | 含义 | 修改后的影响 |
| --- | --- | --- | --- |
| schema | 是 | 清单格式版本，当前只能为 1 | 其他值拒绝加载 |
| project | 是 | 项目身份和 Go module | 影响 import、应用名和生成路径 |
| versions | 是 | core、kit、skill、codegen 更新策略 | deps、sync、CI 和 Makefile 使用 |
| shared_mods | 否 | 每个进程只装配一次的共享 Mod | 进入 App 根容器，不得在 Service 重复 |
| services | 是 | 可启动 Service 及各自 Mod；至少一个 | 生成启动入口、配置和 bootstrap |
| features | 否 | 项目级代码生成能力开关 | 决定目录、生成器和 bootstrap 接线 |
| sagas | 否 | 已生成 Saga 定义名称 | bootstrap 聚合并注册 Definitions |
| ids | 否 | protocol/entity/component/errcode 编号空间 | add、id next 和 id check 使用 |

## 3. project

| 字段 | 规则 | 示例 |
| --- | --- | --- |
| project.name | 小写字母开头，只能包含小写字母、数字、下划线 | planet_server |
| project.module | 非空，不能包含空格、反斜杠或冒号；应使用合法 Go module import path | github.com/acme/planet |

name 是运行与部署身份；module 是 Go import 前缀。仓库目录名可以不同，但初学项目建议三者一致。
修改 module 属于全仓 import 迁移，不应只改 roost.yaml。

## 4. versions

| 字段 | 控制对象 | 当前兼容下限 | 值示例 |
| --- | --- | --- | --- |
| versions.core | cube-core 依赖解析 | %s | latest 或 %s |
| versions.kit | cube-kit 依赖解析 | %s | latest 或 %s |
| versions.skill | roost-skill 依赖解析 | %s | latest 或 %s |
| versions.codegen | Makefile 使用的 roost-codegen | %s | latest 或 %s |

latest 是持续更新策略，不会原样写进 go.mod。project deps 会联合解析 core、kit、skill，
把本次选中的具体版本写入 go.mod/go.sum；这样一次测试和发布仍然可复现。明确版本是 Go MVS
下限，不是禁止更高传递版本的上限。

## 5. shared_mods 与 services

shared_mods 适合 lock、ops、statslog 等进程级能力。services 是名称到配置的 map：

    shared_mods: [lock, ops, statslog]
    services:
      game:
        mods: [configdata, etcd, mongo, nest]
      chat:
        mods: [etcd, redis, nats]

services.<name>.mods 表示该 Service 运行时装配的 Kit Mod。生成器会自动展开依赖并按
DependsOn 拓扑排序；例如 nest 会补 nestwal、checkpoint、mongo、redis、nats。
同一个 Mod 不能同时出现在 shared_mods 和某个 Service 中，未知 Mod 和依赖环会失败。

当前可用 Mod：

| Mod | 主要用途 | 自动依赖 |
| --- | --- | --- |
| lock | 进程内锁服务 | 无 |
| ops | 健康检查与运维端点 | 无 |
| statslog | 周期统计日志 | 无 |
| configdata | 本地配置数据加载 | 无 |
| etcd | 服务发现与分布式配置 | 无 |
| redis | Redis 访问 | 无 |
| mongo | MongoDB 访问 | 无 |
| nats | NATS 消息传输 | 无 |
| sync | Entity/状态同步 | nats |
| remote_entity | 跨服 Remote Entity | redis、mongo、sync |
| checkpoint | Entity 持久化检查点与 WAL | mongo、redis |
| nestwal | Nest 可靠执行与 effect outbox | checkpoint、nats |
| nest | Nest 调度接入 | nestwal |
| saga | 跨服务 Saga 编排 | nestwal |

## 6. features

features 只控制生成期形态，不会自动启动同名基础设施：

| Feature | 生成内容或作用 | 默认启用 |
| --- | --- | --- |
| protocol | 协议、消息 ID、绑定与 handler 骨架 | 是 |
| config | 配置 schema 与强类型配置 | 是 |
| entity | Entity/Component 声明与访问器 | 是 |
| nest | Nest Sender、handler 和注册代码 | 是 |
| event | 事件定义、分发和 handler 接线 | 是 |
| dao | DAO 定义与方法式字段访问代码 | 是 |
| errcode | 错误码检查与文档导出 | 是 |
| attribute | 属性定义与访问代码 | 否 |
| webroute | HTTP route 扫描和注册代码 | 否 |
| saga | Saga definition 的生成与注册 | 否；由 roost add saga 维护 |
| replication-udp | 房间帧同步 UDP 接线 | 否 |
| replication-kcp | 房间帧同步 KCP 接线 | 否 |
| replication-quic | 房间帧同步 QUIC 接线 | 否 |

例如启用 UDP 与 QUIC：

    features:
      - protocol
      - entity
      - replication-udp
      - replication-quic

Feature 和 Mod 必须分别理解：config feature 生成配置代码，configdata mod 在运行时加载配置；
nest feature 生成 handler/注册代码，nest mod 装配运行引擎。

## 7. sagas

sagas 是 roost add saga 生成过的定义名称列表：

    sagas:
      - alliance_rally
      - cross_server_trade

不要只手工添加名字；使用 roost add saga，让定义文件、Service 的 saga mod、依赖和 bootstrap
一起更新。删除前确认没有运行中的旧 definition version。

## 8. ids

普通编号空间使用 min/max 闭区间：

    ids:
      entity: {min: 1000, max: 1999}

Protocol 可以按业务 group 分段：

    ids:
      protocol:
        groups:
          game: {min: 10000, max: 19999}
          chat: {min: 20000, max: 20999}

min 必须大于 0，max 必须不小于 min。范围应互不重叠并预留增长空间。分配和检查：

    roost id next protocol -group game
    roost id next entity
    roost id check

## 9. 常用修改流程

    roost project diff
    make sync
    make generate
    make doctor
    make ci

project diff 只预览受控模板；sync 不覆盖业务拥有的 Service 实现和配置。升级整个模板使用
make project-upgrade，更新框架依赖使用 make deps-update，更新完整项目依赖图使用 make roost-up。

## 10. 常见错误

- cannot unmarshal / field not found：字段拼写错误或当前 schema 不支持；不要忽略。
- repeats shared mod：把该 Mod 只保留在 shared_mods 或 Service 一处。
- unknown feature/mod：查看 roost help mods 和项目生成器文档的合法清单。
- version below minimum：改用 latest，或升级到不低于错误信息给出的版本。
- invalid range / duplicate ID：修正 ids 范围或冲突定义后再生成。
- saga requires saga mod：使用 roost add saga，不要只手改 sagas/features。
`, minimumVersions.Core, minimumVersions.Core,
		minimumVersions.Kit, minimumVersions.Kit,
		minimumVersions.Skill, minimumVersions.Skill,
		minimumVersions.Codegen, minimumVersions.Codegen)
}
