package roost

import (
	"bytes"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

func TestResolveModsAddsRequiredDependencies(t *testing.T) {
	got, err := resolveMods([]string{"remote_entity", "sync"})
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"redis", "nats", "remote_entity", "sync"} {
		if !contains(got, want) {
			t.Fatalf("resolved mods %v do not contain %s", got, want)
		}
	}
}

func TestNewProjectSyncPreservesBusinessFiles(t *testing.T) {
	target := filepath.Join(t.TempDir(), "planet")
	result, root, err := NewProject(NewOptions{
		Name:     "planet",
		Module:   "example.com/planet",
		Out:      target,
		Services: []string{"game", "gate"},
		Mods:     []string{"configdata", "sync", "remote_entity"},
		Features: []string{"config", "nest"},
	})
	if err != nil {
		t.Fatalf("new project: %v", err)
	}
	if len(result.Created) == 0 || root != target {
		t.Fatalf("unexpected result: %#v root=%s", result, root)
	}
	for _, rel := range []string{
		"roost.yaml",
		"Makefile",
		"docs/QUICKSTART.zh-CN.md",
		"docs/ROOST_YAML.zh-CN.md",
		"internal/bootstrap/generated.go",
		"internal/service/game/service.go",
		"configs/generated/gen_table_config.go",
		"game/bootstrap/nest.go",
	} {
		if _, err := os.Stat(filepath.Join(root, filepath.FromSlash(rel))); err != nil {
			t.Fatalf("%s missing: %v", rel, err)
		}
	}

	servicePath := filepath.Join(root, "internal", "service", "game", "service.go")
	raw, err := os.ReadFile(servicePath)
	if err != nil {
		t.Fatal(err)
	}
	raw = append(raw, []byte("\n// business-owned\n")...)
	if err := os.WriteFile(servicePath, raw, 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := SyncProject(root); err != nil {
		t.Fatalf("sync project: %v", err)
	}
	after, _ := os.ReadFile(servicePath)
	if !bytes.Contains(after, []byte("business-owned")) {
		t.Fatal("sync overwrote the business service file")
	}
}

func TestAddProtocolAllocatesIDAndCheckDetectsDuplicate(t *testing.T) {
	target := filepath.Join(t.TempDir(), "planet")
	_, root, err := NewProject(NewOptions{Name: "planet", Module: "example.com/planet", Out: target, Features: []string{"protocol"}})
	if err != nil {
		t.Fatal(err)
	}
	paths, err := Add(root, AddOptions{Kind: "protocol", Name: "PlayerLogin", Group: "game"})
	if err != nil {
		t.Fatal(err)
	}
	if len(paths) != 1 {
		t.Fatalf("paths = %v", paths)
	}
	raw, _ := os.ReadFile(filepath.Join(root, filepath.FromSlash(paths[0])))
	if !strings.Contains(string(raw), "id=10000") {
		t.Fatalf("protocol did not receive first ID:\n%s", raw)
	}
	m, _ := LoadManifest(root)
	if err := CheckIDs(root, m); err != nil {
		t.Fatalf("id check: %v", err)
	}
	duplicate := filepath.Join(root, "protocol", "def", "duplicate.go")
	if err := os.WriteFile(duplicate, []byte("package protocoldef\n//cube:msg id=10000\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := CheckIDs(root, m); err == nil {
		t.Fatal("expected duplicate ID failure")
	}
}

func TestLoadManifestRejectsUnknownFields(t *testing.T) {
	root := t.TempDir()
	raw := []byte("schema: 1\nproject:\n  name: planet\n  module: example.com/planet\nversions: {}\nservices:\n  game: {}\nunknown: true\n")
	if err := os.WriteFile(filepath.Join(root, ManifestName), raw, 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := LoadManifest(root); err == nil {
		t.Fatal("expected strict YAML decode error")
	}
}

func TestUpgradeCanReadVersionsBelowCurrentFloor(t *testing.T) {
	target := filepath.Join(t.TempDir(), "planet")
	_, root, err := NewProject(NewOptions{Name: "planet", Module: "example.com/planet", Out: target})
	if err != nil {
		t.Fatal(err)
	}
	manifestPath := filepath.Join(root, ManifestName)
	raw, err := os.ReadFile(manifestPath)
	if err != nil {
		t.Fatal(err)
	}
	for _, module := range []string{"core", "kit", "skill", "codegen"} {
		raw = bytes.Replace(raw, []byte("  "+module+": latest"), []byte("  "+module+": v1.0.0"), 1)
	}
	if err := os.WriteFile(manifestPath, raw, 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := LoadManifest(root); err == nil {
		t.Fatal("normal manifest load accepted unsupported legacy versions")
	}
	makefilePath := filepath.Join(root, "Makefile")
	legacyMakefile := []byte("# Code generated by roost-codegen. DO NOT EDIT.\n\n.PHONY: sync\nsync:\n\t$(ROOST) project sync\n")
	if err := os.WriteFile(makefilePath, legacyMakefile, 0o644); err != nil {
		t.Fatal(err)
	}
	var preview bytes.Buffer
	if err := Run([]string{"project", "upgrade", "--root", root, "--dry-run", "-core", "latest", "-kit", "latest", "-skill", "latest", "-codegen", "latest"}, &preview, io.Discard); err != nil {
		t.Fatalf("preview legacy upgrade: %v", err)
	}
	if !strings.Contains(preview.String(), "roost.yaml") || !strings.Contains(preview.String(), "Makefile") {
		t.Fatalf("upgrade preview did not report manifest and Makefile:\n%s", preview.String())
	}
	afterPreview, err := os.ReadFile(makefilePath)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(afterPreview, legacyMakefile) {
		t.Fatal("upgrade preview modified Makefile")
	}
	manifestAfterPreview, err := os.ReadFile(manifestPath)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(manifestAfterPreview, []byte("core: v1.0.0")) {
		t.Fatal("upgrade preview modified roost.yaml")
	}
	manifest, err := loadManifestForUpgrade(root)
	if err != nil {
		t.Fatalf("decode legacy manifest for upgrade: %v", err)
	}
	mergeVersions(&manifest.Versions, VersionSpec{Core: "latest", Kit: "latest", Skill: "latest", Codegen: "latest"})
	if err := saveManifest(root, manifest); err != nil {
		t.Fatalf("save upgraded manifest: %v", err)
	}
	if _, err := LoadManifest(root); err != nil {
		t.Fatalf("load upgraded manifest: %v", err)
	}
}

func TestProductionConfigRejectsDevelopmentValues(t *testing.T) {
	path := filepath.Join(t.TempDir(), "config.yaml")
	if err := os.WriteFile(path, []byte("sid: 1\nredis:\n  addr: 127.0.0.1:6379\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := CheckConfig(path, true); err == nil {
		t.Fatal("expected production config rejection")
	}
}

func TestAddCamelCaseProtocolUsesSnakeFileAndPascalTypes(t *testing.T) {
	target := filepath.Join(t.TempDir(), "planet")
	_, root, err := NewProject(NewOptions{Name: "planet", Module: "example.com/planet", Out: target, Features: []string{"protocol"}})
	if err != nil {
		t.Fatal(err)
	}
	paths, err := Add(root, AddOptions{Kind: "protocol", Name: "PlayerLogin", Group: "game"})
	if err != nil {
		t.Fatal(err)
	}
	if got, want := paths[0], "protocol/def/player_login.go"; got != want {
		t.Fatalf("path = %s, want %s", got, want)
	}
	raw, _ := os.ReadFile(filepath.Join(root, filepath.FromSlash(paths[0])))
	if !strings.Contains(string(raw), "type PlayerLoginRequest struct") {
		t.Fatalf("unexpected protocol:\n%s", raw)
	}
}

func TestAddSagaGeneratesValidatedDefinition(t *testing.T) {
	target := filepath.Join(t.TempDir(), "planet")
	_, root, err := NewProject(NewOptions{Name: "planet", Module: "example.com/planet", Out: target, Features: []string{"saga"}})
	if err != nil {
		t.Fatal(err)
	}
	paths, err := Add(root, AddOptions{Kind: "saga", Name: "AllianceRally", Steps: []string{"ReserveTroops", "CreateMarch"}})
	if err != nil {
		t.Fatal(err)
	}
	if got, want := paths[0], "saga/alliance_rally/definition.go"; got != want {
		t.Fatalf("path = %s, want %s", got, want)
	}
	raw, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(paths[0])))
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"= \"alliance_rally\"", "Version uint32 = 1", "DefinitionVersion: Version", "func Definitions() []saga.Definition", "reserve_troops.compensate", "func Register(engine *saga.Engine) error", "func EmitStart(", "saga.EmitStart", "engine.StartSaga", "func SubscribeReserveTroops(", "func SubscribeReserveTroopsCompensation("} {
		if !strings.Contains(string(raw), want) {
			t.Fatalf("generated Saga missing %q:\n%s", want, raw)
		}
	}
	bootstrap, err := os.ReadFile(filepath.Join(root, "internal", "bootstrap", "generated.go"))
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"var EntityAccess = entity.NewManagerAccess(EntityManager)", "kitsaga.NewMod(kitsaga.CombineDefinitions(sagaAllianceRally.Definitions())...)", "example.com/planet/saga/alliance_rally"} {
		if !strings.Contains(string(bootstrap), want) {
			t.Fatalf("bootstrap missing %q:\n%s", want, bootstrap)
		}
	}
	manifest, err := LoadManifest(root)
	if err != nil {
		t.Fatal(err)
	}
	if !contains(manifest.Services["game"].Mods, "saga") || !contains(manifest.Sagas, "alliance_rally") {
		t.Fatalf("Saga was not wired into manifest: %+v", manifest)
	}
}

func TestAddSagaRequiresSteps(t *testing.T) {
	target := filepath.Join(t.TempDir(), "planet")
	_, root, err := NewProject(NewOptions{Name: "planet", Module: "example.com/planet", Out: target, Features: []string{"saga"}})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := Add(root, AddOptions{Kind: "saga", Name: "AllianceRally"}); err == nil {
		t.Fatal("expected missing steps to fail")
	}
}

func TestFrameworkMinimumVersionGuard(t *testing.T) {
	m := DefaultManifest("planet", "example.com/planet", []string{"game"}, []string{"saga"}, []string{"saga"})
	m.Versions.Core = "v1.7.9"
	if err := m.Validate(); err == nil || !strings.Contains(err.Error(), "v1.8.0") {
		t.Fatalf("expected framework minimum version guard, got %v", err)
	}
	m.Versions.Core, m.Versions.Kit = minimumVersions.Core, minimumVersions.Kit
	if err := m.Validate(); err != nil {
		t.Fatalf("minimum supported versions rejected: %v", err)
	}
}

func TestReplicationPresetCompilesAsGoSource(t *testing.T) {
	m := DefaultManifest("planet", "example.com/planet", []string{"game"}, []string{"etcd"}, []string{"replication-quic", "replication-kcp", "replication-udp"})
	m.Versions.Kit = minimumVersions.Kit
	plan, err := renderProject(m)
	if err != nil {
		t.Fatal(err)
	}
	file, ok := plan["internal/transport/generated.go"]
	if !ok || !bytes.Contains(file.Body, []byte("func NewQUIC")) || !bytes.Contains(file.Body, []byte("func NewKCP")) || !bytes.Contains(file.Body, []byte("func NewUDP")) || !bytes.Contains(file.Body, []byte("func NewRoomSink")) {
		t.Fatalf("replication preset missing:\n%s", file.Body)
	}
}

func TestReplicationRequiresSupportedKitRelease(t *testing.T) {
	m := DefaultManifest("planet", "example.com/planet", []string{"game"}, []string{"etcd"}, []string{"replication-quic"})
	m.Versions.Kit = "v1.7.9"
	if err := m.Validate(); err == nil || !strings.Contains(err.Error(), minimumVersions.Kit) {
		t.Fatalf("expected kit release guard, got %v", err)
	}
	m.Versions.Kit = minimumVersions.Kit
	if err := m.Validate(); err != nil {
		t.Fatalf("minimum kit release rejected: %v", err)
	}
}

func TestProductionRenderingIncludesDurabilityAndTopologyGuards(t *testing.T) {
	m := DefaultManifest("planet", "example.com/planet", []string{"game"}, []string{"mongo", "redis", "nats", "checkpoint", "nestwal"}, []string{"config", "nest"})
	production := renderServiceConfig(m, "game", true)
	for _, want := range []string{
		"require_replica_set: true",
		"transaction_timeout: 30s",
		"transaction_receipt_ttl: 720h",
		"dir: /var/lib/roost/wal",
		"max_disk_bytes: 8589934592",
		"duplicate_window: 10m",
		"replicas: 3",
		"aof_replicas: 1",
		"addr: 0.0.0.0:9100",
	} {
		if !strings.Contains(production, want) {
			t.Errorf("production config missing %q:\n%s", want, production)
		}
	}
	if strings.Contains(production, "127.0.0.1") || strings.Contains(production, "file: true") {
		t.Fatalf("development topology leaked into production config:\n%s", production)
	}
	dockerfile := renderDockerfile(m)
	if !strings.Contains(dockerfile, `VOLUME ["/var/lib/roost/wal"]`) || !strings.Contains(dockerfile, "USER nonroot:nonroot") || !strings.Contains(dockerfile, "go mod download && go mod verify") {
		t.Fatalf("durable non-root Dockerfile missing:\n%s", dockerfile)
	}
	if strings.Contains(dockerfile, "COPY configs") {
		t.Fatalf("production image must not bake configuration or secrets:\n%s", dockerfile)
	}
	compose := renderCompose(m)
	if !strings.Contains(compose, `"--appendfsync", "everysec"`) {
		t.Fatalf("Redis AOF configuration missing from compose:\n%s", compose)
	}
	if !strings.Contains(compose, `"-sd", "/data"`) || !strings.Contains(compose, "mongo-data:/data/db") {
		t.Fatalf("development dependencies are not durable:\n%s", compose)
	}
	if m.Versions.Core != "latest" || m.Versions.Kit != "latest" || m.Versions.Skill != "latest" || m.Versions.Codegen != "latest" {
		t.Fatalf("latest version policy defaults = %+v", m.Versions)
	}
}

func TestProductionDeploymentRendering(t *testing.T) {
	m := DefaultManifest(
		"planet",
		"example.com/planet",
		[]string{"game", "gate"},
		[]string{"mongo", "redis", "nats", "checkpoint", "nestwal"},
		[]string{"config", "nest"},
	)
	// Exercise both workload classes: the gate is intentionally stateless.
	m.Services["gate"] = ServiceSpec{Mods: []string{"etcd", "ops"}}

	plan, err := renderProject(m)
	if err != nil {
		t.Fatal(err)
	}
	for _, path := range []string{
		"deploy/shell/build.sh",
		"deploy/shell/install.sh",
		"deploy/shell/healthcheck.sh",
		"deploy/docker/README.md",
		"deploy/k8s/kustomization.yaml",
		"deploy/k8s/network-policy.yaml",
		"deploy/k8s/game.yaml",
		"deploy/k8s/gate.yaml",
		"deploy/k8s/secret.game.example.yaml",
		"docs/IMPLEMENTATION.zh-CN.md",
		"docs/DEPLOYMENT.zh-CN.md",
	} {
		if _, ok := plan[path]; !ok {
			t.Errorf("deployment plan missing %s", path)
		}
	}

	game := string(plan["deploy/k8s/game.yaml"].Body)
	for _, want := range []string{"kind: StatefulSet", "volumeClaimTemplates:", "readOnlyRootFilesystem: true", "startupProbe:", "readinessProbe:", "livenessProbe:"} {
		if !strings.Contains(game, want) {
			t.Errorf("stateful workload missing %q:\n%s", want, game)
		}
	}
	gate := string(plan["deploy/k8s/gate.yaml"].Body)
	if !strings.Contains(gate, "kind: Deployment") || strings.Contains(gate, "volumeClaimTemplates:") {
		t.Fatalf("stateless workload rendered incorrectly:\n%s", gate)
	}
	secret := string(plan["deploy/k8s/secret.game.example.yaml"].Body)
	if !strings.Contains(secret, "CHANGE_ME") || !strings.Contains(secret, "addr: 0.0.0.0:9100") {
		t.Fatalf("secret example is not fail-closed or probe-ready:\n%s", secret)
	}
	kustomization := string(plan["deploy/k8s/kustomization.yaml"].Body)
	if strings.Contains(kustomization, "secret.") {
		t.Fatalf("secret examples must not be applied by kustomize:\n%s", kustomization)
	}

	for path, file := range plan {
		if strings.HasPrefix(path, "deploy/k8s/") && strings.HasSuffix(path, ".yaml") {
			assertYAMLDocuments(t, path, file.Body)
		}
	}
	installer := string(plan["deploy/shell/install.sh"].Body)
	for _, want := range []string{"releases/$VERSION", "switch_release", "wait_ready", "rolling back", "ProtectKernelTunables=true"} {
		if !strings.Contains(installer, want) {
			t.Errorf("systemd deployer missing %q:\n%s", want, installer)
		}
	}
}

func assertYAMLDocuments(t *testing.T, path string, body []byte) {
	t.Helper()
	decoder := yaml.NewDecoder(bytes.NewReader(body))
	for document := 1; ; document++ {
		var value any
		err := decoder.Decode(&value)
		if err == io.EOF {
			return
		}
		if err != nil {
			t.Fatalf("decode %s document %d: %v\n%s", path, document, err, body)
		}
	}
}

func TestBootstrapImportsTransitiveModDependencies(t *testing.T) {
	m := DefaultManifest("planet", "example.com/planet", []string{"game"}, []string{"nestwal"}, []string{"nest"})
	bootstrap := renderBootstrap(m)
	for _, want := range []string{
		`kitcheckpoint "github.com/tjbdwanghaibo/cube-kit/checkpoint"`,
		`kitmongo "github.com/tjbdwanghaibo/cube-kit/mongo"`,
		`kitredis "github.com/tjbdwanghaibo/cube-kit/redis"`,
		`kitnats "github.com/tjbdwanghaibo/cube-kit/nats"`,
		"kitcheckpoint.NewMod(",
	} {
		if !strings.Contains(bootstrap, want) {
			t.Errorf("bootstrap missing transitive dependency %q:\n%s", want, bootstrap)
		}
	}
}

func TestRenderGoModUsesPublishedModulesWithoutReplace(t *testing.T) {
	m := DefaultManifest("planet", "example.com/planet", nil, nil, nil)
	goMod := renderGoMod(m)
	for _, want := range []string{
		"github.com/tjbdwanghaibo/cube-core " + minimumVersions.Core,
		"github.com/tjbdwanghaibo/cube-kit " + minimumVersions.Kit,
		"github.com/tjbdwanghaibo/roost-skill " + minimumVersions.Skill,
	} {
		if !strings.Contains(goMod, want) {
			t.Errorf("go.mod missing %q:\n%s", want, goMod)
		}
	}
	if strings.Contains(goMod, "replace ") {
		t.Fatalf("generated release go.mod contains replace directive:\n%s", goMod)
	}
	if strings.Contains(goMod, "cube-core latest") || strings.Contains(goMod, "cube-kit latest") || strings.Contains(goMod, "roost-skill latest") {
		t.Fatalf("go.mod must contain resolved semantic versions, not module queries:\n%s", goMod)
	}
	plan, err := renderProject(m)
	if err != nil {
		t.Fatal(err)
	}
	deps, ok := plan["internal/frameworkdeps/generated.go"]
	if !ok || !strings.Contains(string(deps.Body), "github.com/tjbdwanghaibo/roost-skill/skill") || strings.Contains(string(deps.Body), "/skillv2") {
		t.Fatalf("generated project does not pin the skill module: %q", deps.Body)
	}
	makefile := string(plan["Makefile"].Body)
	if !strings.Contains(makefile, "deps-update:") || !strings.Contains(makefile, "$(ROOST) project deps") {
		t.Fatalf("generated Makefile does not expose latest dependency resolution:\n%s", makefile)
	}
	for _, want := range []string{
		"project-upgrade:",
		"go run $(CODEGEN_MODULE)/cmd/roost@latest project upgrade --root . -core latest -kit latest -skill latest -codegen latest",
		"roost-up:",
		"GOWORK=off go get -u ./...",
		"GOWORK=off go mod tidy",
		"codegen-up:",
		"go install $(CODEGEN_MODULE)/cmd/roost@latest",
	} {
		if !strings.Contains(makefile, want) {
			t.Errorf("generated Makefile missing %q:\n%s", want, makefile)
		}
	}
	ci := string(plan[".github/workflows/ci.yml"].Body)
	if !strings.Contains(ci, "make deps-update") {
		t.Fatalf("generated CI does not test the latest framework set:\n%s", ci)
	}
}

func TestGeneratedBeginnerAndManifestDocumentationIsComplete(t *testing.T) {
	m := DefaultManifest("planet", "example.com/planet", []string{"game"}, []string{"configdata"}, nil)
	plan, err := renderProject(m)
	if err != nil {
		t.Fatal(err)
	}
	manifestGuide := string(plan["docs/ROOST_YAML.zh-CN.md"].Body)
	for _, want := range []string{
		"schema", "project.name", "project.module", "versions.core", "versions.kit",
		"versions.skill", "versions.codegen", "shared_mods", "services.<name>.mods",
		"features", "sagas", "ids", "groups", "min", "max", "完整示例",
		"Feature 和 Mod 必须分别理解", "roost id next protocol -group game",
		minimumVersions.Core, minimumVersions.Kit, minimumVersions.Skill, minimumVersions.Codegen,
	} {
		if !strings.Contains(manifestGuide, want) {
			t.Errorf("manifest guide missing %q:\n%s", want, manifestGuide)
		}
	}
	for mod := range modCatalog {
		if !strings.Contains(manifestGuide, "| "+mod+" |") {
			t.Errorf("manifest guide missing mod %q", mod)
		}
	}
	for feature := range knownFeatures {
		if !strings.Contains(manifestGuide, "| "+feature+" |") {
			t.Errorf("manifest guide missing feature %q", feature)
		}
	}
	quickstart := string(plan["docs/QUICKSTART.zh-CN.md"].Body)
	for _, want := range []string{
		"零基础快速开始", "Go 1.25", "Service", "Mod", "Feature", "Generated file",
		"make deps-update", "make generate", "make doctor", "make run SERVICE=game",
		"roost add protocol", "常见问题", "ROOST_YAML.zh-CN.md",
	} {
		if !strings.Contains(quickstart, want) {
			t.Errorf("beginner guide missing %q:\n%s", want, quickstart)
		}
	}
}

func TestSyncUpgradesLegacyGeneratedMakefile(t *testing.T) {
	target := filepath.Join(t.TempDir(), "planet")
	_, root, err := NewProject(NewOptions{Name: "planet", Module: "example.com/planet", Out: target})
	if err != nil {
		t.Fatal(err)
	}
	makefilePath := filepath.Join(root, "Makefile")
	legacy := []byte("# Code generated by roost-codegen. DO NOT EDIT.\n\n.PHONY: sync\nsync:\n\t$(ROOST) project sync\n")
	if err := os.WriteFile(makefilePath, legacy, 0o644); err != nil {
		t.Fatal(err)
	}
	result, err := SyncProject(root)
	if err != nil {
		t.Fatalf("upgrade legacy project: %v", err)
	}
	if !contains(result.Updated, "Makefile") {
		t.Fatalf("updated files = %v, want Makefile", result.Updated)
	}
	upgraded, err := os.ReadFile(makefilePath)
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"project-upgrade:", "roost-up:", "codegen-up:"} {
		if !bytes.Contains(upgraded, []byte(want)) {
			t.Errorf("upgraded Makefile missing %q:\n%s", want, upgraded)
		}
	}
}

func TestSyncRefusesUnmanagedMakefile(t *testing.T) {
	target := filepath.Join(t.TempDir(), "planet")
	_, root, err := NewProject(NewOptions{Name: "planet", Module: "example.com/planet", Out: target})
	if err != nil {
		t.Fatal(err)
	}
	makefilePath := filepath.Join(root, "Makefile")
	custom := []byte("build:\n\tgo build ./...\n")
	if err := os.WriteFile(makefilePath, custom, 0o644); err != nil {
		t.Fatal(err)
	}
	manifest, err := LoadManifest(root)
	if err != nil {
		t.Fatal(err)
	}
	manifest.Versions.Codegen = minimumVersions.Codegen
	if err := saveManifest(root, manifest); err != nil {
		t.Fatal(err)
	}
	manifestPath := filepath.Join(root, ManifestName)
	manifestBefore, err := os.ReadFile(manifestPath)
	if err != nil {
		t.Fatal(err)
	}
	if err := Run([]string{"project", "upgrade", "--root", root, "-codegen", "latest"}, io.Discard, io.Discard); err == nil || !strings.Contains(err.Error(), "preflight project upgrade") {
		t.Fatalf("expected upgrade preflight conflict, got %v", err)
	}
	manifestAfter, err := os.ReadFile(manifestPath)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(manifestBefore, manifestAfter) {
		t.Fatal("failed upgrade modified roost.yaml before ownership preflight")
	}
	if _, err := SyncProject(root); err == nil || !strings.Contains(err.Error(), "refusing to overwrite non-generated file Makefile") {
		t.Fatalf("expected unmanaged Makefile conflict, got %v", err)
	}
	after, err := os.ReadFile(makefilePath)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(after, custom) {
		t.Fatal("unmanaged Makefile was modified")
	}
}

func TestDiffIgnoresResolvedUserOwnedGoMod(t *testing.T) {
	target := filepath.Join(t.TempDir(), "planet")
	_, root, err := NewProject(NewOptions{Name: "planet", Module: "example.com/planet", Out: target})
	if err != nil {
		t.Fatal(err)
	}
	goModPath := filepath.Join(root, "go.mod")
	goMod, err := os.ReadFile(goModPath)
	if err != nil {
		t.Fatal(err)
	}
	goMod = bytes.Replace(goMod, []byte(minimumVersions.Core), []byte("v1.99.0"), 1)
	if err := os.WriteFile(goModPath, goMod, 0o644); err != nil {
		t.Fatal(err)
	}
	var output bytes.Buffer
	if err := DiffProject(root, &output); err != nil {
		t.Fatal(err)
	}
	if strings.Contains(output.String(), "go.mod") {
		t.Fatalf("project diff reported the dependency resolver-owned go.mod:\n%s", output.String())
	}
}

func TestSyncPreflightsConflictsBeforeWriting(t *testing.T) {
	target := filepath.Join(t.TempDir(), "planet")
	_, root, err := NewProject(NewOptions{Name: "planet", Module: "example.com/planet", Out: target, Features: []string{"config"}})
	if err != nil {
		t.Fatal(err)
	}
	makefile := filepath.Join(root, "Makefile")
	before, err := os.ReadFile(makefile)
	if err != nil {
		t.Fatal(err)
	}
	bootstrap := filepath.Join(root, "internal", "bootstrap", "generated.go")
	if err := os.WriteFile(bootstrap, []byte("package bootstrap\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	m, err := LoadManifest(root)
	if err != nil {
		t.Fatal(err)
	}
	m.Services["gate"] = ServiceSpec{Mods: []string{"etcd"}}
	if err := saveManifest(root, m); err != nil {
		t.Fatal(err)
	}
	if _, err := SyncProject(root); err == nil {
		t.Fatal("expected ownership conflict")
	}
	after, err := os.ReadFile(makefile)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(before, after) {
		t.Fatal("Makefile changed before a later preflight conflict")
	}
}
