package dao

var daoTemplate = `// Code generated by tool/dao. DO NOT EDIT.
package {{.Package}}

import (
	"fmt"
	"sort"
	"github.com/tjbdwanghaibo/cube-core/dataengine"
	"github.com/tjbdwanghaibo/cube-core/entity"
	"github.com/tjbdwanghaibo/cube-core/migration"
	"github.com/tjbdwanghaibo/cube-core/nest"
{{- if .HasMaps}}
	fmap "github.com/tjbdwanghaibo/cube-core/safemap"
{{- end}}
	"go.mongodb.org/mongo-driver/v2/bson"
)

// {{.Dao.Name}} is the DAO for collection "{{.Dao.Coll}}".
type {{.Dao.Name}} struct {
	id      int64
	tracker dataengine.Tracker
{{- range .Dao.Fields}}
	{{fieldVar .Name}} {{fieldType .}}
{{- end}}
}

// Ensure interface compliance.
var _ entity.DaoInterface = (*{{.Dao.Name}})(nil)
var _ nest.RollbackSnapshotter = (*{{.Dao.Name}})(nil)
var _ nest.MutationParticipant = (*{{.Dao.Name}})(nil)

const (
	{{daoDBConst .Dao.Name}} = "{{.Dao.Db}}"
	{{daoCollConst .Dao.Name}} = "{{.Dao.Coll}}"
	{{.Dao.Name}}SchemaVersion uint32 = 1
)

// New{{.Dao.Name}} creates a new {{.Dao.Name}} instance with initialized maps/slices.
func New{{.Dao.Name}}() *{{.Dao.Name}} {
	d := &{{.Dao.Name}}{}
{{- range .Dao.Fields}}
{{- if eq .Kind 2}}
	d.{{fieldVar .Name}} = {{mapNewExpr . "0"}}
{{- end}}
{{- end}}
	return d
}

func (d *{{.Dao.Name}}) Id() int64        { return d.id }
func (d *{{.Dao.Name}}) SetId(id int64)   { d.id = id }
func (d *{{.Dao.Name}}) DbName() string   { return {{daoDBConst .Dao.Name}} }
func (d *{{.Dao.Name}}) DbScope() dataengine.DatabaseScope { return {{dbScope .Dao}} }
func (d *{{.Dao.Name}}) CollName() string  { return {{daoCollConst .Dao.Name}} }
func (d *{{.Dao.Name}}) SchemaVersion() uint32 { return {{.Dao.Name}}SchemaVersion }
func (d *{{.Dao.Name}}) Migrate(raw []byte, from uint32) ([]byte, error) { return migration.MigrateDAO(d.CollName(), raw, from, {{.Dao.Name}}SchemaVersion) }
func (d *{{.Dao.Name}}) Dirty() entity.IDirty { return &d.tracker }
func (d *{{.Dao.Name}}) CleanDirty()      { d.tracker.SelfClean() }
func (d *{{.Dao.Name}}) DirtyTracker() *dataengine.Tracker { return &d.tracker }

const (
{{- range .Dao.Fields}}
	{{fieldMaskName $.Dao.Name .Name}} uint64 = 1 << iota
{{- end}}
)

{{range .Dao.Fields}}
func (d *{{$.Dao.Name}}) mark{{.Name}}Dirty() {
	{{- if .Tag.Persist}}
	if err := nest.MarkPersist(d, {{fieldMaskName $.Dao.Name .Name}}); err != nil {
		panic(fmt.Errorf("{{$.Dao.Name}}: mark {{.Name}} persistence: %w", err))
	}
	{{- end}}
	{{- if .Tag.Sync}}
	d.tracker.MarkSync({{fieldMaskName $.Dao.Name .Name}})
	{{- end}}
}
{{end}}

{{range .Dao.Fields}}
{{- if eq .Kind 2}}
func (d *{{$.Dao.Name}}) mark{{.Name}}KeyDirty(key {{.MapKey}}, val {{mapValType .}}) {
	{{- if .Tag.Persist}}
	if path, ok := dataengine.MapPatchPath("{{bsonKey .Name}}", key); ok {
		if err := nest.MarkPersistSet(d, {{fieldMaskName $.Dao.Name .Name}}, path, val); err != nil {
			panic(fmt.Errorf("{{$.Dao.Name}}: mark {{.Name}} key persistence: %w", err))
		}
	} else {
		if err := nest.MarkPersistFull(d, {{fieldMaskName $.Dao.Name .Name}}, "{{bsonKey .Name}}"); err != nil {
			panic(fmt.Errorf("{{$.Dao.Name}}: mark {{.Name}} persistence: %w", err))
		}
	}
	{{- end}}
	{{- if .Tag.Sync}}
	d.tracker.MarkSync({{fieldMaskName $.Dao.Name .Name}})
	{{- end}}
}

func (d *{{$.Dao.Name}}) mark{{.Name}}KeyDeleted(key {{.MapKey}}) {
	{{- if .Tag.Persist}}
	if path, ok := dataengine.MapPatchPath("{{bsonKey .Name}}", key); ok {
		if err := nest.MarkPersistUnset(d, {{fieldMaskName $.Dao.Name .Name}}, path); err != nil {
			panic(fmt.Errorf("{{$.Dao.Name}}: mark {{.Name}} delete persistence: %w", err))
		}
	} else {
		if err := nest.MarkPersistFull(d, {{fieldMaskName $.Dao.Name .Name}}, "{{bsonKey .Name}}"); err != nil {
			panic(fmt.Errorf("{{$.Dao.Name}}: mark {{.Name}} persistence: %w", err))
		}
	}
	{{- end}}
	{{- if .Tag.Sync}}
	d.tracker.MarkSync({{fieldMaskName $.Dao.Name .Name}})
	{{- end}}
}
{{end}}
{{- end}}

// Init wires dirty callbacks for nested structs and map values.
func (d *{{.Dao.Name}}) Init() {
{{- range .Dao.Fields}}
{{- if eq .Kind 3}}
{{- if isNested .TypeStr}}
	{{- if .IsPtr}}
	if d.{{fieldVar .Name}} != nil {
		d.{{fieldVar .Name}}.SetNotify(d.mark{{.Name}}Dirty)
	}
	{{- else}}
	d.{{fieldVar .Name}}.SetNotify(d.mark{{.Name}}Dirty)
	{{- end}}
{{- end}}
{{- end}}
{{- if eq .Kind 2}}
{{- if .IsPtr}}
{{- if isNested .MapVal}}
	if d.{{fieldVar .Name}} != nil {
		d.{{fieldVar .Name}}.Range(func(key {{.MapKey}}, v {{mapValType .}}) bool {
			if v != nil {
				key, v := key, v
				v.SetNotify(func() { d.mark{{.Name}}KeyDirty(key, v) })
			}
			return true
		})
	}
{{- end}}
{{- end}}
{{- end}}
{{- if eq .Kind 1}}
{{- if .IsPtr}}
{{- if isNested .SliceElem}}
	for _, v := range d.{{fieldVar .Name}} {
		v.SetNotify(d.mark{{.Name}}Dirty)
	}
{{- end}}
{{- end}}
{{- end}}
{{- end}}
}

// --- Accessors ---
{{range .Dao.Fields}}
{{- if eq .Kind 0}}
func (d *{{$.Dao.Name}}) Get{{.Name}}() {{.TypeStr}} { return d.{{fieldVar .Name}} }
{{end}}
{{- if eq .Kind 3}}
{{- if .IsPtr}}
func (d *{{$.Dao.Name}}) Get{{.Name}}() {{.TypeStr}} { return d.{{fieldVar .Name}} }
{{- else}}
func (d *{{$.Dao.Name}}) Get{{.Name}}() *{{.TypeStr}} { return &d.{{fieldVar .Name}} }
{{- end}}
{{end}}
{{- if eq .Kind 1}}
func (d *{{$.Dao.Name}}) Get{{.Name}}(idx int) ({{if .IsPtr}}*{{.SliceElem}}{{else}}{{.SliceElem}}{{end}}, bool) {
	if idx < 0 || idx >= len(d.{{fieldVar .Name}}) {
		var zero {{if .IsPtr}}*{{.SliceElem}}{{else}}{{.SliceElem}}{{end}}
		return zero, false
	}
	return d.{{fieldVar .Name}}[idx], true
}
{{end}}
{{end}}

// --- Mutators ---

// recordUndo / recordUndoToken register the inverse operation and panic when
// registration fails: continuing would let the mutation escape rollback
// coverage, silently breaking the transaction guarantee.
func (d *{{.Dao.Name}}) recordUndo(tx *nest.RollbackTx, field uint64, fn func() error) {
	if err := tx.RecordUndo(d, field, fn); err != nil {
		panic(fmt.Errorf("{{.Dao.Name}}: record undo: %w", err))
	}
}

func (d *{{.Dao.Name}}) recordUndoToken(tx *nest.RollbackTx, field uint64, token any, fn func() error) {
	if err := tx.RecordUndoToken(d, field, token, fn); err != nil {
		panic(fmt.Errorf("{{.Dao.Name}}: record undo: %w", err))
	}
}
{{range dirtyFields .Dao.Fields}}
{{- if eq .Kind 0}}
func (d *{{$.Dao.Name}}) Set{{.Name}}(v {{.TypeStr}}) {
	if d.{{fieldVar .Name}} != v {
		if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
			old := d.{{fieldVar .Name}}
			d.recordUndo(tx, {{fieldMaskName $.Dao.Name .Name}}, func() error { d.{{fieldVar .Name}} = old; return nil })
		}
		d.{{fieldVar .Name}} = v
		d.mark{{.Name}}Dirty()
	}
}
{{end}}
{{- if eq .Kind 3}}
func (d *{{$.Dao.Name}}) Set{{.Name}}(v {{.TypeStr}}) {
	if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
		old := d.{{fieldVar .Name}}
		d.recordUndo(tx, {{fieldMaskName $.Dao.Name .Name}}, func() error {
			d.{{fieldVar .Name}} = old
{{- if isNested .TypeStr}}
			{{- if .IsPtr}}
			if d.{{fieldVar .Name}} != nil {
				d.{{fieldVar .Name}}.SetNotify(d.mark{{.Name}}Dirty)
			}
			{{- else}}
			d.{{fieldVar .Name}}.SetNotify(d.mark{{.Name}}Dirty)
			{{- end}}
{{- end}}
			return nil
		})
	}
	d.{{fieldVar .Name}} = v
{{- if isNested .TypeStr}}
	{{- if .IsPtr}}
	if d.{{fieldVar .Name}} != nil {
		d.{{fieldVar .Name}}.SetNotify(d.mark{{.Name}}Dirty)
	}
	{{- else}}
	d.{{fieldVar .Name}}.SetNotify(d.mark{{.Name}}Dirty)
	{{- end}}
{{- end}}
	d.mark{{.Name}}Dirty()
}
{{end}}
{{- if eq .Kind 2}}
func (d *{{$.Dao.Name}}) Get{{.Name}}(key {{.MapKey}}) ({{if .IsPtr}}*{{.MapVal}}{{else}}{{.MapVal}}{{end}}, bool) {
	if d.{{fieldVar .Name}} == nil {
		var zero {{mapValType .}}
		return zero, false
	}
	return d.{{fieldVar .Name}}.Get(key)
}

func (d *{{$.Dao.Name}}) Set{{.Name}}(key {{.MapKey}}, val {{if .IsPtr}}*{{.MapVal}}{{else}}{{.MapVal}}{{end}}) {
	if d.{{fieldVar .Name}} == nil {
		d.{{fieldVar .Name}} = {{mapNewExpr . "0"}}
	}
	if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
		old, existed := d.{{fieldVar .Name}}.Get(key)
		d.recordUndoToken(tx, {{fieldMaskName $.Dao.Name .Name}}, key, func() error {
			if existed { d.{{fieldVar .Name}}.Set(key, old) } else { d.{{fieldVar .Name}}.Delete(key) }
			d.Init()
			return nil
		})
	}
{{- if .IsPtr}}
{{- if isNested .MapVal}}
	if val != nil {
		val.SetNotify(func() { d.mark{{.Name}}KeyDirty(key, val) })
	}
{{- end}}
{{- end}}
	d.{{fieldVar .Name}}.Set(key, val)
	d.mark{{.Name}}KeyDirty(key, val)
}

func (d *{{$.Dao.Name}}) Del{{.Name}}(key {{.MapKey}}) {
	if d.{{fieldVar .Name}} == nil {
		return
	}
	if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
		old, existed := d.{{fieldVar .Name}}.Get(key)
		d.recordUndoToken(tx, {{fieldMaskName $.Dao.Name .Name}}, key, func() error {
			if existed { d.{{fieldVar .Name}}.Set(key, old); d.Init() }
			return nil
		})
	}
{{- if .IsPtr}}
{{- if isNested .MapVal}}
	if v, ok := d.{{fieldVar .Name}}.Get(key); ok && v != nil {
		v.SetNotify(nil)
	}
{{- end}}
{{- end}}
	if d.{{fieldVar .Name}}.Delete(key) {
		d.mark{{.Name}}KeyDeleted(key)
	}
}

func (d *{{$.Dao.Name}}) Range{{.Name}}(f func(key {{.MapKey}}, val {{if .IsPtr}}*{{.MapVal}}{{else}}{{.MapVal}}{{end}}) bool) {
	if d.{{fieldVar .Name}} == nil || f == nil {
		return
	}
	d.{{fieldVar .Name}}.Range(f)
}

func (d *{{$.Dao.Name}}) {{.Name}}Len() int {
	if d.{{fieldVar .Name}} == nil {
		return 0
	}
	return d.{{fieldVar .Name}}.Len()
}
{{end}}
{{- if eq .Kind 1}}
func (d *{{$.Dao.Name}}) Add{{.Name}}(v {{if .IsPtr}}*{{.SliceElem}}{{else}}{{.SliceElem}}{{end}}) {
	if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
		old := d.{{fieldVar .Name}}
		d.recordUndo(tx, {{fieldMaskName $.Dao.Name .Name}}, func() error {
			d.{{fieldVar .Name}} = old
			d.Init()
			return nil
		})
	}
{{- if .IsPtr}}
{{- if isNested .SliceElem}}
	v.SetNotify(d.mark{{.Name}}Dirty)
{{- end}}
{{- end}}
	d.{{fieldVar .Name}} = append(d.{{fieldVar .Name}}, v)
	d.mark{{.Name}}Dirty()
}

func (d *{{$.Dao.Name}}) Set{{.Name}}All(v {{.TypeStr}}) {
	if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
		old := d.{{fieldVar .Name}}
		d.recordUndo(tx, {{fieldMaskName $.Dao.Name .Name}}, func() error {
			d.{{fieldVar .Name}} = old
			d.Init()
			return nil
		})
	}
{{- if .IsPtr}}
{{- if isNested .SliceElem}}
	for _, item := range v {
		item.SetNotify(d.mark{{.Name}}Dirty)
	}
{{- end}}
{{- end}}
	d.{{fieldVar .Name}} = append({{.TypeStr}}(nil), v...)
	d.mark{{.Name}}Dirty()
}

func (d *{{$.Dao.Name}}) Range{{.Name}}(f func(idx int, val {{if .IsPtr}}*{{.SliceElem}}{{else}}{{.SliceElem}}{{end}}) bool) {
	if f == nil {
		return
	}
	for i, v := range d.{{fieldVar .Name}} {
		if !f(i, v) {
			break
		}
	}
}

func (d *{{$.Dao.Name}}) {{.Name}}Len() int {
	return len(d.{{fieldVar .Name}})
}
{{end}}
{{- end}}

{{range .Dao.Fields}}
{{- if eq .Kind 2}}
func (d *{{$.Dao.Name}}) {{mapHelperName $.Dao.Name .Name}}() {{rawMapType .}} {
	if d.{{fieldVar .Name}} == nil {
		return nil
	}
	ret := make({{rawMapType .}}, d.{{fieldVar .Name}}.Len())
	d.{{fieldVar .Name}}.Range(func(key {{.MapKey}}, val {{mapValType .}}) bool {
		ret[key] = val
		return true
	})
	return ret
}

func (d *{{$.Dao.Name}}) set{{.Name}}RawMap(src {{rawMapType .}}) {
	d.{{fieldVar .Name}} = {{mapNewExpr . "len(src)"}}
	for key, val := range src {
{{- if .IsPtr}}
{{- if isNested .MapVal}}
		if val != nil {
			key, val := key, val
			val.SetNotify(func() { d.mark{{.Name}}KeyDirty(key, val) })
		}
{{- end}}
{{- end}}
		d.{{fieldVar .Name}}.Set(key, val)
	}
}
{{end}}
{{- end}}

// --- Marshal (persist fields) ---

// CaptureRollbackState is side-effect free and includes transient and
// sync-only fields. Persistence changes live in RollbackTx, not in the DAO.
func (d *{{.Dao.Name}}) CaptureRollbackState() ([]byte, error) {
	type rollbackDoc struct {
		Id int64 ` + "`" + `bson:"_id"` + "`" + `
{{- range .Dao.Fields}}
		{{.Name}} {{if eq .Kind 2}}{{rawMapType .}}{{else}}{{.TypeStr}}{{end}} ` + "`" + `bson:"{{bsonKey .Name}}"` + "`" + `
{{- end}}
	}
	doc := rollbackDoc{
		Id: d.id,
{{- range .Dao.Fields}}
{{- if eq .Kind 2}}
		{{.Name}}: d.{{mapHelperName $.Dao.Name .Name}}(),
{{- else}}
		{{.Name}}: d.{{fieldVar .Name}},
{{- end}}
{{- end}}
	}
	return bson.Marshal(doc)
}

func (d *{{.Dao.Name}}) RestoreRollbackState(raw []byte) error {
	type rollbackDoc struct {
		Id int64 ` + "`" + `bson:"_id"` + "`" + `
{{- range .Dao.Fields}}
		{{.Name}} {{if eq .Kind 2}}{{rawMapType .}}{{else}}{{.TypeStr}}{{end}} ` + "`" + `bson:"{{bsonKey .Name}}"` + "`" + `
{{- end}}
	}
	var doc rollbackDoc
	if err := bson.Unmarshal(raw, &doc); err != nil { return err }
	d.id = doc.Id
{{- range .Dao.Fields}}
{{- if eq .Kind 2}}
	d.set{{.Name}}RawMap(doc.{{.Name}})
{{- else}}
	d.{{fieldVar .Name}} = doc.{{.Name}}
{{- end}}
{{- end}}
	d.Init()
	return nil
}

func (d *{{.Dao.Name}}) marshalCommitState() ([]byte, error) {
	doc := bson.M{
		"_id": d.id,
		"_schema": {{.Dao.Name}}SchemaVersion,
{{- range persistFields .Dao.Fields}}
{{- if eq .Kind 2}}
		"{{bsonKey .Name}}": d.{{mapHelperName $.Dao.Name .Name}}(),
{{- else}}
		"{{bsonKey .Name}}": d.{{fieldVar .Name}},
{{- end}}
{{- end}}
	}
	return bson.Marshal(doc)
}

func (d *{{.Dao.Name}}) PrepareMutation(change nest.PersistChange) (dataengine.Mutation, error) {
	version := d.tracker.Version()
	mutation := dataengine.Mutation{
		Key: dataengine.DocumentKey{
			Database: d.DbName(), Scope: dataengine.DatabaseScope(d.DbScope()),
			Resource: d.CollName(), ID: d.Id(),
		},
		Kind: dataengine.MutationPatch, ExpectedVersion: version, NextVersion: version + 1,
		Mask: change.Mask, Schema: {{.Dao.Name}}SchemaVersion, Codec: "bson-v2",
	}
	if change.Delete {
		mutation.Kind = dataengine.MutationDelete
		return mutation, nil
	}
	if version == 0 || change.Mask == dataengine.AllFields {
		data, err := d.marshalCommitState()
		if err != nil { return dataengine.Mutation{}, fmt.Errorf("prepare put %s/%d: %w", d.CollName(), d.id, err) }
		mutation.Kind = dataengine.MutationPut
		mutation.Data = data
		return mutation, nil
	}
	patch, err := d.marshalPersistPatchBSON(change)
	if err != nil { return dataengine.Mutation{}, fmt.Errorf("prepare patch %s/%d: %w", d.CollName(), d.id, err) }
	mutation.Patch = patch
	return mutation, nil
}

func (d *{{.Dao.Name}}) AcceptMutation(mutation dataengine.Mutation) error {
	return d.tracker.AcceptVersion(mutation.ExpectedVersion, mutation.NextVersion)
}

func (d *{{.Dao.Name}}) Marshal() []byte {
	return d.MarshalPersist(dataengine.AllFields)
}

func (d *{{.Dao.Name}}) MarshalPersist(mask uint64) []byte {
	return d.marshalPersistData(mask)
}

func (d *{{.Dao.Name}}) marshalPersistData(mask uint64) []byte {
	_ = mask // full payload is used for inserts and safe fallback.
	doc := bson.M{
		"_id": d.id,
		"_schema": {{.Dao.Name}}SchemaVersion,
{{- range persistFields .Dao.Fields}}
{{- if eq .Kind 2}}
		"{{bsonKey .Name}}": d.{{mapHelperName $.Dao.Name .Name}}(),
{{- else}}
		"{{bsonKey .Name}}": d.{{fieldVar .Name}},
{{- end}}
{{- end}}
	}
	data, err := bson.Marshal(doc)
	if err != nil {
		// The interface has no error slot and a nil payload would be
		// persisted as silent data loss; a marshal failure here is a
		// programming error (unserializable state), so fail loudly and let
		// Data Engine WAL recovery owns the aftermath.
		panic(fmt.Errorf("{{.Dao.Name}}: marshal persist data: %w", err))
	}
	return data
}

func (d *{{.Dao.Name}}) persistChangeHasPath(change nest.PersistChange, field string) bool {
	prefix := field + "."
	for path := range change.Set {
		if path == field || len(path) > len(prefix) && path[:len(prefix)] == prefix { return true }
	}
	for _, path := range change.Unset {
		if path == field || len(path) > len(prefix) && path[:len(prefix)] == prefix { return true }
	}
	return false
}

func (d *{{.Dao.Name}}) persistChangePathCovered(change nest.PersistChange, path string) bool {
	for field := range change.FullFields {
		prefix := field + "."
		if path == field || len(path) > len(prefix) && path[:len(prefix)] == prefix { return true }
	}
	return false
}

func (d *{{.Dao.Name}}) marshalPersistPatchBSON(change nest.PersistChange) (dataengine.FieldPatch, error) {
	set := make(map[string]any, len(change.Set)+len(change.FullFields))
{{- range persistFields .Dao.Fields}}
	if change.Mask&{{fieldMaskName $.Dao.Name .Name}} != 0 {
{{- if eq .Kind 2}}
		_, full := change.FullFields["{{bsonKey .Name}}"]
		if full || !d.persistChangeHasPath(change, "{{bsonKey .Name}}") {
			set["{{bsonKey .Name}}"] = d.{{mapHelperName $.Dao.Name .Name}}()
		}
{{- else}}
		set["{{bsonKey .Name}}"] = d.{{fieldVar .Name}}
{{- end}}
	}
{{- end}}
	for path, value := range change.Set {
		if !d.persistChangePathCovered(change, path) { set[path] = value }
	}
	var raw []byte
	if len(set) != 0 {
		keys := make([]string, 0, len(set))
		for path := range set { keys = append(keys, path) }
		sort.Strings(keys)
		doc := make(bson.D, 0, len(keys))
		for _, path := range keys { doc = append(doc, bson.E{Key: path, Value: set[path]}) }
		var err error
		raw, err = bson.Marshal(doc)
		if err != nil { return dataengine.FieldPatch{}, err }
	}
	return dataengine.FieldPatch{SetBSON: raw, Unset: append([]string(nil), change.Unset...)}, nil
}

func (d *{{.Dao.Name}}) MarshalSync(mask uint64) []byte {
	doc := bson.M{
		"_id": d.id,
	}
{{- range syncFields .Dao.Fields}}
	if mask&{{fieldMaskName $.Dao.Name .Name}} != 0 {
{{- if eq .Kind 2}}
		doc["{{bsonKey .Name}}"] = d.{{mapHelperName $.Dao.Name .Name}}()
{{- else}}
		doc["{{bsonKey .Name}}"] = d.{{fieldVar .Name}}
{{- end}}
	}
{{- end}}
	if len(doc) == 1 {
		return nil
	}
	data, err := bson.Marshal(doc)
	if err != nil {
		// nil already means "nothing to sync"; returning it on failure would
		// silently drop a sync payload. See marshalPersistData.
		panic(fmt.Errorf("{{.Dao.Name}}: marshal sync data: %w", err))
	}
	return data
}

func (d *{{.Dao.Name}}) ApplySync(raw []byte) error {
	var doc bson.M
	if err := bson.Unmarshal(raw, &doc); err != nil {
		return err
	}
{{- range syncFields .Dao.Fields}}
	if v, ok := doc["{{bsonKey .Name}}"]; ok {
		data, err := bson.Marshal(bson.M{"v": v})
		if err != nil {
			return err
		}
		var wrap struct {
			V {{if eq .Kind 2}}{{rawMapType .}}{{else}}{{.TypeStr}}{{end}} ` + "`" + `bson:"v"` + "`" + `
		}
		if err := bson.Unmarshal(data, &wrap); err != nil {
			return err
		}
{{- if eq .Kind 2}}
		d.set{{.Name}}RawMap(wrap.V)
{{- else}}
		d.{{fieldVar .Name}} = wrap.V
{{- end}}
	}
{{- end}}
	d.Init()
	return nil
}

// --- Unmarshal ---

func (d *{{.Dao.Name}}) Unmarshal(raw []byte) error {
	type rawDoc struct {
		Id int64 ` + "`" + `bson:"_id"` + "`" + `
{{- range persistFields .Dao.Fields}}
		{{.Name}} {{if eq .Kind 2}}{{rawMapType .}}{{else}}{{.TypeStr}}{{end}} ` + "`" + `bson:"{{bsonKey .Name}}"` + "`" + `
{{- end}}
	}
	var dd rawDoc
	if err := bson.Unmarshal(raw, &dd); err != nil {
		return err
	}
	d.id = dd.Id
{{- range persistFields .Dao.Fields}}
{{- if eq .Kind 2}}
	d.set{{.Name}}RawMap(dd.{{.Name}})
{{- else}}
	d.{{fieldVar .Name}} = dd.{{.Name}}
{{- end}}
{{- end}}
	d.Init()
	return nil
}

// RestorePersisted is the single production hydration path used by the
// Data Engine aggregate repository. Migration and tracker restoration happen
// before the DAO is published through its entity.
func (d *{{.Dao.Name}}) RestorePersisted(raw []byte, schemaVersion uint32, version uint64) error {
	if schemaVersion > {{.Dao.Name}}SchemaVersion {
		return fmt.Errorf("dao {{.Dao.Name}}: stored schema %d is newer than runtime schema %d", schemaVersion, {{.Dao.Name}}SchemaVersion)
	}
	var err error
	if schemaVersion < {{.Dao.Name}}SchemaVersion {
		raw, err = d.Migrate(raw, schemaVersion)
		if err != nil {
			return fmt.Errorf("dao {{.Dao.Name}}: migrate schema %d to %d: %w", schemaVersion, {{.Dao.Name}}SchemaVersion, err)
		}
	}
	if err := d.Unmarshal(raw); err != nil {
		return err
	}
	d.tracker.SetVersion(version)
	d.CleanDirty()
	return nil
}

// compile-time import guards
var (
	_ = dataengine.Tracker{}
	_ = bson.M{}
)
`
