package dao

// bsonHelpersFileName is the one file per package holding the generic
// container conversions the nested wire forms use.
const bsonHelpersFileName = "gen_dao_bson_helpers.go"

// bsonHelpersTemplate is written once per output package that has nested
// structs. The two functions map a per-type conversion over a map or a slice
// in either direction (stored form <-> wire form); see wireType in gen.go.
var bsonHelpersTemplate = `// Code generated by tool/dao. DO NOT EDIT.
package {{.Package}}

// daoMapDocs maps conv over src; nil stays nil so an absent map is not
// persisted as an empty one.
func daoMapDocs[K comparable, V, D any](src map[K]V, conv func(V) D) map[K]D {
	if src == nil {
		return nil
	}
	out := make(map[K]D, len(src))
	for key, val := range src {
		out[key] = conv(val)
	}
	return out
}

// daoSliceDocs maps conv over src; nil stays nil.
func daoSliceDocs[V, D any](src []V, conv func(V) D) []D {
	if src == nil {
		return nil
	}
	out := make([]D, len(src))
	for i, val := range src {
		out[i] = conv(val)
	}
	return out
}
`
