package dao

var nestedTemplate = `// Code generated by tool/dao. DO NOT EDIT.
package {{.Package}}

import (
	"fmt"

	"github.com/tjbdwanghaibo/cube-core/checkpoint"
	"github.com/tjbdwanghaibo/cube-core/nest"
{{- if hasMaps .Nested.Fields}}
	fmap "github.com/tjbdwanghaibo/cube-core/map"
{{- end}}
)

// {{.Nested.Name}} is a nested struct with dirty propagation.
type {{.Nested.Name}} struct {
	checkpoint.DirtyHook
{{- range .Nested.Fields}}
	{{fieldVar .Name}} {{fieldType .}}
{{- end}}
}
{{range .Nested.Fields}}
{{- if eq .Kind 0}}
func (s *{{$.Nested.Name}}) Get{{.Name}}() {{.TypeStr}} { return s.{{fieldVar .Name}} }
{{end}}
{{- if eq .Kind 3}}
{{- if .IsPtr}}
func (s *{{$.Nested.Name}}) Get{{.Name}}() {{.TypeStr}} { return s.{{fieldVar .Name}} }
{{- else}}
func (s *{{$.Nested.Name}}) Get{{.Name}}() *{{.TypeStr}} { return &s.{{fieldVar .Name}} }
{{- end}}
{{end}}
{{- if eq .Kind 1}}
func (s *{{$.Nested.Name}}) Get{{.Name}}(idx int) ({{if .IsPtr}}*{{.SliceElem}}{{else}}{{.SliceElem}}{{end}}, bool) {
	if idx < 0 || idx >= len(s.{{fieldVar .Name}}) {
		var zero {{if .IsPtr}}*{{.SliceElem}}{{else}}{{.SliceElem}}{{end}}
		return zero, false
	}
	return s.{{fieldVar .Name}}[idx], true
}

func (s *{{$.Nested.Name}}) Range{{.Name}}(f func(idx int, val {{if .IsPtr}}*{{.SliceElem}}{{else}}{{.SliceElem}}{{end}}) bool) {
	if f == nil { return }
	for idx, val := range s.{{fieldVar .Name}} {
		if !f(idx, val) { return }
	}
}

func (s *{{$.Nested.Name}}) {{.Name}}Len() int { return len(s.{{fieldVar .Name}}) }
{{end}}
{{- if eq .Kind 2}}
func (s *{{$.Nested.Name}}) Get{{.Name}}(key {{.MapKey}}) ({{mapValType .}}, bool) {
	if s.{{fieldVar .Name}} == nil {
		var zero {{mapValType .}}
		return zero, false
	}
	return s.{{fieldVar .Name}}.Get(key)
}

func (s *{{$.Nested.Name}}) Range{{.Name}}(f func(key {{.MapKey}}, val {{mapValType .}}) bool) {
	if s.{{fieldVar .Name}} == nil || f == nil { return }
	s.{{fieldVar .Name}}.Range(f)
}

func (s *{{$.Nested.Name}}) {{.Name}}Len() int {
	if s.{{fieldVar .Name}} == nil { return 0 }
	return s.{{fieldVar .Name}}.Len()
}
{{end}}
{{end}}
{{range $idx, $field := .Nested.Fields}}
func (s *{{$.Nested.Name}}) Set{{.Name}}(v {{if eq .Kind 2}}{{rawMapType .}}{{else}}{{.TypeStr}}{{end}}) {
	if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
		old := s.{{fieldVar .Name}}
		if err := tx.RecordUndo(s, uint64({{$idx}}), func() error { s.{{fieldVar .Name}} = old; return nil }); err != nil {
			// A mutation without undo coverage silently breaks rollback;
			// failing loudly matches the generated DAO setters.
			panic(fmt.Errorf("{{$.Nested.Name}}: record undo: %w", err))
		}
	}
{{- if eq .Kind 0}}
	if s.{{fieldVar .Name}} != v {
		s.{{fieldVar .Name}} = v
		s.Mark()
	}
{{- else if eq .Kind 2}}
	s.{{fieldVar .Name}} = {{mapNewExpr . "len(v)"}}
	for key, val := range v {
		s.{{fieldVar .Name}}.Set(key, val)
	}
	s.Mark()
{{- else if eq .Kind 1}}
	s.{{fieldVar .Name}} = append({{.TypeStr}}(nil), v...)
	s.Mark()
{{- else}}
	s.{{fieldVar .Name}} = v
	s.Mark()
{{- end}}
}
{{end}}`
