package dao

// bsonHelpersFileName is the one file per package holding the generic
// container conversions the nested wire forms use.
const bsonHelpersFileName = "gen_dao_bson_helpers.go"

// bsonHelpersTemplate is written once per output package that has nested
// structs. The two functions map a per-type conversion over a map or a slice
// in either direction (stored form <-> wire form); see wireType in gen.go.
var bsonHelpersTemplate = `// Code generated by tool/dao. DO NOT EDIT.
package {{.Package}}

// daoMapDocs maps conv over src; nil stays nil so an absent map is not
// persisted as an empty one.
func daoMapDocs[K comparable, V, D any](src map[K]V, conv func(V) D) map[K]D {
	if src == nil {
		return nil
	}
	out := make(map[K]D, len(src))
	for key, val := range src {
		out[key] = conv(val)
	}
	return out
}

// daoSliceDocs maps conv over src; nil stays nil.
func daoSliceDocs[V, D any](src []V, conv func(V) D) []D {
	if src == nil {
		return nil
	}
	out := make([]D, len(src))
	for i, val := range src {
		out[i] = conv(val)
	}
	return out
}
`

// fieldCarriesChildHook reports whether a nested struct's field holds nested
// children whose changes have to reach this struct through a callback. Those
// are the fields that need bind/unbind helpers: which child notifies which
// parent is runtime wiring, and it has to be re-established on every path
// that changes what the field holds — the setter, a restore from storage, and
// the rollback undo (RR-20260918-03).
func fieldCarriesChildHook(defs *Definitions, f FieldDef) bool {
	switch f.Kind {
	case 1:
		return f.IsPtr && isNestedType(defs, f.SliceElem)
	case 2:
		return f.IsPtr && isNestedType(defs, f.MapVal)
	case 3:
		return isNestedType(defs, f.TypeStr)
	}
	return false
}

// fieldDetachesOldChildren narrows fieldCarriesChildHook to the fields whose
// previous contents survive the assignment as separate objects and therefore
// have to be released. A nested value field is overwritten in place — there is
// no old object left to notify anyone — so it is bound but never unbound.
func fieldDetachesOldChildren(defs *Definitions, f FieldDef) bool {
	return fieldCarriesChildHook(defs, f) && (f.Kind != 3 || f.IsPtr)
}
