package dao

var daoTemplate = `// Code generated by tool/dao. DO NOT EDIT.
package {{.Package}}

import (
	"fmt"
	"github.com/tjbdwanghaibo/cube-core/checkpoint"
	"github.com/tjbdwanghaibo/cube-core/entity"
	"github.com/tjbdwanghaibo/cube-core/migration"
	"github.com/tjbdwanghaibo/cube-core/nest"
{{- if .HasMaps}}
	fmap "github.com/tjbdwanghaibo/cube-core/map"
{{- end}}
	"go.mongodb.org/mongo-driver/v2/bson"
)

// {{.Dao.Name}} is the DAO for collection "{{.Dao.Coll}}".
type {{.Dao.Name}} struct {
	id      int64
	tracker checkpoint.DirtyTracker
	persistPatchSet map[string]any
	persistPatchUnset []string
	persistPatchFull map[string]bool
{{- range .Dao.Fields}}
	{{fieldVar .Name}} {{fieldType .}}
{{- end}}
}

// Ensure interface compliance.
var _ entity.DaoInterface = (*{{.Dao.Name}})(nil)
var _ nest.RollbackSnapshotter = (*{{.Dao.Name}})(nil)
var _ nest.CommitParticipant = (*{{.Dao.Name}})(nil)

const (
	{{daoDBConst .Dao.Name}} = "{{.Dao.Db}}"
	{{daoCollConst .Dao.Name}} = "{{.Dao.Coll}}"
	{{.Dao.Name}}SchemaVersion uint32 = 1
)

// New{{.Dao.Name}} creates a new {{.Dao.Name}} instance with initialized maps/slices.
func New{{.Dao.Name}}() *{{.Dao.Name}} {
	d := &{{.Dao.Name}}{}
{{- range .Dao.Fields}}
{{- if eq .Kind 2}}
	d.{{fieldVar .Name}} = {{mapNewExpr . "0"}}
{{- end}}
{{- end}}
	return d
}

func (d *{{.Dao.Name}}) Id() int64        { return d.id }
func (d *{{.Dao.Name}}) SetId(id int64)   { d.id = id }
func (d *{{.Dao.Name}}) DbName() string   { return {{daoDBConst .Dao.Name}} }
func (d *{{.Dao.Name}}) DbScope() checkpoint.DatabaseScope { return {{dbScope .Dao}} }
func (d *{{.Dao.Name}}) CollName() string  { return {{daoCollConst .Dao.Name}} }
func (d *{{.Dao.Name}}) SchemaVersion() uint32 { return {{.Dao.Name}}SchemaVersion }
func (d *{{.Dao.Name}}) Migrate(raw []byte, from uint32) ([]byte, error) { return migration.MigrateDAO(d.CollName(), raw, from, {{.Dao.Name}}SchemaVersion) }
func (d *{{.Dao.Name}}) Dirty() entity.IDirty { return &d.tracker }
func (d *{{.Dao.Name}}) CleanDirty()      { d.tracker.SelfClean(); d.clearPersistPathPatch() }
func (d *{{.Dao.Name}}) DirtyTracker() *checkpoint.DirtyTracker { return &d.tracker }

const (
{{- range .Dao.Fields}}
	{{fieldMaskName $.Dao.Name .Name}} uint64 = 1 << iota
{{- end}}
)

{{range .Dao.Fields}}
func (d *{{$.Dao.Name}}) mark{{.Name}}Dirty() {
	d.tracker.MarkScope({{dirtyScope .}}, {{fieldMaskName $.Dao.Name .Name}})
}
{{end}}

func (d *{{.Dao.Name}}) recordPersistPatchSet(field string, path string, value any) {
	if path == "" {
		d.recordPersistPatchFull(field)
		return
	}
	if d.persistPatchSet == nil {
		d.persistPatchSet = make(map[string]any)
	}
	d.persistPatchSet[path] = value
	for i := 0; i < len(d.persistPatchUnset); {
		if d.persistPatchUnset[i] == path {
			d.persistPatchUnset = append(d.persistPatchUnset[:i], d.persistPatchUnset[i+1:]...)
			continue
		}
		i++
	}
}

func (d *{{.Dao.Name}}) recordPersistPatchUnset(field string, path string) {
	if path == "" {
		d.recordPersistPatchFull(field)
		return
	}
	delete(d.persistPatchSet, path)
	d.persistPatchUnset = append(d.persistPatchUnset, path)
}

func (d *{{.Dao.Name}}) recordPersistPatchFull(field string) {
	if field == "" {
		return
	}
	if d.persistPatchFull == nil {
		d.persistPatchFull = make(map[string]bool)
	}
	d.persistPatchFull[field] = true
}

func (d *{{.Dao.Name}}) hasPersistPathPatch(field string) bool {
	return checkpoint.PersistPatchHasPath(d.persistPatchSet, d.persistPatchUnset, field)
}

func (d *{{.Dao.Name}}) appendPersistPathPatch(patch *checkpoint.PersistPatch, fullFields map[string]bool) {
	for path, value := range d.persistPatchSet {
		if checkpoint.PersistPatchPathCovered(path, fullFields) {
			continue
		}
		patch.Set[path] = value
	}
	for _, path := range d.persistPatchUnset {
		if checkpoint.PersistPatchPathCovered(path, fullFields) {
			continue
		}
		patch.Unset = append(patch.Unset, path)
	}
	d.clearPersistPathPatch()
}

func (d *{{.Dao.Name}}) clearPersistPathPatch() {
	d.persistPatchSet = nil
	d.persistPatchUnset = nil
	d.persistPatchFull = nil
}

{{range .Dao.Fields}}
{{- if eq .Kind 2}}
func (d *{{$.Dao.Name}}) mark{{.Name}}KeyDirty(key {{.MapKey}}, val {{mapValType .}}) {
	if path, ok := checkpoint.MapPatchPath("{{bsonKey .Name}}", key); ok {
		d.recordPersistPatchSet("{{bsonKey .Name}}", path, val)
	} else {
		d.recordPersistPatchFull("{{bsonKey .Name}}")
	}
	d.mark{{.Name}}Dirty()
}

func (d *{{$.Dao.Name}}) mark{{.Name}}KeyDeleted(key {{.MapKey}}) {
	if path, ok := checkpoint.MapPatchPath("{{bsonKey .Name}}", key); ok {
		d.recordPersistPatchUnset("{{bsonKey .Name}}", path)
	} else {
		d.recordPersistPatchFull("{{bsonKey .Name}}")
	}
	d.mark{{.Name}}Dirty()
}
{{end}}
{{- end}}

// Init wires dirty callbacks for nested structs and map values.
func (d *{{.Dao.Name}}) Init() {
{{- range .Dao.Fields}}
{{- if eq .Kind 3}}
{{- if isNested .TypeStr}}
	{{- if .IsPtr}}
	if d.{{fieldVar .Name}} != nil {
		d.{{fieldVar .Name}}.SetNotify(d.mark{{.Name}}Dirty)
	}
	{{- else}}
	d.{{fieldVar .Name}}.SetNotify(d.mark{{.Name}}Dirty)
	{{- end}}
{{- end}}
{{- end}}
{{- if eq .Kind 2}}
{{- if .IsPtr}}
{{- if isNested .MapVal}}
	if d.{{fieldVar .Name}} != nil {
		d.{{fieldVar .Name}}.Range(func(key {{.MapKey}}, v {{mapValType .}}) bool {
			if v != nil {
				key, v := key, v
				v.SetNotify(func() { d.mark{{.Name}}KeyDirty(key, v) })
			}
			return true
		})
	}
{{- end}}
{{- end}}
{{- end}}
{{- if eq .Kind 1}}
{{- if .IsPtr}}
{{- if isNested .SliceElem}}
	for _, v := range d.{{fieldVar .Name}} {
		v.SetNotify(d.mark{{.Name}}Dirty)
	}
{{- end}}
{{- end}}
{{- end}}
{{- end}}
}

// --- Accessors ---
{{range .Dao.Fields}}
{{- if eq .Kind 0}}
func (d *{{$.Dao.Name}}) Get{{.Name}}() {{.TypeStr}} { return d.{{fieldVar .Name}} }
{{end}}
{{- if eq .Kind 3}}
{{- if .IsPtr}}
func (d *{{$.Dao.Name}}) Get{{.Name}}() {{.TypeStr}} { return d.{{fieldVar .Name}} }
{{- else}}
func (d *{{$.Dao.Name}}) Get{{.Name}}() *{{.TypeStr}} { return &d.{{fieldVar .Name}} }
{{- end}}
{{end}}
{{- if eq .Kind 1}}
func (d *{{$.Dao.Name}}) Get{{.Name}}(idx int) ({{if .IsPtr}}*{{.SliceElem}}{{else}}{{.SliceElem}}{{end}}, bool) {
	if idx < 0 || idx >= len(d.{{fieldVar .Name}}) {
		var zero {{if .IsPtr}}*{{.SliceElem}}{{else}}{{.SliceElem}}{{end}}
		return zero, false
	}
	return d.{{fieldVar .Name}}[idx], true
}
{{end}}
{{end}}

// --- Mutators ---

// recordUndo / recordUndoToken register the inverse operation and panic when
// registration fails: continuing would let the mutation escape rollback
// coverage, silently breaking the transaction guarantee.
func (d *{{.Dao.Name}}) recordUndo(tx *nest.RollbackTx, field uint64, fn func() error) {
	if err := tx.RecordUndo(d, field, fn); err != nil {
		panic(fmt.Errorf("{{.Dao.Name}}: record undo: %w", err))
	}
}

func (d *{{.Dao.Name}}) recordUndoToken(tx *nest.RollbackTx, field uint64, token any, fn func() error) {
	if err := tx.RecordUndoToken(d, field, token, fn); err != nil {
		panic(fmt.Errorf("{{.Dao.Name}}: record undo: %w", err))
	}
}
{{range dirtyFields .Dao.Fields}}
{{- if eq .Kind 0}}
func (d *{{$.Dao.Name}}) Set{{.Name}}(v {{.TypeStr}}) {
	if d.{{fieldVar .Name}} != v {
		if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
			old := d.{{fieldVar .Name}}
			d.recordUndo(tx, {{fieldMaskName $.Dao.Name .Name}}, func() error { d.{{fieldVar .Name}} = old; return nil })
		}
		d.{{fieldVar .Name}} = v
		d.mark{{.Name}}Dirty()
	}
}
{{end}}
{{- if eq .Kind 3}}
func (d *{{$.Dao.Name}}) Set{{.Name}}(v {{.TypeStr}}) {
	if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
		old := d.{{fieldVar .Name}}
		d.recordUndo(tx, {{fieldMaskName $.Dao.Name .Name}}, func() error {
			d.{{fieldVar .Name}} = old
{{- if isNested .TypeStr}}
			{{- if .IsPtr}}
			if d.{{fieldVar .Name}} != nil {
				d.{{fieldVar .Name}}.SetNotify(d.mark{{.Name}}Dirty)
			}
			{{- else}}
			d.{{fieldVar .Name}}.SetNotify(d.mark{{.Name}}Dirty)
			{{- end}}
{{- end}}
			return nil
		})
	}
	d.{{fieldVar .Name}} = v
{{- if isNested .TypeStr}}
	{{- if .IsPtr}}
	if d.{{fieldVar .Name}} != nil {
		d.{{fieldVar .Name}}.SetNotify(d.mark{{.Name}}Dirty)
	}
	{{- else}}
	d.{{fieldVar .Name}}.SetNotify(d.mark{{.Name}}Dirty)
	{{- end}}
{{- end}}
	d.mark{{.Name}}Dirty()
}
{{end}}
{{- if eq .Kind 2}}
func (d *{{$.Dao.Name}}) Get{{.Name}}(key {{.MapKey}}) ({{if .IsPtr}}*{{.MapVal}}{{else}}{{.MapVal}}{{end}}, bool) {
	if d.{{fieldVar .Name}} == nil {
		var zero {{mapValType .}}
		return zero, false
	}
	return d.{{fieldVar .Name}}.Get(key)
}

func (d *{{$.Dao.Name}}) Set{{.Name}}(key {{.MapKey}}, val {{if .IsPtr}}*{{.MapVal}}{{else}}{{.MapVal}}{{end}}) {
	if d.{{fieldVar .Name}} == nil {
		d.{{fieldVar .Name}} = {{mapNewExpr . "0"}}
	}
	if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
		old, existed := d.{{fieldVar .Name}}.Get(key)
		d.recordUndoToken(tx, {{fieldMaskName $.Dao.Name .Name}}, key, func() error {
			if existed { d.{{fieldVar .Name}}.Set(key, old) } else { d.{{fieldVar .Name}}.Delete(key) }
			d.Init()
			return nil
		})
	}
{{- if .IsPtr}}
{{- if isNested .MapVal}}
	if val != nil {
		val.SetNotify(func() { d.mark{{.Name}}KeyDirty(key, val) })
	}
{{- end}}
{{- end}}
	d.{{fieldVar .Name}}.Set(key, val)
	d.mark{{.Name}}KeyDirty(key, val)
}

func (d *{{$.Dao.Name}}) Del{{.Name}}(key {{.MapKey}}) {
	if d.{{fieldVar .Name}} == nil {
		return
	}
	if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
		old, existed := d.{{fieldVar .Name}}.Get(key)
		d.recordUndoToken(tx, {{fieldMaskName $.Dao.Name .Name}}, key, func() error {
			if existed { d.{{fieldVar .Name}}.Set(key, old); d.Init() }
			return nil
		})
	}
{{- if .IsPtr}}
{{- if isNested .MapVal}}
	if v, ok := d.{{fieldVar .Name}}.Get(key); ok && v != nil {
		v.SetNotify(nil)
	}
{{- end}}
{{- end}}
	if d.{{fieldVar .Name}}.Delete(key) {
		d.mark{{.Name}}KeyDeleted(key)
	}
}

func (d *{{$.Dao.Name}}) Range{{.Name}}(f func(key {{.MapKey}}, val {{if .IsPtr}}*{{.MapVal}}{{else}}{{.MapVal}}{{end}}) bool) {
	if d.{{fieldVar .Name}} == nil || f == nil {
		return
	}
	d.{{fieldVar .Name}}.Range(f)
}

func (d *{{$.Dao.Name}}) {{.Name}}Len() int {
	if d.{{fieldVar .Name}} == nil {
		return 0
	}
	return d.{{fieldVar .Name}}.Len()
}
{{end}}
{{- if eq .Kind 1}}
func (d *{{$.Dao.Name}}) Add{{.Name}}(v {{if .IsPtr}}*{{.SliceElem}}{{else}}{{.SliceElem}}{{end}}) {
	if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
		old := d.{{fieldVar .Name}}
		d.recordUndo(tx, {{fieldMaskName $.Dao.Name .Name}}, func() error {
			d.{{fieldVar .Name}} = old
			d.Init()
			return nil
		})
	}
{{- if .IsPtr}}
{{- if isNested .SliceElem}}
	v.SetNotify(d.mark{{.Name}}Dirty)
{{- end}}
{{- end}}
	d.{{fieldVar .Name}} = append(d.{{fieldVar .Name}}, v)
	d.mark{{.Name}}Dirty()
}

func (d *{{$.Dao.Name}}) Set{{.Name}}All(v {{.TypeStr}}) {
	if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
		old := d.{{fieldVar .Name}}
		d.recordUndo(tx, {{fieldMaskName $.Dao.Name .Name}}, func() error {
			d.{{fieldVar .Name}} = old
			d.Init()
			return nil
		})
	}
{{- if .IsPtr}}
{{- if isNested .SliceElem}}
	for _, item := range v {
		item.SetNotify(d.mark{{.Name}}Dirty)
	}
{{- end}}
{{- end}}
	d.{{fieldVar .Name}} = append({{.TypeStr}}(nil), v...)
	d.mark{{.Name}}Dirty()
}

func (d *{{$.Dao.Name}}) Range{{.Name}}(f func(idx int, val {{if .IsPtr}}*{{.SliceElem}}{{else}}{{.SliceElem}}{{end}}) bool) {
	if f == nil {
		return
	}
	for i, v := range d.{{fieldVar .Name}} {
		if !f(i, v) {
			break
		}
	}
}

func (d *{{$.Dao.Name}}) {{.Name}}Len() int {
	return len(d.{{fieldVar .Name}})
}
{{end}}
{{- end}}

{{range .Dao.Fields}}
{{- if eq .Kind 2}}
func (d *{{$.Dao.Name}}) {{mapHelperName $.Dao.Name .Name}}() {{rawMapType .}} {
	if d.{{fieldVar .Name}} == nil {
		return nil
	}
	ret := make({{rawMapType .}}, d.{{fieldVar .Name}}.Len())
	d.{{fieldVar .Name}}.Range(func(key {{.MapKey}}, val {{mapValType .}}) bool {
		ret[key] = val
		return true
	})
	return ret
}

func (d *{{$.Dao.Name}}) set{{.Name}}RawMap(src {{rawMapType .}}) {
	d.{{fieldVar .Name}} = {{mapNewExpr . "len(src)"}}
	for key, val := range src {
{{- if .IsPtr}}
{{- if isNested .MapVal}}
		if val != nil {
			key, val := key, val
			val.SetNotify(func() { d.mark{{.Name}}KeyDirty(key, val) })
		}
{{- end}}
{{- end}}
		d.{{fieldVar .Name}}.Set(key, val)
	}
}
{{end}}
{{- end}}

// --- Marshal (persist fields) ---

// CaptureRollbackState is side-effect free. It includes transient and
// sync-only fields plus pending path-patch state; persistence Marshal methods
// are intentionally not reused because some of them consume patch metadata.
func (d *{{.Dao.Name}}) CaptureRollbackState() ([]byte, error) {
	type rollbackDoc struct {
		Id int64 ` + "`" + `bson:"_id"` + "`" + `
		PatchSet map[string]any ` + "`" + `bson:"_rollback_patch_set"` + "`" + `
		PatchUnset []string ` + "`" + `bson:"_rollback_patch_unset"` + "`" + `
		PatchFull map[string]bool ` + "`" + `bson:"_rollback_patch_full"` + "`" + `
{{- range .Dao.Fields}}
		{{.Name}} {{if eq .Kind 2}}{{rawMapType .}}{{else}}{{.TypeStr}}{{end}} ` + "`" + `bson:"{{bsonKey .Name}}"` + "`" + `
{{- end}}
	}
	doc := rollbackDoc{
		Id: d.id, PatchSet: d.persistPatchSet, PatchUnset: d.persistPatchUnset, PatchFull: d.persistPatchFull,
{{- range .Dao.Fields}}
{{- if eq .Kind 2}}
		{{.Name}}: d.{{mapHelperName $.Dao.Name .Name}}(),
{{- else}}
		{{.Name}}: d.{{fieldVar .Name}},
{{- end}}
{{- end}}
	}
	return bson.Marshal(doc)
}

func (d *{{.Dao.Name}}) RestoreRollbackState(raw []byte) error {
	type rollbackDoc struct {
		Id int64 ` + "`" + `bson:"_id"` + "`" + `
		PatchSet map[string]any ` + "`" + `bson:"_rollback_patch_set"` + "`" + `
		PatchUnset []string ` + "`" + `bson:"_rollback_patch_unset"` + "`" + `
		PatchFull map[string]bool ` + "`" + `bson:"_rollback_patch_full"` + "`" + `
{{- range .Dao.Fields}}
		{{.Name}} {{if eq .Kind 2}}{{rawMapType .}}{{else}}{{.TypeStr}}{{end}} ` + "`" + `bson:"{{bsonKey .Name}}"` + "`" + `
{{- end}}
	}
	var doc rollbackDoc
	if err := bson.Unmarshal(raw, &doc); err != nil { return err }
	d.id = doc.Id
	d.persistPatchSet = doc.PatchSet
	d.persistPatchUnset = doc.PatchUnset
	d.persistPatchFull = doc.PatchFull
{{- range .Dao.Fields}}
{{- if eq .Kind 2}}
	d.set{{.Name}}RawMap(doc.{{.Name}})
{{- else}}
	d.{{fieldVar .Name}} = doc.{{.Name}}
{{- end}}
{{- end}}
	d.Init()
	return nil
}

func (d *{{.Dao.Name}}) marshalCommitState() ([]byte, error) {
	doc := bson.M{
		"_id": d.id,
		"_schema": {{.Dao.Name}}SchemaVersion,
{{- range persistFields .Dao.Fields}}
{{- if eq .Kind 2}}
		"{{bsonKey .Name}}": d.{{mapHelperName $.Dao.Name .Name}}(),
{{- else}}
		"{{bsonKey .Name}}": d.{{fieldVar .Name}},
{{- end}}
{{- end}}
	}
	return bson.Marshal(doc)
}

func (d *{{.Dao.Name}}) PrepareCommit(tx *nest.RollbackTx) error {
	if tx == nil || !d.tracker.HasPersistDirty() { return nil }
	data, err := d.marshalCommitState()
	if err != nil { return fmt.Errorf("prepare commit %s/%d: %w", d.CollName(), d.id, err) }
	return tx.AddMutation(nest.EntityMutation{
		EntityID: d.id, Database: d.DbName(), DatabaseScope: uint8(d.DbScope()), Resource: d.CollName(), Version: d.tracker.Version() + 1,
		Mask: d.tracker.PersistDirtyMask(),
		Schema: {{.Dao.Name}}SchemaVersion, Codec: "bson-full-v1", Data: data,
	})
}

func (d *{{.Dao.Name}}) Marshal() []byte {
	return d.MarshalPersist(checkpoint.DirtyAll)
}

func (d *{{.Dao.Name}}) MarshalPersist(mask uint64) []byte {
	data := d.marshalPersistData(mask)
	if mask == checkpoint.DirtyAll {
		d.clearPersistPathPatch()
	}
	return data
}

func (d *{{.Dao.Name}}) marshalPersistData(mask uint64) []byte {
	_ = mask // full payload is used for inserts and safe fallback.
	doc := bson.M{
		"_id": d.id,
		"_schema": {{.Dao.Name}}SchemaVersion,
{{- range persistFields .Dao.Fields}}
{{- if eq .Kind 2}}
		"{{bsonKey .Name}}": d.{{mapHelperName $.Dao.Name .Name}}(),
{{- else}}
		"{{bsonKey .Name}}": d.{{fieldVar .Name}},
{{- end}}
{{- end}}
	}
	data, err := bson.Marshal(doc)
	if err != nil {
		// The interface has no error slot and a nil payload would be
		// persisted as silent data loss; a marshal failure here is a
		// programming error (unserializable state), so fail loudly and let
		// WAL/checkpoint recovery own the aftermath.
		panic(fmt.Errorf("{{.Dao.Name}}: marshal persist data: %w", err))
	}
	return data
}

func (d *{{.Dao.Name}}) MarshalPersistPatch(mask uint64) checkpoint.PersistPatch {
	patch := checkpoint.PersistPatch{
		Set:      make(map[string]any),
		FullData: d.marshalPersistData(checkpoint.DirtyAll),
	}
	if mask == 0 || mask == checkpoint.DirtyAll {
		d.clearPersistPathPatch()
		return patch
	}
	fullFields := make(map[string]bool)
{{- range persistFields .Dao.Fields}}
	if mask&{{fieldMaskName $.Dao.Name .Name}} != 0 {
{{- if eq .Kind 2}}
		if d.persistPatchFull["{{bsonKey .Name}}"] || !d.hasPersistPathPatch("{{bsonKey .Name}}") {
			patch.Set["{{bsonKey .Name}}"] = d.{{mapHelperName $.Dao.Name .Name}}()
			fullFields["{{bsonKey .Name}}"] = true
		}
{{- else}}
		patch.Set["{{bsonKey .Name}}"] = d.{{fieldVar .Name}}
{{- end}}
	}
{{- end}}
	d.appendPersistPathPatch(&patch, fullFields)
	if len(patch.Set) == 0 {
		patch.Set = nil
	}
	return patch
}

func (d *{{.Dao.Name}}) MarshalSync(mask uint64) []byte {
	doc := bson.M{
		"_id": d.id,
	}
{{- range syncFields .Dao.Fields}}
	if mask&{{fieldMaskName $.Dao.Name .Name}} != 0 {
{{- if eq .Kind 2}}
		doc["{{bsonKey .Name}}"] = d.{{mapHelperName $.Dao.Name .Name}}()
{{- else}}
		doc["{{bsonKey .Name}}"] = d.{{fieldVar .Name}}
{{- end}}
	}
{{- end}}
	if len(doc) == 1 {
		return nil
	}
	data, err := bson.Marshal(doc)
	if err != nil {
		// nil already means "nothing to sync"; returning it on failure would
		// silently drop a sync payload. See marshalPersistData.
		panic(fmt.Errorf("{{.Dao.Name}}: marshal sync data: %w", err))
	}
	return data
}

func (d *{{.Dao.Name}}) ApplySync(raw []byte) error {
	var doc bson.M
	if err := bson.Unmarshal(raw, &doc); err != nil {
		return err
	}
{{- range syncFields .Dao.Fields}}
	if v, ok := doc["{{bsonKey .Name}}"]; ok {
		data, err := bson.Marshal(bson.M{"v": v})
		if err != nil {
			return err
		}
		var wrap struct {
			V {{if eq .Kind 2}}{{rawMapType .}}{{else}}{{.TypeStr}}{{end}} ` + "`" + `bson:"v"` + "`" + `
		}
		if err := bson.Unmarshal(data, &wrap); err != nil {
			return err
		}
{{- if eq .Kind 2}}
		d.set{{.Name}}RawMap(wrap.V)
{{- else}}
		d.{{fieldVar .Name}} = wrap.V
{{- end}}
	}
{{- end}}
	d.Init()
	return nil
}

// --- Unmarshal ---

func (d *{{.Dao.Name}}) Unmarshal(raw []byte) error {
	type rawDoc struct {
		Id int64 ` + "`" + `bson:"_id"` + "`" + `
{{- range persistFields .Dao.Fields}}
		{{.Name}} {{if eq .Kind 2}}{{rawMapType .}}{{else}}{{.TypeStr}}{{end}} ` + "`" + `bson:"{{bsonKey .Name}}"` + "`" + `
{{- end}}
	}
	var dd rawDoc
	if err := bson.Unmarshal(raw, &dd); err != nil {
		return err
	}
	d.id = dd.Id
{{- range persistFields .Dao.Fields}}
{{- if eq .Kind 2}}
	d.set{{.Name}}RawMap(dd.{{.Name}})
{{- else}}
	d.{{fieldVar .Name}} = dd.{{.Name}}
{{- end}}
{{- end}}
	d.Init()
	return nil
}

// RestorePersisted is the single production hydration path used by the
// checkpoint aggregate repository. Migration and tracker restoration happen
// before the DAO is published through its entity.
func (d *{{.Dao.Name}}) RestorePersisted(raw []byte, schemaVersion uint32, version uint64) error {
	if schemaVersion > {{.Dao.Name}}SchemaVersion {
		return fmt.Errorf("dao {{.Dao.Name}}: stored schema %d is newer than runtime schema %d", schemaVersion, {{.Dao.Name}}SchemaVersion)
	}
	var err error
	if schemaVersion < {{.Dao.Name}}SchemaVersion {
		raw, err = d.Migrate(raw, schemaVersion)
		if err != nil {
			return fmt.Errorf("dao {{.Dao.Name}}: migrate schema %d to %d: %w", schemaVersion, {{.Dao.Name}}SchemaVersion, err)
		}
	}
	if err := d.Unmarshal(raw); err != nil {
		return err
	}
	d.tracker.SetVersion(version)
	d.CleanDirty()
	return nil
}

// compile-time import guards
var (
	_ = checkpoint.DirtyTracker{}
	_ = bson.M{}
)
`
