// Code generated by tool/entity. DO NOT EDIT.
package testdata

import (
	"sync"

	"github.com/tjbdwanghaibo/cube-core/checkpoint"
	"github.com/tjbdwanghaibo/cube-core/entity"
	"github.com/tjbdwanghaibo/cube/game/clientsync"
)

var registerEntityOnce sync.Once

// RegisterEntity registers the Player entity builder.
func RegisterEntity() {
	registerEntityOnce.Do(func() {
		entity.RegisterEntityBuilder(&entity.EntityBuilderParam{
			Category: entity.MustEntityCategoryOfKind(EntityKindPlayer),
			Kind:     EntityKindPlayer,
			Builder: func(param *entity.EntityCreateParam) (entity.IThreadSafeEntity, error) {
				return NewPlayer(param)
			},
			DaoBuilders: []entity.DaoBuilderFunc{
				func() entity.DaoInterface { return NewPlayerDao() },
				func() entity.DaoInterface { return NewMailDao() },
			},
			NoPersist:    false,
			RemotePolicy: entity.RemotePolicyNone,
			Lifetime:     entity.EntityLifetimePersistedHotCold,
			Sync: entity.EntitySyncBuilderParam{
				Enabled:              true,
				Topic:                "SyncTopicPlayer",
				FlushPolicy:          entity.SyncFlushOnEntityRelease,
				PackerFactory:        clientsync.PlayerPacker,
				SubjectPackerFactory: clientsync.PlayerSubjectPacker,
			},
		})
	})
}

func NewPlayer(param *entity.EntityCreateParam) (*Player, error) {
	e := &Player{}
	if err := param.NormalizeID(EntityKindPlayer); err != nil {
		return nil, err
	}

	// EntityBase
	e.EntityBase = entity.NewEntityBaseWithMutex(param.Id, param.Category, false, param.Mutex, param.Kind)
	e.EntityBase.SetHooks(e.generatedOnClear, e.generatedOnDestroy)

	// ComponentManager
	e.ComponentManager = entity.NewComponentManager()

	// DaoManager
	e.DaoManager = entity.NewDaoManager()

	// DAO: dao
	if raw, ok := param.Dao[PlayerDaoCollection]; ok {
		e.dao = raw.(*PlayerDao)
	} else {
		e.dao = NewPlayerDao()
		e.dao.SetId(param.StorageID())
	}
	if e.dao != nil {
		e.DaoManager.Set(PlayerDaoCollection, e.dao)
	}

	// DAO: mail
	if raw, ok := param.Dao[MailDaoCollection]; ok {
		e.mail = raw.(*MailDao)
	} else {
		e.mail = NewMailDao()
		e.mail.SetId(param.StorageID())
	}
	if e.mail != nil {
		e.DaoManager.Set(MailDaoCollection, e.mail)
	}

	// Component: bag
	if comp, err := entity.CreateComponent(CompTypeBag, e, param); err != nil {
		return nil, err
	} else {
		e.bag = comp.(*BagComponent)
	}
	e.ComponentManager.Set(CompTypeBag, e.bag)

	// Component: battle
	if comp, err := entity.CreateComponent(CompTypeBattle, e, param); err != nil {
		return nil, err
	} else {
		e.battle = comp.(*BattleComponent)
	}
	e.ComponentManager.Set(CompTypeBattle, e.battle)

	// Initialize all components in dependency order
	if err := e.ComponentManager.InitAll(param, param.IsCreate); err != nil {
		return nil, err
	}

	return e, nil
}
func (e *Player) Base() *entity.EntityBase { return e.EntityBase }

func (e *Player) BagComp() *BagComponent { return e.bag }

func (e *Player) BattleComp() *BattleComponent { return e.battle }

func (e *Player) Dao() *PlayerDao { return e.dao }

func (e *Player) MailDao() *MailDao { return e.mail }

func (e *Player) generatedOnClear() {
	e.ComponentManager.Clear()
	e.DaoManager.Clear()
	e.bag = nil
	e.battle = nil
	e.dao = nil
	e.mail = nil
}

func (e *Player) generatedOnDestroy(reason entity.EntityDestroyReason) {
	e.ComponentManager.DestroyAll(reason)
}

// Snapshot produces save items for the checkpoint system.
// Called under entity lock (guard release).
func (e *Player) Snapshot() []checkpoint.SaveItem {
	var items []checkpoint.SaveItem
	if e.dao != nil {
		if mask := e.dao.DirtyTracker().TakePersistDirty(); mask != 0 {
			ver := e.dao.DirtyTracker().IncVersion()
			data := e.dao.MarshalPersist(mask)
			mode := checkpoint.SaveModeFull
			var patch checkpoint.PersistPatch
			if mask != checkpoint.DirtyAll {
				if patcher, ok := any(e.dao).(checkpoint.PersistPatcher); ok {
					patch = patcher.MarshalPersistPatch(mask)
					if !patch.Empty() {
						if len(patch.FullData) == 0 {
							patch.FullData = data
						}
						mode = checkpoint.SaveModePatch
					}
				}
			}
			items = append(items, checkpoint.SaveItem{
				Db:         e.dao.DbName(),
				DbScope:    checkpoint.ResolveDatabaseScope(e.dao),
				Collection: e.dao.CollName(),
				ID:         e.dao.Id(),
				Version:    ver,
				Mask:       mask,
				Mode:       mode,
				Data:       data,
				Patch:      patch,
				Tracker:    e.dao.DirtyTracker(),
			})
		}
	}
	if e.mail != nil {
		if mask := e.mail.DirtyTracker().TakePersistDirty(); mask != 0 {
			ver := e.mail.DirtyTracker().IncVersion()
			data := e.mail.MarshalPersist(mask)
			mode := checkpoint.SaveModeFull
			var patch checkpoint.PersistPatch
			if mask != checkpoint.DirtyAll {
				if patcher, ok := any(e.mail).(checkpoint.PersistPatcher); ok {
					patch = patcher.MarshalPersistPatch(mask)
					if !patch.Empty() {
						if len(patch.FullData) == 0 {
							patch.FullData = data
						}
						mode = checkpoint.SaveModePatch
					}
				}
			}
			items = append(items, checkpoint.SaveItem{
				Db:         e.mail.DbName(),
				DbScope:    checkpoint.ResolveDatabaseScope(e.mail),
				Collection: e.mail.CollName(),
				ID:         e.mail.Id(),
				Version:    ver,
				Mask:       mask,
				Mode:       mode,
				Data:       data,
				Patch:      patch,
				Tracker:    e.mail.DirtyTracker(),
			})
		}
	}
	return items
}

// RemoveSnapshot describes all persistent DAO targets independently of dirty
// state. Checkpoint writes durable delete tombstones before backend removal.
func (e *Player) RemoveSnapshot() []checkpoint.SaveItem {
	items := make([]checkpoint.SaveItem, 0, 2)
	if e.dao != nil {
		items = append(items, checkpoint.SaveItem{
			Db: e.dao.DbName(), DbScope: checkpoint.ResolveDatabaseScope(e.dao),
			Collection: e.dao.CollName(), ID: e.dao.Id(),
			Version: e.dao.DirtyTracker().IncVersion(), Deleted: true,
		})
	}
	if e.mail != nil {
		items = append(items, checkpoint.SaveItem{
			Db: e.mail.DbName(), DbScope: checkpoint.ResolveDatabaseScope(e.mail),
			Collection: e.mail.CollName(), ID: e.mail.Id(),
			Version: e.mail.DirtyTracker().IncVersion(), Deleted: true,
		})
	}
	return items
}
