// Code generated by tool/dao. DO NOT EDIT.
package testdata

import (
	"fmt"
	"github.com/tjbdwanghaibo/cube-core/checkpoint"
	"github.com/tjbdwanghaibo/cube-core/entity"
	fmap "github.com/tjbdwanghaibo/cube-core/map"
	"github.com/tjbdwanghaibo/cube-core/migration"
	"github.com/tjbdwanghaibo/cube-core/nest"
	"go.mongodb.org/mongo-driver/v2/bson"
)

// VarietyDao is the DAO for collection "varieties".
type VarietyDao struct {
	id                int64
	tracker           checkpoint.DirtyTracker
	persistPatchSet   map[string]any
	persistPatchUnset []string
	persistPatchFull  map[string]bool
	persistOnly       int64
	syncOnly          int64
	neither           int64
	fastItems         *fmap.FastMap[int64, int32]
	shardedTags       *fmap.ShardedSafeMap[int32, string]
}

// Ensure interface compliance.
var _ entity.DaoInterface = (*VarietyDao)(nil)
var _ nest.RollbackSnapshotter = (*VarietyDao)(nil)
var _ nest.CommitParticipant = (*VarietyDao)(nil)

const (
	VarietyDaoDBName               = "game"
	VarietyDaoCollection           = "varieties"
	VarietyDaoSchemaVersion uint32 = 1
)

// NewVarietyDao creates a new VarietyDao instance with initialized maps/slices.
func NewVarietyDao() *VarietyDao {
	d := &VarietyDao{}
	d.fastItems = fmap.NewFastMap[int64, int32](0, fmap.HashInteger[int64])
	d.shardedTags = fmap.NewShardedSafeMap[int32, string](32, fmap.HashInteger[int32])
	return d
}

func (d *VarietyDao) Id() int64                         { return d.id }
func (d *VarietyDao) SetId(id int64)                    { d.id = id }
func (d *VarietyDao) DbName() string                    { return VarietyDaoDBName }
func (d *VarietyDao) DbScope() checkpoint.DatabaseScope { return checkpoint.DatabaseScopeGlobal }
func (d *VarietyDao) CollName() string                  { return VarietyDaoCollection }
func (d *VarietyDao) SchemaVersion() uint32             { return VarietyDaoSchemaVersion }
func (d *VarietyDao) Migrate(raw []byte, from uint32) ([]byte, error) {
	return migration.MigrateDAO(d.CollName(), raw, from, VarietyDaoSchemaVersion)
}
func (d *VarietyDao) Dirty() entity.IDirty                   { return &d.tracker }
func (d *VarietyDao) CleanDirty()                            { d.tracker.SelfClean(); d.clearPersistPathPatch() }
func (d *VarietyDao) DirtyTracker() *checkpoint.DirtyTracker { return &d.tracker }

const (
	varietyDaoFieldPersistOnly uint64 = 1 << iota
	varietyDaoFieldSyncOnly    uint64 = 1 << iota
	varietyDaoFieldNeither     uint64 = 1 << iota
	varietyDaoFieldFastItems   uint64 = 1 << iota
	varietyDaoFieldShardedTags uint64 = 1 << iota
)

func (d *VarietyDao) markPersistOnlyDirty() {
	d.tracker.MarkScope(checkpoint.DirtyPersist, varietyDaoFieldPersistOnly)
}

func (d *VarietyDao) markSyncOnlyDirty() {
	d.tracker.MarkScope(checkpoint.DirtySync, varietyDaoFieldSyncOnly)
}

func (d *VarietyDao) markNeitherDirty() {
	d.tracker.MarkScope(0, varietyDaoFieldNeither)
}

func (d *VarietyDao) markFastItemsDirty() {
	d.tracker.MarkScope(checkpoint.DirtyPersist|checkpoint.DirtySync, varietyDaoFieldFastItems)
}

func (d *VarietyDao) markShardedTagsDirty() {
	d.tracker.MarkScope(checkpoint.DirtyPersist|checkpoint.DirtySync, varietyDaoFieldShardedTags)
}

func (d *VarietyDao) recordPersistPatchSet(field string, path string, value any) {
	if path == "" {
		d.recordPersistPatchFull(field)
		return
	}
	if d.persistPatchSet == nil {
		d.persistPatchSet = make(map[string]any)
	}
	d.persistPatchSet[path] = value
	for i := 0; i < len(d.persistPatchUnset); {
		if d.persistPatchUnset[i] == path {
			d.persistPatchUnset = append(d.persistPatchUnset[:i], d.persistPatchUnset[i+1:]...)
			continue
		}
		i++
	}
}

func (d *VarietyDao) recordPersistPatchUnset(field string, path string) {
	if path == "" {
		d.recordPersistPatchFull(field)
		return
	}
	delete(d.persistPatchSet, path)
	d.persistPatchUnset = append(d.persistPatchUnset, path)
}

func (d *VarietyDao) recordPersistPatchFull(field string) {
	if field == "" {
		return
	}
	if d.persistPatchFull == nil {
		d.persistPatchFull = make(map[string]bool)
	}
	d.persistPatchFull[field] = true
}

func (d *VarietyDao) hasPersistPathPatch(field string) bool {
	return checkpoint.PersistPatchHasPath(d.persistPatchSet, d.persistPatchUnset, field)
}

func (d *VarietyDao) appendPersistPathPatch(patch *checkpoint.PersistPatch, fullFields map[string]bool) {
	for path, value := range d.persistPatchSet {
		if checkpoint.PersistPatchPathCovered(path, fullFields) {
			continue
		}
		patch.Set[path] = value
	}
	for _, path := range d.persistPatchUnset {
		if checkpoint.PersistPatchPathCovered(path, fullFields) {
			continue
		}
		patch.Unset = append(patch.Unset, path)
	}
	d.clearPersistPathPatch()
}

func (d *VarietyDao) clearPersistPathPatch() {
	d.persistPatchSet = nil
	d.persistPatchUnset = nil
	d.persistPatchFull = nil
}

func (d *VarietyDao) markFastItemsKeyDirty(key int64, val int32) {
	if path, ok := checkpoint.MapPatchPath("fast_items", key); ok {
		d.recordPersistPatchSet("fast_items", path, val)
	} else {
		d.recordPersistPatchFull("fast_items")
	}
	d.markFastItemsDirty()
}

func (d *VarietyDao) markFastItemsKeyDeleted(key int64) {
	if path, ok := checkpoint.MapPatchPath("fast_items", key); ok {
		d.recordPersistPatchUnset("fast_items", path)
	} else {
		d.recordPersistPatchFull("fast_items")
	}
	d.markFastItemsDirty()
}

func (d *VarietyDao) markShardedTagsKeyDirty(key int32, val string) {
	if path, ok := checkpoint.MapPatchPath("sharded_tags", key); ok {
		d.recordPersistPatchSet("sharded_tags", path, val)
	} else {
		d.recordPersistPatchFull("sharded_tags")
	}
	d.markShardedTagsDirty()
}

func (d *VarietyDao) markShardedTagsKeyDeleted(key int32) {
	if path, ok := checkpoint.MapPatchPath("sharded_tags", key); ok {
		d.recordPersistPatchUnset("sharded_tags", path)
	} else {
		d.recordPersistPatchFull("sharded_tags")
	}
	d.markShardedTagsDirty()
}

// Init wires dirty callbacks for nested structs and map values.
func (d *VarietyDao) Init() {
}

// --- Accessors ---

func (d *VarietyDao) GetPersistOnly() int64 { return d.persistOnly }

func (d *VarietyDao) GetSyncOnly() int64 { return d.syncOnly }

func (d *VarietyDao) GetNeither() int64 { return d.neither }

// --- Mutators ---

// recordUndo / recordUndoToken register the inverse operation and panic when
// registration fails: continuing would let the mutation escape rollback
// coverage, silently breaking the transaction guarantee.
func (d *VarietyDao) recordUndo(tx *nest.RollbackTx, field uint64, fn func() error) {
	if err := tx.RecordUndo(d, field, fn); err != nil {
		panic(fmt.Errorf("VarietyDao: record undo: %w", err))
	}
}

func (d *VarietyDao) recordUndoToken(tx *nest.RollbackTx, field uint64, token any, fn func() error) {
	if err := tx.RecordUndoToken(d, field, token, fn); err != nil {
		panic(fmt.Errorf("VarietyDao: record undo: %w", err))
	}
}

func (d *VarietyDao) SetPersistOnly(v int64) {
	if d.persistOnly != v {
		if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
			old := d.persistOnly
			d.recordUndo(tx, varietyDaoFieldPersistOnly, func() error { d.persistOnly = old; return nil })
		}
		d.persistOnly = v
		d.markPersistOnlyDirty()
	}
}

func (d *VarietyDao) SetSyncOnly(v int64) {
	if d.syncOnly != v {
		if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
			old := d.syncOnly
			d.recordUndo(tx, varietyDaoFieldSyncOnly, func() error { d.syncOnly = old; return nil })
		}
		d.syncOnly = v
		d.markSyncOnlyDirty()
	}
}

func (d *VarietyDao) GetFastItems(key int64) (int32, bool) {
	if d.fastItems == nil {
		var zero int32
		return zero, false
	}
	return d.fastItems.Get(key)
}

func (d *VarietyDao) SetFastItems(key int64, val int32) {
	if d.fastItems == nil {
		d.fastItems = fmap.NewFastMap[int64, int32](0, fmap.HashInteger[int64])
	}
	if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
		old, existed := d.fastItems.Get(key)
		d.recordUndoToken(tx, varietyDaoFieldFastItems, key, func() error {
			if existed {
				d.fastItems.Set(key, old)
			} else {
				d.fastItems.Delete(key)
			}
			d.Init()
			return nil
		})
	}
	d.fastItems.Set(key, val)
	d.markFastItemsKeyDirty(key, val)
}

func (d *VarietyDao) DelFastItems(key int64) {
	if d.fastItems == nil {
		return
	}
	if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
		old, existed := d.fastItems.Get(key)
		d.recordUndoToken(tx, varietyDaoFieldFastItems, key, func() error {
			if existed {
				d.fastItems.Set(key, old)
				d.Init()
			}
			return nil
		})
	}
	if d.fastItems.Delete(key) {
		d.markFastItemsKeyDeleted(key)
	}
}

func (d *VarietyDao) RangeFastItems(f func(key int64, val int32) bool) {
	if d.fastItems == nil || f == nil {
		return
	}
	d.fastItems.Range(f)
}

func (d *VarietyDao) FastItemsLen() int {
	if d.fastItems == nil {
		return 0
	}
	return d.fastItems.Len()
}

func (d *VarietyDao) GetShardedTags(key int32) (string, bool) {
	if d.shardedTags == nil {
		var zero string
		return zero, false
	}
	return d.shardedTags.Get(key)
}

func (d *VarietyDao) SetShardedTags(key int32, val string) {
	if d.shardedTags == nil {
		d.shardedTags = fmap.NewShardedSafeMap[int32, string](32, fmap.HashInteger[int32])
	}
	if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
		old, existed := d.shardedTags.Get(key)
		d.recordUndoToken(tx, varietyDaoFieldShardedTags, key, func() error {
			if existed {
				d.shardedTags.Set(key, old)
			} else {
				d.shardedTags.Delete(key)
			}
			d.Init()
			return nil
		})
	}
	d.shardedTags.Set(key, val)
	d.markShardedTagsKeyDirty(key, val)
}

func (d *VarietyDao) DelShardedTags(key int32) {
	if d.shardedTags == nil {
		return
	}
	if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
		old, existed := d.shardedTags.Get(key)
		d.recordUndoToken(tx, varietyDaoFieldShardedTags, key, func() error {
			if existed {
				d.shardedTags.Set(key, old)
				d.Init()
			}
			return nil
		})
	}
	if d.shardedTags.Delete(key) {
		d.markShardedTagsKeyDeleted(key)
	}
}

func (d *VarietyDao) RangeShardedTags(f func(key int32, val string) bool) {
	if d.shardedTags == nil || f == nil {
		return
	}
	d.shardedTags.Range(f)
}

func (d *VarietyDao) ShardedTagsLen() int {
	if d.shardedTags == nil {
		return 0
	}
	return d.shardedTags.Len()
}

func (d *VarietyDao) varietyDaoFastItemsRawMap() map[int64]int32 {
	if d.fastItems == nil {
		return nil
	}
	ret := make(map[int64]int32, d.fastItems.Len())
	d.fastItems.Range(func(key int64, val int32) bool {
		ret[key] = val
		return true
	})
	return ret
}

func (d *VarietyDao) setFastItemsRawMap(src map[int64]int32) {
	d.fastItems = fmap.NewFastMap[int64, int32](len(src), fmap.HashInteger[int64])
	for key, val := range src {
		d.fastItems.Set(key, val)
	}
}

func (d *VarietyDao) varietyDaoShardedTagsRawMap() map[int32]string {
	if d.shardedTags == nil {
		return nil
	}
	ret := make(map[int32]string, d.shardedTags.Len())
	d.shardedTags.Range(func(key int32, val string) bool {
		ret[key] = val
		return true
	})
	return ret
}

func (d *VarietyDao) setShardedTagsRawMap(src map[int32]string) {
	d.shardedTags = fmap.NewShardedSafeMap[int32, string](32, fmap.HashInteger[int32])
	for key, val := range src {
		d.shardedTags.Set(key, val)
	}
}

// --- Marshal (persist fields) ---

// CaptureRollbackState is side-effect free. It includes transient and
// sync-only fields plus pending path-patch state; persistence Marshal methods
// are intentionally not reused because some of them consume patch metadata.
func (d *VarietyDao) CaptureRollbackState() ([]byte, error) {
	type rollbackDoc struct {
		Id          int64            `bson:"_id"`
		PatchSet    map[string]any   `bson:"_rollback_patch_set"`
		PatchUnset  []string         `bson:"_rollback_patch_unset"`
		PatchFull   map[string]bool  `bson:"_rollback_patch_full"`
		PersistOnly int64            `bson:"persist_only"`
		SyncOnly    int64            `bson:"sync_only"`
		Neither     int64            `bson:"neither"`
		FastItems   map[int64]int32  `bson:"fast_items"`
		ShardedTags map[int32]string `bson:"sharded_tags"`
	}
	doc := rollbackDoc{
		Id: d.id, PatchSet: d.persistPatchSet, PatchUnset: d.persistPatchUnset, PatchFull: d.persistPatchFull,
		PersistOnly: d.persistOnly,
		SyncOnly:    d.syncOnly,
		Neither:     d.neither,
		FastItems:   d.varietyDaoFastItemsRawMap(),
		ShardedTags: d.varietyDaoShardedTagsRawMap(),
	}
	return bson.Marshal(doc)
}

func (d *VarietyDao) RestoreRollbackState(raw []byte) error {
	type rollbackDoc struct {
		Id          int64            `bson:"_id"`
		PatchSet    map[string]any   `bson:"_rollback_patch_set"`
		PatchUnset  []string         `bson:"_rollback_patch_unset"`
		PatchFull   map[string]bool  `bson:"_rollback_patch_full"`
		PersistOnly int64            `bson:"persist_only"`
		SyncOnly    int64            `bson:"sync_only"`
		Neither     int64            `bson:"neither"`
		FastItems   map[int64]int32  `bson:"fast_items"`
		ShardedTags map[int32]string `bson:"sharded_tags"`
	}
	var doc rollbackDoc
	if err := bson.Unmarshal(raw, &doc); err != nil {
		return err
	}
	d.id = doc.Id
	d.persistPatchSet = doc.PatchSet
	d.persistPatchUnset = doc.PatchUnset
	d.persistPatchFull = doc.PatchFull
	d.persistOnly = doc.PersistOnly
	d.syncOnly = doc.SyncOnly
	d.neither = doc.Neither
	d.setFastItemsRawMap(doc.FastItems)
	d.setShardedTagsRawMap(doc.ShardedTags)
	d.Init()
	return nil
}

func (d *VarietyDao) marshalCommitState() ([]byte, error) {
	doc := bson.M{
		"_id":          d.id,
		"_schema":      VarietyDaoSchemaVersion,
		"persist_only": d.persistOnly,
		"fast_items":   d.varietyDaoFastItemsRawMap(),
		"sharded_tags": d.varietyDaoShardedTagsRawMap(),
	}
	return bson.Marshal(doc)
}

func (d *VarietyDao) PrepareCommit(tx *nest.RollbackTx) error {
	if tx == nil || !d.tracker.HasPersistDirty() {
		return nil
	}
	data, err := d.marshalCommitState()
	if err != nil {
		return fmt.Errorf("prepare commit %s/%d: %w", d.CollName(), d.id, err)
	}
	return tx.AddMutation(nest.EntityMutation{
		EntityID: d.id, Database: d.DbName(), DatabaseScope: uint8(d.DbScope()), Resource: d.CollName(), Version: d.tracker.Version() + 1,
		Mask:   d.tracker.PersistDirtyMask(),
		Schema: VarietyDaoSchemaVersion, Codec: "bson-full-v1", Data: data,
	})
}

func (d *VarietyDao) Marshal() []byte {
	return d.MarshalPersist(checkpoint.DirtyAll)
}

func (d *VarietyDao) MarshalPersist(mask uint64) []byte {
	data := d.marshalPersistData(mask)
	if mask == checkpoint.DirtyAll {
		d.clearPersistPathPatch()
	}
	return data
}

func (d *VarietyDao) marshalPersistData(mask uint64) []byte {
	_ = mask // full payload is used for inserts and safe fallback.
	doc := bson.M{
		"_id":          d.id,
		"_schema":      VarietyDaoSchemaVersion,
		"persist_only": d.persistOnly,
		"fast_items":   d.varietyDaoFastItemsRawMap(),
		"sharded_tags": d.varietyDaoShardedTagsRawMap(),
	}
	data, err := bson.Marshal(doc)
	if err != nil {
		// The interface has no error slot and a nil payload would be
		// persisted as silent data loss; a marshal failure here is a
		// programming error (unserializable state), so fail loudly and let
		// WAL/checkpoint recovery own the aftermath.
		panic(fmt.Errorf("VarietyDao: marshal persist data: %w", err))
	}
	return data
}

func (d *VarietyDao) MarshalPersistPatch(mask uint64) checkpoint.PersistPatch {
	patch := checkpoint.PersistPatch{
		Set:      make(map[string]any),
		FullData: d.marshalPersistData(checkpoint.DirtyAll),
	}
	if mask == 0 || mask == checkpoint.DirtyAll {
		d.clearPersistPathPatch()
		return patch
	}
	fullFields := make(map[string]bool)
	if mask&varietyDaoFieldPersistOnly != 0 {
		patch.Set["persist_only"] = d.persistOnly
	}
	if mask&varietyDaoFieldFastItems != 0 {
		if d.persistPatchFull["fast_items"] || !d.hasPersistPathPatch("fast_items") {
			patch.Set["fast_items"] = d.varietyDaoFastItemsRawMap()
			fullFields["fast_items"] = true
		}
	}
	if mask&varietyDaoFieldShardedTags != 0 {
		if d.persistPatchFull["sharded_tags"] || !d.hasPersistPathPatch("sharded_tags") {
			patch.Set["sharded_tags"] = d.varietyDaoShardedTagsRawMap()
			fullFields["sharded_tags"] = true
		}
	}
	d.appendPersistPathPatch(&patch, fullFields)
	if len(patch.Set) == 0 {
		patch.Set = nil
	}
	return patch
}

func (d *VarietyDao) MarshalSync(mask uint64) []byte {
	doc := bson.M{
		"_id": d.id,
	}
	if mask&varietyDaoFieldSyncOnly != 0 {
		doc["sync_only"] = d.syncOnly
	}
	if mask&varietyDaoFieldFastItems != 0 {
		doc["fast_items"] = d.varietyDaoFastItemsRawMap()
	}
	if mask&varietyDaoFieldShardedTags != 0 {
		doc["sharded_tags"] = d.varietyDaoShardedTagsRawMap()
	}
	if len(doc) == 1 {
		return nil
	}
	data, err := bson.Marshal(doc)
	if err != nil {
		// nil already means "nothing to sync"; returning it on failure would
		// silently drop a sync payload. See marshalPersistData.
		panic(fmt.Errorf("VarietyDao: marshal sync data: %w", err))
	}
	return data
}

func (d *VarietyDao) ApplySync(raw []byte) error {
	var doc bson.M
	if err := bson.Unmarshal(raw, &doc); err != nil {
		return err
	}
	if v, ok := doc["sync_only"]; ok {
		data, err := bson.Marshal(bson.M{"v": v})
		if err != nil {
			return err
		}
		var wrap struct {
			V int64 `bson:"v"`
		}
		if err := bson.Unmarshal(data, &wrap); err != nil {
			return err
		}
		d.syncOnly = wrap.V
	}
	if v, ok := doc["fast_items"]; ok {
		data, err := bson.Marshal(bson.M{"v": v})
		if err != nil {
			return err
		}
		var wrap struct {
			V map[int64]int32 `bson:"v"`
		}
		if err := bson.Unmarshal(data, &wrap); err != nil {
			return err
		}
		d.setFastItemsRawMap(wrap.V)
	}
	if v, ok := doc["sharded_tags"]; ok {
		data, err := bson.Marshal(bson.M{"v": v})
		if err != nil {
			return err
		}
		var wrap struct {
			V map[int32]string `bson:"v"`
		}
		if err := bson.Unmarshal(data, &wrap); err != nil {
			return err
		}
		d.setShardedTagsRawMap(wrap.V)
	}
	d.Init()
	return nil
}

// --- Unmarshal ---

func (d *VarietyDao) Unmarshal(raw []byte) error {
	type rawDoc struct {
		Id          int64            `bson:"_id"`
		PersistOnly int64            `bson:"persist_only"`
		FastItems   map[int64]int32  `bson:"fast_items"`
		ShardedTags map[int32]string `bson:"sharded_tags"`
	}
	var dd rawDoc
	if err := bson.Unmarshal(raw, &dd); err != nil {
		return err
	}
	d.id = dd.Id
	d.persistOnly = dd.PersistOnly
	d.setFastItemsRawMap(dd.FastItems)
	d.setShardedTagsRawMap(dd.ShardedTags)
	d.Init()
	return nil
}

// RestorePersisted is the single production hydration path used by the
// checkpoint aggregate repository. Migration and tracker restoration happen
// before the DAO is published through its entity.
func (d *VarietyDao) RestorePersisted(raw []byte, schemaVersion uint32, version uint64) error {
	if schemaVersion > VarietyDaoSchemaVersion {
		return fmt.Errorf("dao VarietyDao: stored schema %d is newer than runtime schema %d", schemaVersion, VarietyDaoSchemaVersion)
	}
	var err error
	if schemaVersion < VarietyDaoSchemaVersion {
		raw, err = d.Migrate(raw, schemaVersion)
		if err != nil {
			return fmt.Errorf("dao VarietyDao: migrate schema %d to %d: %w", schemaVersion, VarietyDaoSchemaVersion, err)
		}
	}
	if err := d.Unmarshal(raw); err != nil {
		return err
	}
	d.tracker.SetVersion(version)
	d.CleanDirty()
	return nil
}

// compile-time import guards
var (
	_ = checkpoint.DirtyTracker{}
	_ = bson.M{}
)
