// Code generated by tool/dao. DO NOT EDIT.
package testdata

// daoMapDocs maps conv over src; nil stays nil so an absent map is not
// persisted as an empty one.
func daoMapDocs[K comparable, V, D any](src map[K]V, conv func(V) D) map[K]D {
	if src == nil {
		return nil
	}
	out := make(map[K]D, len(src))
	for key, val := range src {
		out[key] = conv(val)
	}
	return out
}

// daoSliceDocs maps conv over src; nil stays nil.
func daoSliceDocs[V, D any](src []V, conv func(V) D) []D {
	if src == nil {
		return nil
	}
	out := make([]D, len(src))
	for i, val := range src {
		out[i] = conv(val)
	}
	return out
}
