// Code generated by tool/dao. DO NOT EDIT.
package testdata

import (
	"fmt"

	"github.com/tjbdwanghaibo/roost-core/dataengine"
	"github.com/tjbdwanghaibo/roost-core/nest"
	"go.mongodb.org/mongo-driver/v2/bson"
)

// GemInfo is a nested struct with dirty propagation.
//
// The hook is excluded from every codec: it is runtime wiring, not state, and
// an exported embedded struct with no exported fields would otherwise be
// written as an empty "dirtyhook" sub-document (U-0224).
type GemInfo struct {
	dataengine.DirtyHook `bson:"-" json:"-"`
	id                   int32
	level                int32
}

// --- wire form (persistence, rollback capture, sync) ---
//
// The fields are unexported so every mutation goes through the setters below
// — that is what makes dirty tracking and undo impossible to bypass — and the
// reflection-based codec cannot see unexported fields. GemInfo therefore
// has a WIRE FORM, gemInfoBSONDoc, with exported fields: the
// parent DAO places that into its own document and reflection encodes it
// inline, with no per-value Marshaler round trip (U-0224 and its follow-up:
// the bson.Marshaler route cost about four allocations per nested value).
// MarshalBSON / UnmarshalBSON are kept for a GemInfo encoded on its own.
type gemInfoBSONDoc struct {
	ID    int32 `bson:"id"`
	Level int32 `bson:"level"`
}

// bsonDoc is the value receiver on purpose: containers hold GemInfo values
// as well as pointers, and a method expression GemInfo.bsonDoc maps over both.
func (s GemInfo) bsonDoc() gemInfoBSONDoc {
	return gemInfoBSONDoc{
		ID:    s.id,
		Level: s.level,
	}
}

func (s *GemInfo) setBSONDoc(doc gemInfoBSONDoc) {
	s.id = doc.ID
	s.level = doc.Level
}

func gemInfoFromBSONDoc(doc gemInfoBSONDoc) GemInfo {
	var s GemInfo
	s.setBSONDoc(doc)
	return s
}

func gemInfoPtrBSONDoc(v *GemInfo) *gemInfoBSONDoc {
	if v == nil {
		return nil
	}
	doc := v.bsonDoc()
	return &doc
}

func gemInfoPtrFromBSONDoc(doc *gemInfoBSONDoc) *GemInfo {
	if doc == nil {
		return nil
	}
	v := gemInfoFromBSONDoc(*doc)
	return &v
}

func (s GemInfo) MarshalBSON() ([]byte, error) { return bson.Marshal(s.bsonDoc()) }

func (s *GemInfo) UnmarshalBSON(raw []byte) error {
	var doc gemInfoBSONDoc
	if err := bson.Unmarshal(raw, &doc); err != nil {
		return err
	}
	s.setBSONDoc(doc)
	return nil
}

func (s *GemInfo) GetID() int32 { return s.id }

func (s *GemInfo) GetLevel() int32 { return s.level }

func (s *GemInfo) SetID(v int32) {
	if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
		old := s.id
		if err := tx.RecordUndo(s, uint64(0), func() error {
			s.id = old
			return nil
		}); err != nil {
			// A mutation without undo coverage silently breaks rollback;
			// failing loudly matches the generated DAO setters.
			panic(fmt.Errorf("GemInfo: record undo: %w", err))
		}
	}
	if s.id != v {
		s.id = v
		s.Mark()
	}
}

func (s *GemInfo) SetLevel(v int32) {
	if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
		old := s.level
		if err := tx.RecordUndo(s, uint64(1), func() error {
			s.level = old
			return nil
		}); err != nil {
			// A mutation without undo coverage silently breaks rollback;
			// failing loudly matches the generated DAO setters.
			panic(fmt.Errorf("GemInfo: record undo: %w", err))
		}
	}
	if s.level != v {
		s.level = v
		s.Mark()
	}
}
