// Code generated by tool/dao. DO NOT EDIT.
package testdata

import (
	"fmt"
	"github.com/tjbdwanghaibo/cube-core/dataengine"
	"github.com/tjbdwanghaibo/cube-core/entity"
	"github.com/tjbdwanghaibo/cube-core/migration"
	"github.com/tjbdwanghaibo/cube-core/nest"
	fmap "github.com/tjbdwanghaibo/cube-core/safemap"
	"go.mongodb.org/mongo-driver/v2/bson"
	"sort"
)

// HeroDao is the DAO for collection "heroes".
type HeroDao struct {
	id      int64
	tracker dataengine.Tracker
	name    string
	level   int32
	exp     int64
	loginAt int64
	items   *fmap.SmallSafeMap[int64, int32]
	friends []int64
	pos     Position
	equips  *fmap.SmallSafeMap[int64, *EquipInfo]
}

// Ensure interface compliance.
var _ entity.DaoInterface = (*HeroDao)(nil)
var _ nest.RollbackSnapshotter = (*HeroDao)(nil)
var _ nest.MutationParticipant = (*HeroDao)(nil)

const (
	HeroDaoDBName               = "game"
	HeroDaoCollection           = "heroes"
	HeroDaoSchemaVersion uint32 = 1
)

// NewHeroDao creates a new HeroDao instance with initialized maps/slices.
func NewHeroDao() *HeroDao {
	d := &HeroDao{}
	d.items = fmap.NewSmallSafeMap[int64, int32](0)
	d.equips = fmap.NewSmallSafeMap[int64, *EquipInfo](0)
	return d
}

func (d *HeroDao) Id() int64                         { return d.id }
func (d *HeroDao) SetId(id int64)                    { d.id = id }
func (d *HeroDao) DbName() string                    { return HeroDaoDBName }
func (d *HeroDao) DbScope() dataengine.DatabaseScope { return dataengine.DatabaseServer }
func (d *HeroDao) CollName() string                  { return HeroDaoCollection }
func (d *HeroDao) SchemaVersion() uint32             { return HeroDaoSchemaVersion }
func (d *HeroDao) Migrate(raw []byte, from uint32) ([]byte, error) {
	return migration.MigrateDAO(d.CollName(), raw, from, HeroDaoSchemaVersion)
}
func (d *HeroDao) Dirty() entity.IDirty              { return &d.tracker }
func (d *HeroDao) CleanDirty()                       { d.tracker.SelfClean() }
func (d *HeroDao) DirtyTracker() *dataengine.Tracker { return &d.tracker }

const (
	heroDaoFieldName    uint64 = 1 << iota
	heroDaoFieldLevel   uint64 = 1 << iota
	heroDaoFieldExp     uint64 = 1 << iota
	heroDaoFieldLoginAt uint64 = 1 << iota
	heroDaoFieldItems   uint64 = 1 << iota
	heroDaoFieldFriends uint64 = 1 << iota
	heroDaoFieldPos     uint64 = 1 << iota
	heroDaoFieldEquips  uint64 = 1 << iota
)

func (d *HeroDao) markNameDirty() {
	if err := nest.MarkPersist(d, heroDaoFieldName); err != nil {
		panic(fmt.Errorf("HeroDao: mark Name persistence: %w", err))
	}
	d.tracker.MarkSync(heroDaoFieldName)
}

func (d *HeroDao) markLevelDirty() {
	if err := nest.MarkPersist(d, heroDaoFieldLevel); err != nil {
		panic(fmt.Errorf("HeroDao: mark Level persistence: %w", err))
	}
	d.tracker.MarkSync(heroDaoFieldLevel)
}

func (d *HeroDao) markExpDirty() {
	if err := nest.MarkPersist(d, heroDaoFieldExp); err != nil {
		panic(fmt.Errorf("HeroDao: mark Exp persistence: %w", err))
	}
	d.tracker.MarkSync(heroDaoFieldExp)
}

func (d *HeroDao) markLoginAtDirty() {
	if err := nest.MarkPersist(d, heroDaoFieldLoginAt); err != nil {
		panic(fmt.Errorf("HeroDao: mark LoginAt persistence: %w", err))
	}
}

func (d *HeroDao) markItemsDirty() {
	if err := nest.MarkPersist(d, heroDaoFieldItems); err != nil {
		panic(fmt.Errorf("HeroDao: mark Items persistence: %w", err))
	}
	d.tracker.MarkSync(heroDaoFieldItems)
}

func (d *HeroDao) markFriendsDirty() {
	if err := nest.MarkPersist(d, heroDaoFieldFriends); err != nil {
		panic(fmt.Errorf("HeroDao: mark Friends persistence: %w", err))
	}
	d.tracker.MarkSync(heroDaoFieldFriends)
}

func (d *HeroDao) markPosDirty() {
	if err := nest.MarkPersist(d, heroDaoFieldPos); err != nil {
		panic(fmt.Errorf("HeroDao: mark Pos persistence: %w", err))
	}
	d.tracker.MarkSync(heroDaoFieldPos)
}

func (d *HeroDao) markEquipsDirty() {
	if err := nest.MarkPersist(d, heroDaoFieldEquips); err != nil {
		panic(fmt.Errorf("HeroDao: mark Equips persistence: %w", err))
	}
	d.tracker.MarkSync(heroDaoFieldEquips)
}

func (d *HeroDao) markItemsKeyDirty(key int64, val int32) {
	if path, ok := dataengine.MapPatchPath("items", key); ok {
		if err := nest.MarkPersistSet(d, heroDaoFieldItems, path, val); err != nil {
			panic(fmt.Errorf("HeroDao: mark Items key persistence: %w", err))
		}
	} else {
		if err := nest.MarkPersistFull(d, heroDaoFieldItems, "items"); err != nil {
			panic(fmt.Errorf("HeroDao: mark Items persistence: %w", err))
		}
	}
	d.tracker.MarkSync(heroDaoFieldItems)
}

func (d *HeroDao) markItemsKeyDeleted(key int64) {
	if path, ok := dataengine.MapPatchPath("items", key); ok {
		if err := nest.MarkPersistUnset(d, heroDaoFieldItems, path); err != nil {
			panic(fmt.Errorf("HeroDao: mark Items delete persistence: %w", err))
		}
	} else {
		if err := nest.MarkPersistFull(d, heroDaoFieldItems, "items"); err != nil {
			panic(fmt.Errorf("HeroDao: mark Items persistence: %w", err))
		}
	}
	d.tracker.MarkSync(heroDaoFieldItems)
}

func (d *HeroDao) markEquipsKeyDirty(key int64, val *EquipInfo) {
	if path, ok := dataengine.MapPatchPath("equips", key); ok {
		if err := nest.MarkPersistSet(d, heroDaoFieldEquips, path, val); err != nil {
			panic(fmt.Errorf("HeroDao: mark Equips key persistence: %w", err))
		}
	} else {
		if err := nest.MarkPersistFull(d, heroDaoFieldEquips, "equips"); err != nil {
			panic(fmt.Errorf("HeroDao: mark Equips persistence: %w", err))
		}
	}
	d.tracker.MarkSync(heroDaoFieldEquips)
}

func (d *HeroDao) markEquipsKeyDeleted(key int64) {
	if path, ok := dataengine.MapPatchPath("equips", key); ok {
		if err := nest.MarkPersistUnset(d, heroDaoFieldEquips, path); err != nil {
			panic(fmt.Errorf("HeroDao: mark Equips delete persistence: %w", err))
		}
	} else {
		if err := nest.MarkPersistFull(d, heroDaoFieldEquips, "equips"); err != nil {
			panic(fmt.Errorf("HeroDao: mark Equips persistence: %w", err))
		}
	}
	d.tracker.MarkSync(heroDaoFieldEquips)
}

// Init wires dirty callbacks for nested structs and map values.
func (d *HeroDao) Init() {
	d.pos.SetNotify(d.markPosDirty)
	if d.equips != nil {
		d.equips.Range(func(key int64, v *EquipInfo) bool {
			if v != nil {
				key, v := key, v
				v.SetNotify(func() { d.markEquipsKeyDirty(key, v) })
			}
			return true
		})
	}
}

// --- Accessors ---

func (d *HeroDao) GetName() string { return d.name }

func (d *HeroDao) GetLevel() int32 { return d.level }

func (d *HeroDao) GetExp() int64 { return d.exp }

func (d *HeroDao) GetLoginAt() int64 { return d.loginAt }

func (d *HeroDao) GetFriends(idx int) (int64, bool) {
	if idx < 0 || idx >= len(d.friends) {
		var zero int64
		return zero, false
	}
	return d.friends[idx], true
}

func (d *HeroDao) GetPos() *Position { return &d.pos }

// --- Mutators ---

// recordUndo / recordUndoToken register the inverse operation and panic when
// registration fails: continuing would let the mutation escape rollback
// coverage, silently breaking the transaction guarantee.
func (d *HeroDao) recordUndo(tx *nest.RollbackTx, field uint64, fn func() error) {
	if err := tx.RecordUndo(d, field, fn); err != nil {
		panic(fmt.Errorf("HeroDao: record undo: %w", err))
	}
}

func (d *HeroDao) recordUndoToken(tx *nest.RollbackTx, field uint64, token any, fn func() error) {
	if err := tx.RecordUndoToken(d, field, token, fn); err != nil {
		panic(fmt.Errorf("HeroDao: record undo: %w", err))
	}
}

func (d *HeroDao) SetName(v string) {
	if d.name != v {
		if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
			old := d.name
			d.recordUndo(tx, heroDaoFieldName, func() error { d.name = old; return nil })
		}
		d.name = v
		d.markNameDirty()
	}
}

func (d *HeroDao) SetLevel(v int32) {
	if d.level != v {
		if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
			old := d.level
			d.recordUndo(tx, heroDaoFieldLevel, func() error { d.level = old; return nil })
		}
		d.level = v
		d.markLevelDirty()
	}
}

func (d *HeroDao) SetExp(v int64) {
	if d.exp != v {
		if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
			old := d.exp
			d.recordUndo(tx, heroDaoFieldExp, func() error { d.exp = old; return nil })
		}
		d.exp = v
		d.markExpDirty()
	}
}

func (d *HeroDao) SetLoginAt(v int64) {
	if d.loginAt != v {
		if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
			old := d.loginAt
			d.recordUndo(tx, heroDaoFieldLoginAt, func() error { d.loginAt = old; return nil })
		}
		d.loginAt = v
		d.markLoginAtDirty()
	}
}

func (d *HeroDao) GetItems(key int64) (int32, bool) {
	if d.items == nil {
		var zero int32
		return zero, false
	}
	return d.items.Get(key)
}

func (d *HeroDao) SetItems(key int64, val int32) {
	if d.items == nil {
		d.items = fmap.NewSmallSafeMap[int64, int32](0)
	}
	if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
		old, existed := d.items.Get(key)
		d.recordUndoToken(tx, heroDaoFieldItems, key, func() error {
			if existed {
				d.items.Set(key, old)
			} else {
				d.items.Delete(key)
			}
			d.Init()
			return nil
		})
	}
	d.items.Set(key, val)
	d.markItemsKeyDirty(key, val)
}

func (d *HeroDao) DelItems(key int64) {
	if d.items == nil {
		return
	}
	if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
		old, existed := d.items.Get(key)
		d.recordUndoToken(tx, heroDaoFieldItems, key, func() error {
			if existed {
				d.items.Set(key, old)
				d.Init()
			}
			return nil
		})
	}
	if d.items.Delete(key) {
		d.markItemsKeyDeleted(key)
	}
}

func (d *HeroDao) RangeItems(f func(key int64, val int32) bool) {
	if d.items == nil || f == nil {
		return
	}
	d.items.Range(f)
}

func (d *HeroDao) ItemsLen() int {
	if d.items == nil {
		return 0
	}
	return d.items.Len()
}

func (d *HeroDao) AddFriends(v int64) {
	if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
		old := d.friends
		d.recordUndo(tx, heroDaoFieldFriends, func() error {
			d.friends = old
			d.Init()
			return nil
		})
	}
	d.friends = append(d.friends, v)
	d.markFriendsDirty()
}

func (d *HeroDao) SetFriendsAll(v []int64) {
	if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
		old := d.friends
		d.recordUndo(tx, heroDaoFieldFriends, func() error {
			d.friends = old
			d.Init()
			return nil
		})
	}
	d.friends = append([]int64(nil), v...)
	d.markFriendsDirty()
}

func (d *HeroDao) RangeFriends(f func(idx int, val int64) bool) {
	if f == nil {
		return
	}
	for i, v := range d.friends {
		if !f(i, v) {
			break
		}
	}
}

func (d *HeroDao) FriendsLen() int {
	return len(d.friends)
}

func (d *HeroDao) SetPos(v Position) {
	if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
		old := d.pos
		d.recordUndo(tx, heroDaoFieldPos, func() error {
			d.pos = old
			d.pos.SetNotify(d.markPosDirty)
			return nil
		})
	}
	d.pos = v
	d.pos.SetNotify(d.markPosDirty)
	d.markPosDirty()
}

func (d *HeroDao) GetEquips(key int64) (*EquipInfo, bool) {
	if d.equips == nil {
		var zero *EquipInfo
		return zero, false
	}
	return d.equips.Get(key)
}

func (d *HeroDao) SetEquips(key int64, val *EquipInfo) {
	if d.equips == nil {
		d.equips = fmap.NewSmallSafeMap[int64, *EquipInfo](0)
	}
	if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
		old, existed := d.equips.Get(key)
		d.recordUndoToken(tx, heroDaoFieldEquips, key, func() error {
			if existed {
				d.equips.Set(key, old)
			} else {
				d.equips.Delete(key)
			}
			d.Init()
			return nil
		})
	}
	if val != nil {
		val.SetNotify(func() { d.markEquipsKeyDirty(key, val) })
	}
	d.equips.Set(key, val)
	d.markEquipsKeyDirty(key, val)
}

func (d *HeroDao) DelEquips(key int64) {
	if d.equips == nil {
		return
	}
	if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
		old, existed := d.equips.Get(key)
		d.recordUndoToken(tx, heroDaoFieldEquips, key, func() error {
			if existed {
				d.equips.Set(key, old)
				d.Init()
			}
			return nil
		})
	}
	if v, ok := d.equips.Get(key); ok && v != nil {
		v.SetNotify(nil)
	}
	if d.equips.Delete(key) {
		d.markEquipsKeyDeleted(key)
	}
}

func (d *HeroDao) RangeEquips(f func(key int64, val *EquipInfo) bool) {
	if d.equips == nil || f == nil {
		return
	}
	d.equips.Range(f)
}

func (d *HeroDao) EquipsLen() int {
	if d.equips == nil {
		return 0
	}
	return d.equips.Len()
}

func (d *HeroDao) heroDaoItemsRawMap() map[int64]int32 {
	if d.items == nil {
		return nil
	}
	ret := make(map[int64]int32, d.items.Len())
	d.items.Range(func(key int64, val int32) bool {
		ret[key] = val
		return true
	})
	return ret
}

func (d *HeroDao) setItemsRawMap(src map[int64]int32) {
	d.items = fmap.NewSmallSafeMap[int64, int32](len(src))
	for key, val := range src {
		d.items.Set(key, val)
	}
}

func (d *HeroDao) heroDaoEquipsRawMap() map[int64]*EquipInfo {
	if d.equips == nil {
		return nil
	}
	ret := make(map[int64]*EquipInfo, d.equips.Len())
	d.equips.Range(func(key int64, val *EquipInfo) bool {
		ret[key] = val
		return true
	})
	return ret
}

func (d *HeroDao) setEquipsRawMap(src map[int64]*EquipInfo) {
	d.equips = fmap.NewSmallSafeMap[int64, *EquipInfo](len(src))
	for key, val := range src {
		if val != nil {
			key, val := key, val
			val.SetNotify(func() { d.markEquipsKeyDirty(key, val) })
		}
		d.equips.Set(key, val)
	}
}

// --- Marshal (persist fields) ---

// CaptureRollbackState is side-effect free and includes transient and
// sync-only fields. Persistence changes live in RollbackTx, not in the DAO.
func (d *HeroDao) CaptureRollbackState() ([]byte, error) {
	type rollbackDoc struct {
		Id      int64                `bson:"_id"`
		Name    string               `bson:"name"`
		Level   int32                `bson:"level"`
		Exp     int64                `bson:"exp"`
		LoginAt int64                `bson:"login_at"`
		Items   map[int64]int32      `bson:"items"`
		Friends []int64              `bson:"friends"`
		Pos     Position             `bson:"pos"`
		Equips  map[int64]*EquipInfo `bson:"equips"`
	}
	doc := rollbackDoc{
		Id:      d.id,
		Name:    d.name,
		Level:   d.level,
		Exp:     d.exp,
		LoginAt: d.loginAt,
		Items:   d.heroDaoItemsRawMap(),
		Friends: d.friends,
		Pos:     d.pos,
		Equips:  d.heroDaoEquipsRawMap(),
	}
	return bson.Marshal(doc)
}

func (d *HeroDao) RestoreRollbackState(raw []byte) error {
	type rollbackDoc struct {
		Id      int64                `bson:"_id"`
		Name    string               `bson:"name"`
		Level   int32                `bson:"level"`
		Exp     int64                `bson:"exp"`
		LoginAt int64                `bson:"login_at"`
		Items   map[int64]int32      `bson:"items"`
		Friends []int64              `bson:"friends"`
		Pos     Position             `bson:"pos"`
		Equips  map[int64]*EquipInfo `bson:"equips"`
	}
	var doc rollbackDoc
	if err := bson.Unmarshal(raw, &doc); err != nil {
		return err
	}
	d.id = doc.Id
	d.name = doc.Name
	d.level = doc.Level
	d.exp = doc.Exp
	d.loginAt = doc.LoginAt
	d.setItemsRawMap(doc.Items)
	d.friends = doc.Friends
	d.pos = doc.Pos
	d.setEquipsRawMap(doc.Equips)
	d.Init()
	return nil
}

func (d *HeroDao) marshalCommitState() ([]byte, error) {
	doc := bson.M{
		"_id":      d.id,
		"_schema":  HeroDaoSchemaVersion,
		"name":     d.name,
		"level":    d.level,
		"exp":      d.exp,
		"login_at": d.loginAt,
		"items":    d.heroDaoItemsRawMap(),
		"friends":  d.friends,
		"pos":      d.pos,
		"equips":   d.heroDaoEquipsRawMap(),
	}
	return bson.Marshal(doc)
}

func (d *HeroDao) PrepareMutation(change nest.PersistChange) (dataengine.Mutation, error) {
	version := d.tracker.Version()
	mutation := dataengine.Mutation{
		Key: dataengine.DocumentKey{
			Database: d.DbName(), Scope: dataengine.DatabaseScope(d.DbScope()),
			Resource: d.CollName(), ID: d.Id(),
		},
		Kind: dataengine.MutationPatch, ExpectedVersion: version, NextVersion: version + 1,
		Mask: change.Mask, Schema: HeroDaoSchemaVersion, Codec: "bson-v2",
	}
	if change.Delete {
		mutation.Kind = dataengine.MutationDelete
		return mutation, nil
	}
	if version == 0 || change.Mask == dataengine.AllFields {
		data, err := d.marshalCommitState()
		if err != nil {
			return dataengine.Mutation{}, fmt.Errorf("prepare put %s/%d: %w", d.CollName(), d.id, err)
		}
		mutation.Kind = dataengine.MutationPut
		mutation.Data = data
		return mutation, nil
	}
	patch, err := d.marshalPersistPatchBSON(change)
	if err != nil {
		return dataengine.Mutation{}, fmt.Errorf("prepare patch %s/%d: %w", d.CollName(), d.id, err)
	}
	mutation.Patch = patch
	return mutation, nil
}

func (d *HeroDao) AcceptMutation(mutation dataengine.Mutation) error {
	return d.tracker.AcceptVersion(mutation.ExpectedVersion, mutation.NextVersion)
}

func (d *HeroDao) Marshal() []byte {
	return d.MarshalPersist(dataengine.AllFields)
}

func (d *HeroDao) MarshalPersist(mask uint64) []byte {
	return d.marshalPersistData(mask)
}

func (d *HeroDao) marshalPersistData(mask uint64) []byte {
	_ = mask // full payload is used for inserts and safe fallback.
	doc := bson.M{
		"_id":      d.id,
		"_schema":  HeroDaoSchemaVersion,
		"name":     d.name,
		"level":    d.level,
		"exp":      d.exp,
		"login_at": d.loginAt,
		"items":    d.heroDaoItemsRawMap(),
		"friends":  d.friends,
		"pos":      d.pos,
		"equips":   d.heroDaoEquipsRawMap(),
	}
	data, err := bson.Marshal(doc)
	if err != nil {
		// The interface has no error slot and a nil payload would be
		// persisted as silent data loss; a marshal failure here is a
		// programming error (unserializable state), so fail loudly and let
		// Data Engine WAL recovery owns the aftermath.
		panic(fmt.Errorf("HeroDao: marshal persist data: %w", err))
	}
	return data
}

func (d *HeroDao) persistChangeHasPath(change nest.PersistChange, field string) bool {
	prefix := field + "."
	for path := range change.Set {
		if path == field || len(path) > len(prefix) && path[:len(prefix)] == prefix {
			return true
		}
	}
	for _, path := range change.Unset {
		if path == field || len(path) > len(prefix) && path[:len(prefix)] == prefix {
			return true
		}
	}
	return false
}

func (d *HeroDao) persistChangePathCovered(change nest.PersistChange, path string) bool {
	for field := range change.FullFields {
		prefix := field + "."
		if path == field || len(path) > len(prefix) && path[:len(prefix)] == prefix {
			return true
		}
	}
	return false
}

func (d *HeroDao) marshalPersistPatchBSON(change nest.PersistChange) (dataengine.FieldPatch, error) {
	set := make(map[string]any, len(change.Set)+len(change.FullFields))
	if change.Mask&heroDaoFieldName != 0 {
		set["name"] = d.name
	}
	if change.Mask&heroDaoFieldLevel != 0 {
		set["level"] = d.level
	}
	if change.Mask&heroDaoFieldExp != 0 {
		set["exp"] = d.exp
	}
	if change.Mask&heroDaoFieldLoginAt != 0 {
		set["login_at"] = d.loginAt
	}
	if change.Mask&heroDaoFieldItems != 0 {
		_, full := change.FullFields["items"]
		if full || !d.persistChangeHasPath(change, "items") {
			set["items"] = d.heroDaoItemsRawMap()
		}
	}
	if change.Mask&heroDaoFieldFriends != 0 {
		set["friends"] = d.friends
	}
	if change.Mask&heroDaoFieldPos != 0 {
		set["pos"] = d.pos
	}
	if change.Mask&heroDaoFieldEquips != 0 {
		_, full := change.FullFields["equips"]
		if full || !d.persistChangeHasPath(change, "equips") {
			set["equips"] = d.heroDaoEquipsRawMap()
		}
	}
	for path, value := range change.Set {
		if !d.persistChangePathCovered(change, path) {
			set[path] = value
		}
	}
	var raw []byte
	if len(set) != 0 {
		keys := make([]string, 0, len(set))
		for path := range set {
			keys = append(keys, path)
		}
		sort.Strings(keys)
		doc := make(bson.D, 0, len(keys))
		for _, path := range keys {
			doc = append(doc, bson.E{Key: path, Value: set[path]})
		}
		var err error
		raw, err = bson.Marshal(doc)
		if err != nil {
			return dataengine.FieldPatch{}, err
		}
	}
	return dataengine.FieldPatch{SetBSON: raw, Unset: append([]string(nil), change.Unset...)}, nil
}

func (d *HeroDao) MarshalSync(mask uint64) []byte {
	doc := bson.M{
		"_id": d.id,
	}
	if mask&heroDaoFieldName != 0 {
		doc["name"] = d.name
	}
	if mask&heroDaoFieldLevel != 0 {
		doc["level"] = d.level
	}
	if mask&heroDaoFieldExp != 0 {
		doc["exp"] = d.exp
	}
	if mask&heroDaoFieldItems != 0 {
		doc["items"] = d.heroDaoItemsRawMap()
	}
	if mask&heroDaoFieldFriends != 0 {
		doc["friends"] = d.friends
	}
	if mask&heroDaoFieldPos != 0 {
		doc["pos"] = d.pos
	}
	if mask&heroDaoFieldEquips != 0 {
		doc["equips"] = d.heroDaoEquipsRawMap()
	}
	if len(doc) == 1 {
		return nil
	}
	data, err := bson.Marshal(doc)
	if err != nil {
		// nil already means "nothing to sync"; returning it on failure would
		// silently drop a sync payload. See marshalPersistData.
		panic(fmt.Errorf("HeroDao: marshal sync data: %w", err))
	}
	return data
}

func (d *HeroDao) ApplySync(raw []byte) error {
	var doc bson.M
	if err := bson.Unmarshal(raw, &doc); err != nil {
		return err
	}
	if v, ok := doc["name"]; ok {
		data, err := bson.Marshal(bson.M{"v": v})
		if err != nil {
			return err
		}
		var wrap struct {
			V string `bson:"v"`
		}
		if err := bson.Unmarshal(data, &wrap); err != nil {
			return err
		}
		d.name = wrap.V
	}
	if v, ok := doc["level"]; ok {
		data, err := bson.Marshal(bson.M{"v": v})
		if err != nil {
			return err
		}
		var wrap struct {
			V int32 `bson:"v"`
		}
		if err := bson.Unmarshal(data, &wrap); err != nil {
			return err
		}
		d.level = wrap.V
	}
	if v, ok := doc["exp"]; ok {
		data, err := bson.Marshal(bson.M{"v": v})
		if err != nil {
			return err
		}
		var wrap struct {
			V int64 `bson:"v"`
		}
		if err := bson.Unmarshal(data, &wrap); err != nil {
			return err
		}
		d.exp = wrap.V
	}
	if v, ok := doc["items"]; ok {
		data, err := bson.Marshal(bson.M{"v": v})
		if err != nil {
			return err
		}
		var wrap struct {
			V map[int64]int32 `bson:"v"`
		}
		if err := bson.Unmarshal(data, &wrap); err != nil {
			return err
		}
		d.setItemsRawMap(wrap.V)
	}
	if v, ok := doc["friends"]; ok {
		data, err := bson.Marshal(bson.M{"v": v})
		if err != nil {
			return err
		}
		var wrap struct {
			V []int64 `bson:"v"`
		}
		if err := bson.Unmarshal(data, &wrap); err != nil {
			return err
		}
		d.friends = wrap.V
	}
	if v, ok := doc["pos"]; ok {
		data, err := bson.Marshal(bson.M{"v": v})
		if err != nil {
			return err
		}
		var wrap struct {
			V Position `bson:"v"`
		}
		if err := bson.Unmarshal(data, &wrap); err != nil {
			return err
		}
		d.pos = wrap.V
	}
	if v, ok := doc["equips"]; ok {
		data, err := bson.Marshal(bson.M{"v": v})
		if err != nil {
			return err
		}
		var wrap struct {
			V map[int64]*EquipInfo `bson:"v"`
		}
		if err := bson.Unmarshal(data, &wrap); err != nil {
			return err
		}
		d.setEquipsRawMap(wrap.V)
	}
	d.Init()
	return nil
}

// --- Unmarshal ---

func (d *HeroDao) Unmarshal(raw []byte) error {
	type rawDoc struct {
		Id      int64                `bson:"_id"`
		Name    string               `bson:"name"`
		Level   int32                `bson:"level"`
		Exp     int64                `bson:"exp"`
		LoginAt int64                `bson:"login_at"`
		Items   map[int64]int32      `bson:"items"`
		Friends []int64              `bson:"friends"`
		Pos     Position             `bson:"pos"`
		Equips  map[int64]*EquipInfo `bson:"equips"`
	}
	var dd rawDoc
	if err := bson.Unmarshal(raw, &dd); err != nil {
		return err
	}
	d.id = dd.Id
	d.name = dd.Name
	d.level = dd.Level
	d.exp = dd.Exp
	d.loginAt = dd.LoginAt
	d.setItemsRawMap(dd.Items)
	d.friends = dd.Friends
	d.pos = dd.Pos
	d.setEquipsRawMap(dd.Equips)
	d.Init()
	return nil
}

// RestorePersisted is the single production hydration path used by the
// Data Engine aggregate repository. Migration and tracker restoration happen
// before the DAO is published through its entity.
func (d *HeroDao) RestorePersisted(raw []byte, schemaVersion uint32, version uint64) error {
	if schemaVersion > HeroDaoSchemaVersion {
		return fmt.Errorf("dao HeroDao: stored schema %d is newer than runtime schema %d", schemaVersion, HeroDaoSchemaVersion)
	}
	var err error
	if schemaVersion < HeroDaoSchemaVersion {
		raw, err = d.Migrate(raw, schemaVersion)
		if err != nil {
			return fmt.Errorf("dao HeroDao: migrate schema %d to %d: %w", schemaVersion, HeroDaoSchemaVersion, err)
		}
	}
	if err := d.Unmarshal(raw); err != nil {
		return err
	}
	d.tracker.SetVersion(version)
	d.CleanDirty()
	return nil
}

// compile-time import guards
var (
	_ = dataengine.Tracker{}
	_ = bson.M{}
)
