// Code generated by tool/dao. DO NOT EDIT.
package testdata

import (
	"fmt"

	"github.com/tjbdwanghaibo/roost-core/dataengine"
	"github.com/tjbdwanghaibo/roost-core/nest"
	fmap "github.com/tjbdwanghaibo/roost-core/safemap"
	"go.mongodb.org/mongo-driver/v2/bson"
)

// EquipInfo is a nested struct with dirty propagation.
//
// The hook is excluded from every codec: it is runtime wiring, not state, and
// an exported embedded struct with no exported fields would otherwise be
// written as an empty "dirtyhook" sub-document (U-0224).
type EquipInfo struct {
	dataengine.DirtyHook `bson:"-" json:"-"`
	level                int32
	star                 int32
	gems                 *fmap.SmallSafeMap[int32, *GemInfo]
}

// --- BSON (persistence, rollback capture, sync) ---
//
// The fields are unexported so every mutation goes through the setters below
// — that is what makes dirty tracking and undo impossible to bypass — and the
// reflection-based codec cannot see unexported fields. Without these two
// methods the parent DAO's document carried {"<field>": {"dirtyhook": {}}}:
// no data at all (U-0224). MarshalBSON has a value receiver because the
// parent places the struct itself, not a pointer, into its bson.M.
type equipInfoBSONDoc struct {
	Level int32              `bson:"level"`
	Star  int32              `bson:"star"`
	Gems  map[int32]*GemInfo `bson:"gems"`
}

func (s EquipInfo) MarshalBSON() ([]byte, error) {
	return bson.Marshal(equipInfoBSONDoc{
		Level: s.level,
		Star:  s.star,
		Gems:  s.gemsRawMap(),
	})
}

func (s *EquipInfo) UnmarshalBSON(raw []byte) error {
	var doc equipInfoBSONDoc
	if err := bson.Unmarshal(raw, &doc); err != nil {
		return err
	}
	s.level = doc.Level
	s.star = doc.Star
	s.setGemsRawMap(doc.Gems)
	return nil
}

func (s EquipInfo) gemsRawMap() map[int32]*GemInfo {
	if s.gems == nil {
		return nil
	}
	ret := make(map[int32]*GemInfo, s.gems.Len())
	s.gems.Range(func(key int32, val *GemInfo) bool {
		ret[key] = val
		return true
	})
	return ret
}

func (s *EquipInfo) setGemsRawMap(src map[int32]*GemInfo) {
	s.gems = fmap.NewSmallSafeMap[int32, *GemInfo](len(src))
	for key, val := range src {
		s.gems.Set(key, val)
	}
}

func (s *EquipInfo) GetLevel() int32 { return s.level }

func (s *EquipInfo) GetStar() int32 { return s.star }

func (s *EquipInfo) GetGems(key int32) (*GemInfo, bool) {
	if s.gems == nil {
		var zero *GemInfo
		return zero, false
	}
	return s.gems.Get(key)
}

func (s *EquipInfo) RangeGems(f func(key int32, val *GemInfo) bool) {
	if s.gems == nil || f == nil {
		return
	}
	s.gems.Range(f)
}

func (s *EquipInfo) GemsLen() int {
	if s.gems == nil {
		return 0
	}
	return s.gems.Len()
}

func (s *EquipInfo) SetLevel(v int32) {
	if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
		old := s.level
		if err := tx.RecordUndo(s, uint64(0), func() error { s.level = old; return nil }); err != nil {
			// A mutation without undo coverage silently breaks rollback;
			// failing loudly matches the generated DAO setters.
			panic(fmt.Errorf("EquipInfo: record undo: %w", err))
		}
	}
	if s.level != v {
		s.level = v
		s.Mark()
	}
}

func (s *EquipInfo) SetStar(v int32) {
	if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
		old := s.star
		if err := tx.RecordUndo(s, uint64(1), func() error { s.star = old; return nil }); err != nil {
			// A mutation without undo coverage silently breaks rollback;
			// failing loudly matches the generated DAO setters.
			panic(fmt.Errorf("EquipInfo: record undo: %w", err))
		}
	}
	if s.star != v {
		s.star = v
		s.Mark()
	}
}

func (s *EquipInfo) SetGems(v map[int32]*GemInfo) {
	if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
		old := s.gems
		if err := tx.RecordUndo(s, uint64(2), func() error { s.gems = old; return nil }); err != nil {
			// A mutation without undo coverage silently breaks rollback;
			// failing loudly matches the generated DAO setters.
			panic(fmt.Errorf("EquipInfo: record undo: %w", err))
		}
	}
	s.gems = fmap.NewSmallSafeMap[int32, *GemInfo](len(v))
	for key, val := range v {
		s.gems.Set(key, val)
	}
	s.Mark()
}
