// Code generated by tool/dao. DO NOT EDIT.
package testdata

import (
	"fmt"

	"github.com/tjbdwanghaibo/cube-core/checkpoint"
	"github.com/tjbdwanghaibo/cube-core/nest"
)

// Position is a nested struct with dirty propagation.
type Position struct {
	checkpoint.DirtyHook
	x int32
	y int32
}

func (s *Position) GetX() int32 { return s.x }

func (s *Position) GetY() int32 { return s.y }

func (s *Position) SetX(v int32) {
	if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
		old := s.x
		if err := tx.RecordUndo(s, uint64(0), func() error { s.x = old; return nil }); err != nil {
			// A mutation without undo coverage silently breaks rollback;
			// failing loudly matches the generated DAO setters.
			panic(fmt.Errorf("Position: record undo: %w", err))
		}
	}
	if s.x != v {
		s.x = v
		s.Mark()
	}
}

func (s *Position) SetY(v int32) {
	if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
		old := s.y
		if err := tx.RecordUndo(s, uint64(1), func() error { s.y = old; return nil }); err != nil {
			// A mutation without undo coverage silently breaks rollback;
			// failing loudly matches the generated DAO setters.
			panic(fmt.Errorf("Position: record undo: %w", err))
		}
	}
	if s.y != v {
		s.y = v
		s.Mark()
	}
}
